#!/usr/bin/env python3
"""Snippet-corpus generator. Run from the snippets/ directory:

    python3 gen_snippets.py

Writes one <name>/ directory per row in the table. Each directory
contains `input.py` (driver) and `want.txt` (golden output). The
Go-side TestSnippetParity does not invoke this script; it only
reads what is on disk. Treat the generator as a convenience for
authoring or refreshing the corpus after a binding change.
"""

from __future__ import annotations

import os
import sys
import textwrap


HERE = os.path.dirname(os.path.abspath(__file__))


# Each row: (name, driver-body, expected-stdout).
# Driver bodies share a preamble that puts the generator dir on
# sys.path; the helper below adds it.
ROWS: list[tuple[str, str, str]] = [
    (
        "peek",
        'from go_generators_common import render_macro\nprint(render_macro("PEEK", ("1",)))\n',
        "e.peek(1)\n",
    ),
    (
        "poke",
        'from go_generators_common import render_macro\nprint(render_macro("POKE", ("0", "value")))\n',
        "e.poke(0, value)\n",
    ),
    (
        "top",
        'from go_generators_common import render_macro\nprint(render_macro("TOP", ()))\n',
        "e.peek(0)\n",
    ),
    (
        "second",
        'from go_generators_common import render_macro\nprint(render_macro("SECOND", ()))\n',
        "e.peek(1)\n",
    ),
    (
        "stack_grow",
        'from go_generators_common import render_macro\nprint(render_macro("STACK_GROW", ("1",)))\n',
        "e.f.StackTop += 1\n",
    ),
    (
        "stack_shrink",
        'from go_generators_common import render_macro\nprint(render_macro("STACK_SHRINK", ("2",)))\n',
        "e.f.StackTop -= 2\n",
    ),
    (
        "getlocal",
        'from go_generators_common import render_macro\nprint(render_macro("GETLOCAL", ("idx",)))\n',
        "e.localAt(idx)\n",
    ),
    (
        "setlocal",
        'from go_generators_common import render_macro\nprint(render_macro("SETLOCAL", ("0", "ref")))\n',
        "e.setLocal(0, ref)\n",
    ),
    (
        "jumpby",
        'from go_generators_common import render_macro\nprint(render_macro("JUMPBY", ("delta",)))\n',
        "e.jumpBy(delta)\n",
    ),
    (
        "jumpto",
        'from go_generators_common import render_macro\nprint(render_macro("JUMPTO", ("target",)))\n',
        "e.f.InstrPtr = target\n",
    ),
    (
        "deopt_if",
        'from go_generators_common import render_macro\nprint(render_macro("DEOPT_IF", ("!ok", "LOAD_GLOBAL")))\n',
        "if !ok { return e.deoptTo(LOAD_GLOBAL) }\n",
    ),
    (
        "error_if",
        'from go_generators_common import render_macro\nprint(render_macro("ERROR_IF", ("err != nil", "errLabel")))\n',
        "if err != nil { goto errLabel }\n",
    ),
    (
        "stackref_from_new",
        'from go_generators_common import render_macro\nprint(render_macro("PyStackRef_FromPyObjectNew", ("v",)))\n',
        "stackref.FromObjectNew(v)\n",
    ),
    (
        "stackref_borrow",
        'from go_generators_common import render_macro\nprint(render_macro("PyStackRef_AsPyObjectBorrow", ("ref",)))\n',
        "ref.AsObject()\n",
    ),
    (
        "stackref_close",
        'from go_generators_common import render_macro\nprint(render_macro("PyStackRef_CLOSE", ("ref",)))\n',
        "_ = 0 // PyStackRef_CLOSE: GC no-op\n",
    ),
    (
        "refcount_noop_incref",
        'from go_generators_common import render_macro\nprint(render_macro("Py_INCREF", ("v",)))\n',
        "_ = 0 // Py_INCREF/DECREF: GC no-op\n",
    ),
    (
        "instruction_size",
        'from go_generators_common import render_macro\nprint(render_macro("INSTRUCTION_SIZE", ()))\n',
        "2\n",
    ),
    (
        "header",
        textwrap.dedent("""\
            import sys
            from go_generators_common import write_go_header
            write_go_header(sys.stdout, "demo_generator.py",
                            ["Python/bytecodes.c"], "vm")
        """),
        textwrap.dedent("""\
            // Code generated by Tools/cases_generator/demo_generator.py. DO NOT EDIT.
            // Source:
            //   Python/bytecodes.c
            // Regenerate via: go run ./Tools/regen-cases --target=go

            package vm

        """),
    ),
    (
        "writer_indent_block",
        textwrap.dedent("""\
            import sys
            from gowriter import GoWriter
            w = GoWriter(sys.stdout)
            w.emit_str("func opNop() {\\n")
            w.emit_str("return\\n")
            w.emit_str("}\\n")
        """),
        "func opNop() {\n\treturn\n}\n",
    ),
    (
        "writer_nested_braces",
        textwrap.dedent("""\
            import sys
            from gowriter import GoWriter
            w = GoWriter(sys.stdout)
            w.emit_str("func loop() {\\n")
            w.emit_str("for i := 0; i < 3; i++ {\\n")
            w.emit_str("x++\\n")
            w.emit_str("}\\n")
            w.emit_str("}\\n")
        """),
        "func loop() {\n\tfor i := 0; i < 3; i++ {\n\t\tx++\n\t}\n}\n",
    ),
]


PREAMBLE = "import os, sys\nsys.path.insert(0, os.environ['CASES_GENERATOR_DIR'])\n"


def main() -> int:
    for name, body, want in ROWS:
        d = os.path.join(HERE, name)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "input.py"), "w") as fh:
            fh.write(PREAMBLE)
            fh.write(body)
        with open(os.path.join(d, "want.txt"), "w") as fh:
            fh.write(want)
    print(f"wrote {len(ROWS)} snippets", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
