//go:build ignore

// Code generated by Tools/cases_generator/cache_struct_parser.py. DO NOT EDIT.
// Source:
//   Include/internal/pycore_code.h
// Regenerate via: go run ./Tools/regen-cases --target=go

package specialize

// Typed inline-cache accessors. Each struct wraps a slice of
// codeunits (uint16) and an instruction offset; field accessors
// read or write the codeunit at the struct-relative offset. The
// offsets are derived from CPython's _Py<Op>Cache struct member
// order in Include/internal/pycore_code.h.

// LoadGlobalCache wraps _PyLoadGlobalCache (size 4 codeunits).
type LoadGlobalCache struct { code []uint16; instr int }

func LoadGlobalCacheAt(code []uint16, instr int) LoadGlobalCache { return LoadGlobalCache{code, instr} }

func (LoadGlobalCache) Codeunits() int { return 4 }

func (c LoadGlobalCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c LoadGlobalCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }
func (c LoadGlobalCache) ModuleKeysVersion() uint16 { return c.code[c.instr+1+1] }
func (c LoadGlobalCache) SetModuleKeysVersion(v uint16) { c.code[c.instr+1+1] = v }
func (c LoadGlobalCache) BuiltinKeysVersion() uint16 { return c.code[c.instr+1+2] }
func (c LoadGlobalCache) SetBuiltinKeysVersion(v uint16) { c.code[c.instr+1+2] = v }
func (c LoadGlobalCache) Index() uint16 { return c.code[c.instr+1+3] }
func (c LoadGlobalCache) SetIndex(v uint16) { c.code[c.instr+1+3] = v }

// BinaryOpCache wraps _PyBinaryOpCache (size 5 codeunits).
type BinaryOpCache struct { code []uint16; instr int }

func BinaryOpCacheAt(code []uint16, instr int) BinaryOpCache { return BinaryOpCache{code, instr} }

func (BinaryOpCache) Codeunits() int { return 5 }

func (c BinaryOpCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c BinaryOpCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }
func (c BinaryOpCache) ExternalCache0() uint16 { return c.code[c.instr+1+1] }
func (c BinaryOpCache) SetExternalCache0(v uint16) { c.code[c.instr+1+1] = v }
func (c BinaryOpCache) ExternalCache1() uint16 { return c.code[c.instr+1+2] }
func (c BinaryOpCache) SetExternalCache1(v uint16) { c.code[c.instr+1+2] = v }
func (c BinaryOpCache) ExternalCache2() uint16 { return c.code[c.instr+1+3] }
func (c BinaryOpCache) SetExternalCache2(v uint16) { c.code[c.instr+1+3] = v }
func (c BinaryOpCache) ExternalCache3() uint16 { return c.code[c.instr+1+4] }
func (c BinaryOpCache) SetExternalCache3(v uint16) { c.code[c.instr+1+4] = v }

// UnpackSequenceCache wraps _PyUnpackSequenceCache (size 1 codeunits).
type UnpackSequenceCache struct { code []uint16; instr int }

func UnpackSequenceCacheAt(code []uint16, instr int) UnpackSequenceCache { return UnpackSequenceCache{code, instr} }

func (UnpackSequenceCache) Codeunits() int { return 1 }

func (c UnpackSequenceCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c UnpackSequenceCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }

// CompareOpCache wraps _PyCompareOpCache (size 1 codeunits).
type CompareOpCache struct { code []uint16; instr int }

func CompareOpCacheAt(code []uint16, instr int) CompareOpCache { return CompareOpCache{code, instr} }

func (CompareOpCache) Codeunits() int { return 1 }

func (c CompareOpCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c CompareOpCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }

// SuperAttrCache wraps _PySuperAttrCache (size 1 codeunits).
type SuperAttrCache struct { code []uint16; instr int }

func SuperAttrCacheAt(code []uint16, instr int) SuperAttrCache { return SuperAttrCache{code, instr} }

func (SuperAttrCache) Codeunits() int { return 1 }

func (c SuperAttrCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c SuperAttrCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }

// AttrCache wraps _PyAttrCache (size 4 codeunits).
type AttrCache struct { code []uint16; instr int }

func AttrCacheAt(code []uint16, instr int) AttrCache { return AttrCache{code, instr} }

func (AttrCache) Codeunits() int { return 4 }

func (c AttrCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c AttrCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }
func (c AttrCache) Version0() uint16 { return c.code[c.instr+1+1] }
func (c AttrCache) SetVersion0(v uint16) { c.code[c.instr+1+1] = v }
func (c AttrCache) Version1() uint16 { return c.code[c.instr+1+2] }
func (c AttrCache) SetVersion1(v uint16) { c.code[c.instr+1+2] = v }
func (c AttrCache) Index() uint16 { return c.code[c.instr+1+3] }
func (c AttrCache) SetIndex(v uint16) { c.code[c.instr+1+3] = v }

// LoadMethodCache wraps _PyLoadMethodCache (size 9 codeunits).
type LoadMethodCache struct { code []uint16; instr int }

func LoadMethodCacheAt(code []uint16, instr int) LoadMethodCache { return LoadMethodCache{code, instr} }

func (LoadMethodCache) Codeunits() int { return 9 }

func (c LoadMethodCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c LoadMethodCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }
func (c LoadMethodCache) TypeVersion0() uint16 { return c.code[c.instr+1+1] }
func (c LoadMethodCache) SetTypeVersion0(v uint16) { c.code[c.instr+1+1] = v }
func (c LoadMethodCache) TypeVersion1() uint16 { return c.code[c.instr+1+2] }
func (c LoadMethodCache) SetTypeVersion1(v uint16) { c.code[c.instr+1+2] = v }
func (c LoadMethodCache) Descr0() uint16 { return c.code[c.instr+1+3] }
func (c LoadMethodCache) SetDescr0(v uint16) { c.code[c.instr+1+3] = v }
func (c LoadMethodCache) Descr1() uint16 { return c.code[c.instr+1+4] }
func (c LoadMethodCache) SetDescr1(v uint16) { c.code[c.instr+1+4] = v }
func (c LoadMethodCache) Descr2() uint16 { return c.code[c.instr+1+5] }
func (c LoadMethodCache) SetDescr2(v uint16) { c.code[c.instr+1+5] = v }
func (c LoadMethodCache) Descr3() uint16 { return c.code[c.instr+1+6] }
func (c LoadMethodCache) SetDescr3(v uint16) { c.code[c.instr+1+6] = v }
func (c LoadMethodCache) KeysVersion0() uint16 { return c.code[c.instr+1+7] }
func (c LoadMethodCache) SetKeysVersion0(v uint16) { c.code[c.instr+1+7] = v }
func (c LoadMethodCache) KeysVersion1() uint16 { return c.code[c.instr+1+8] }
func (c LoadMethodCache) SetKeysVersion1(v uint16) { c.code[c.instr+1+8] = v }
func (c LoadMethodCache) DictOffset() uint16 { return c.code[c.instr+1+7] }
func (c LoadMethodCache) SetDictOffset(v uint16) { c.code[c.instr+1+7] = v }

// CallCache wraps _PyCallCache (size 3 codeunits).
type CallCache struct { code []uint16; instr int }

func CallCacheAt(code []uint16, instr int) CallCache { return CallCache{code, instr} }

func (CallCache) Codeunits() int { return 3 }

func (c CallCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c CallCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }
func (c CallCache) FuncVersion0() uint16 { return c.code[c.instr+1+1] }
func (c CallCache) SetFuncVersion0(v uint16) { c.code[c.instr+1+1] = v }
func (c CallCache) FuncVersion1() uint16 { return c.code[c.instr+1+2] }
func (c CallCache) SetFuncVersion1(v uint16) { c.code[c.instr+1+2] = v }

// StoreSubscrCache wraps _PyStoreSubscrCache (size 1 codeunits).
type StoreSubscrCache struct { code []uint16; instr int }

func StoreSubscrCacheAt(code []uint16, instr int) StoreSubscrCache { return StoreSubscrCache{code, instr} }

func (StoreSubscrCache) Codeunits() int { return 1 }

func (c StoreSubscrCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c StoreSubscrCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }

// ForIterCache wraps _PyForIterCache (size 1 codeunits).
type ForIterCache struct { code []uint16; instr int }

func ForIterCacheAt(code []uint16, instr int) ForIterCache { return ForIterCache{code, instr} }

func (ForIterCache) Codeunits() int { return 1 }

func (c ForIterCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c ForIterCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }

// SendCache wraps _PySendCache (size 1 codeunits).
type SendCache struct { code []uint16; instr int }

func SendCacheAt(code []uint16, instr int) SendCache { return SendCache{code, instr} }

func (SendCache) Codeunits() int { return 1 }

func (c SendCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c SendCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }

// ToBoolCache wraps _PyToBoolCache (size 3 codeunits).
type ToBoolCache struct { code []uint16; instr int }

func ToBoolCacheAt(code []uint16, instr int) ToBoolCache { return ToBoolCache{code, instr} }

func (ToBoolCache) Codeunits() int { return 3 }

func (c ToBoolCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c ToBoolCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }
func (c ToBoolCache) Version0() uint16 { return c.code[c.instr+1+1] }
func (c ToBoolCache) SetVersion0(v uint16) { c.code[c.instr+1+1] = v }
func (c ToBoolCache) Version1() uint16 { return c.code[c.instr+1+2] }
func (c ToBoolCache) SetVersion1(v uint16) { c.code[c.instr+1+2] = v }

// ContainsOpCache wraps _PyContainsOpCache (size 1 codeunits).
type ContainsOpCache struct { code []uint16; instr int }

func ContainsOpCacheAt(code []uint16, instr int) ContainsOpCache { return ContainsOpCache{code, instr} }

func (ContainsOpCache) Codeunits() int { return 1 }

func (c ContainsOpCache) Counter() uint16 { return c.code[c.instr+1+0] }
func (c ContainsOpCache) SetCounter(v uint16) { c.code[c.instr+1+0] = v }

// CacheCodeunits names each cache struct by its CPython type and
// returns its codeunit footprint. Useful for parity tests.
var CacheCodeunits = map[string]int{
	"_PyLoadGlobalCache": 4,
	"_PyBinaryOpCache": 5,
	"_PyUnpackSequenceCache": 1,
	"_PyCompareOpCache": 1,
	"_PySuperAttrCache": 1,
	"_PyAttrCache": 4,
	"_PyLoadMethodCache": 9,
	"_PyCallCache": 3,
	"_PyStoreSubscrCache": 1,
	"_PyForIterCache": 1,
	"_PySendCache": 1,
	"_PyToBoolCache": 3,
	"_PyContainsOpCache": 1,
}
