// Command unicodedata_go generates module/unicodedata/data_gen.go
// from the UCD tables that ship with CPython 3.14.
//
// Inputs:
//   - $CPYTHON/Modules/unicodedata_db.h: pre-generated by CPython's
//     own Tools/unicode/makeunicodedata.py from the Unicode 16.0
//     UCD source files. We re-parse the C output rather than the
//     UCD source so the runtime tables are byte-identical to
//     CPython.
//
// Output:
//   - module/unicodedata/data_gen.go: Go arrays mirroring the C
//     tables (records, index1/index2, decomp_data, decomp_index1/2,
//     decomp_prefix, comp_data, comp_index, nfc_first, nfc_last,
//     plus the category/bidirectional/east_asian_width name slices
//     and the SHIFT / DECOMP_SHIFT / COMP_SHIFT / TOTAL_FIRST /
//     TOTAL_LAST / UNIDATA_VERSION constants).
//
// Run with:
//
//	go run ./Tools/unicodedata_go \
//	  -cpython=$HOME/cpython-314 \
//	  -out=module/unicodedata/data_gen.go
//
// The output is checked in. The runtime build has no Python
// dependency.
//
// CPython: Modules/unicodedata_db.h (generator output)
// CPython: Tools/unicode/makeunicodedata.py (generator)
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	cpython := flag.String("cpython", "", "path to cpython source tree")
	out := flag.String("out", "", "output Go file")
	flag.Parse()
	if *cpython == "" || *out == "" {
		log.Fatal("both -cpython and -out required")
	}

	dbPath := filepath.Join(*cpython, "Modules", "unicodedata_db.h")
	src, err := os.ReadFile(dbPath) //nolint:gosec
	if err != nil {
		log.Fatal(err)
	}

	doc, err := parseDB(string(src))
	if err != nil {
		log.Fatal(err)
	}

	var buf bytes.Buffer
	if err := emit(&buf, doc); err != nil {
		log.Fatal(err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		_ = os.WriteFile(*out+".raw", buf.Bytes(), 0o644) //nolint:gosec
		log.Fatalf("gofmt: %v (raw dump at %s.raw)", err, *out)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil { //nolint:gosec
		log.Fatal(err)
	}
}

// db is the in-memory shape of the parts of unicodedata_db.h we
// care about. Each named array is a flat []uint32 (widening to fit
// the largest entry); the consumers cast back to the runtime type.
type db struct {
	version string
	shift   int
	decomp  int
	comp    int
	first   int
	last    int

	records        [][]uint32 // 6-tuples
	categoryNames  []string
	bidiNames      []string
	eawNames       []string
	decompPrefix   []string
	index1         []uint32
	index2         []uint32
	decompData     []uint32
	decompIndex1   []uint32
	decompIndex2   []uint32
	compIndex      []uint32
	compData       []uint32
	nfcFirst       []reindex
	nfcLast        []reindex
}

type reindex struct {
	start, count, index int
}

func parseDB(src string) (*db, error) {
	out := &db{}

	if m := regexp.MustCompile(`#define UNIDATA_VERSION "([^"]+)"`).FindStringSubmatch(src); m != nil {
		out.version = m[1]
	}
	if v, ok := defineInt(src, "SHIFT"); ok {
		out.shift = v
	}
	if v, ok := defineInt(src, "DECOMP_SHIFT"); ok {
		out.decomp = v
	}
	if v, ok := defineInt(src, "COMP_SHIFT"); ok {
		out.comp = v
	}
	if v, ok := defineInt(src, "TOTAL_FIRST"); ok {
		out.first = v
	}
	if v, ok := defineInt(src, "TOTAL_LAST"); ok {
		out.last = v
	}

	// _PyUnicode_Database_Records is a list of {a, b, c, d, e, f}
	// tuples; parse with the tuple-walker because regexp on the
	// braces is ambiguous against the outer braces.
	recBody, err := extractBlock(src, "_PyUnicode_Database_Records[] = {", "};")
	if err != nil {
		return nil, fmt.Errorf("records: %w", err)
	}
	out.records = parseTupleList(recBody, 6)

	// Name arrays.
	if out.categoryNames, err = extractStrings(src, "_PyUnicode_CategoryNames[] = {"); err != nil {
		return nil, fmt.Errorf("category names: %w", err)
	}
	if out.bidiNames, err = extractStrings(src, "_PyUnicode_BidirectionalNames[] = {"); err != nil {
		return nil, fmt.Errorf("bidirectional names: %w", err)
	}
	if out.eawNames, err = extractStrings(src, "_PyUnicode_EastAsianWidthNames[] = {"); err != nil {
		return nil, fmt.Errorf("east_asian_width names: %w", err)
	}
	if out.decompPrefix, err = extractStrings(src, "decomp_prefix[] = {"); err != nil {
		return nil, fmt.Errorf("decomp_prefix: %w", err)
	}

	// Flat integer arrays.
	for _, tab := range []struct {
		name string
		dst  *[]uint32
	}{
		{"index1[] = {", &out.index1},
		{"index2[] = {", &out.index2},
		{"decomp_data[] = {", &out.decompData},
		{"decomp_index1[] = {", &out.decompIndex1},
		{"decomp_index2[] = {", &out.decompIndex2},
		{"comp_index[] = {", &out.compIndex},
		// Leading space disambiguates from decomp_data[] = {.
		{" comp_data[] = {", &out.compData},
	} {
		body, err := extractBlock(src, tab.name, "};")
		if err != nil {
			return nil, fmt.Errorf("%s: %w", tab.name, err)
		}
		*tab.dst = parseInts(body)
	}

	// nfc_first / nfc_last are struct reindex tuples.
	if body, err := extractBlock(src, "nfc_first[] = {", "};"); err == nil {
		out.nfcFirst = parseReindex(body)
	} else {
		return nil, fmt.Errorf("nfc_first: %w", err)
	}
	if body, err := extractBlock(src, "nfc_last[] = {", "};"); err == nil {
		out.nfcLast = parseReindex(body)
	} else {
		return nil, fmt.Errorf("nfc_last: %w", err)
	}

	return out, nil
}

var defineRE = regexp.MustCompile(`(?m)^#define\s+([A-Z_]+)\s+(\d+)\s*$`)

func defineInt(src, name string) (int, bool) {
	for _, m := range defineRE.FindAllStringSubmatch(src, -1) {
		if m[1] == name {
			v, _ := strconv.Atoi(m[2])
			return v, true
		}
	}
	return 0, false
}

// extractBlock finds the substring between `start` and the next
// matching `};`, returning the inner text.
func extractBlock(src, start, end string) (string, error) {
	i := strings.Index(src, start)
	if i < 0 {
		return "", fmt.Errorf("not found: %s", start)
	}
	rest := src[i+len(start):]
	j := strings.Index(rest, end)
	if j < 0 {
		return "", fmt.Errorf("unterminated: %s", start)
	}
	return rest[:j], nil
}

// extractStrings parses a `static const char *name[] = { "a", "b", NULL };`
// block (or similar) into a slice of Go strings, dropping the
// trailing NULL sentinel if present.
func extractStrings(src, start string) ([]string, error) {
	body, err := extractBlock(src, start, "};")
	if err != nil {
		return nil, err
	}
	var out []string
	i := 0
	for i < len(body) {
		switch {
		case body[i] == '"':
			j := i + 1
			for j < len(body) && body[j] != '"' {
				if body[j] == '\\' {
					j++
				}
				j++
			}
			if j >= len(body) {
				return nil, fmt.Errorf("unterminated string at offset %d", i)
			}
			lit, err := strconv.Unquote(body[i : j+1])
			if err != nil {
				return nil, fmt.Errorf("unquote at %d: %w", i, err)
			}
			out = append(out, lit)
			i = j + 1
		case body[i] == 'N' && strings.HasPrefix(body[i:], "NULL"):
			i += 4
		default:
			i++
		}
	}
	return out, nil
}

// parseInts walks a comma-separated sequence of decimal / hex
// integers, ignoring whitespace and comments. Returns the flat
// []uint32.
func parseInts(body string) []uint32 {
	body = stripComments(body)
	var out []uint32
	i := 0
	for i < len(body) {
		c := body[i]
		switch {
		case c == ' ' || c == '\t' || c == '\n' || c == ',' || c == '\r':
			i++
		case c == '0' && i+1 < len(body) && (body[i+1] == 'x' || body[i+1] == 'X'):
			j := i + 2
			for j < len(body) && isHex(body[j]) {
				j++
			}
			n, _ := strconv.ParseUint(body[i+2:j], 16, 64)
			out = append(out, uint32(n))
			i = j
		case c >= '0' && c <= '9':
			j := i
			for j < len(body) && body[j] >= '0' && body[j] <= '9' {
				j++
			}
			n, _ := strconv.ParseUint(body[i:j], 10, 64)
			out = append(out, uint32(n))
			i = j
		default:
			i++
		}
	}
	return out
}

// parseTupleList walks a `{a, b, ...}, {...}, ...` sequence and
// returns one []uint32 per tuple. Tuples must be `arity` wide.
func parseTupleList(body string, arity int) [][]uint32 {
	body = stripComments(body)
	var out [][]uint32
	i := 0
	for i < len(body) {
		c := body[i]
		switch {
		case c == '{':
			j := strings.IndexByte(body[i:], '}')
			if j < 0 {
				return out
			}
			tup := parseInts(body[i+1 : i+j])
			if len(tup) != arity {
				log.Fatalf("tuple arity mismatch: got %d, want %d in %q", len(tup), arity, body[i:i+j+1])
			}
			out = append(out, tup)
			i += j + 1
		default:
			i++
		}
	}
	return out
}

// parseReindex walks a sequence of `{start, count, index}` triples.
func parseReindex(body string) []reindex {
	tuples := parseTupleList(body, 3)
	out := make([]reindex, len(tuples))
	for i, t := range tuples {
		out[i] = reindex{int(t[0]), int(t[1]), int(t[2])}
	}
	return out
}

func stripComments(s string) string {
	for {
		i := strings.Index(s, "/*")
		if i < 0 {
			return s
		}
		j := strings.Index(s[i:], "*/")
		if j < 0 {
			return s[:i]
		}
		s = s[:i] + s[i+j+2:]
	}
}

func isHex(c byte) bool {
	return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')
}

func emit(w *bytes.Buffer, d *db) error {
	fmt.Fprint(w, `// Code generated by Tools/unicodedata_go. DO NOT EDIT.
//
// Source: $CPYTHON/Modules/unicodedata_db.h
//
// CPython: Modules/unicodedata_db.h
// CPython: Tools/unicode/makeunicodedata.py

package unicodedata

`)
	fmt.Fprintf(w, "const unidataVersion = %q\n\n", d.version)
	fmt.Fprintf(w, "const recShift = %d\n", d.shift)
	fmt.Fprintf(w, "const decompShift = %d\n", d.decomp)
	fmt.Fprintf(w, "const compShift = %d\n", d.comp)
	fmt.Fprintf(w, "const totalFirst = %d\n", d.first)
	fmt.Fprintf(w, "const totalLast = %d\n\n", d.last)

	emitStrings(w, "categoryNames", d.categoryNames)
	emitStrings(w, "bidirectionalNames", d.bidiNames)
	emitStrings(w, "eastAsianWidthNames", d.eawNames)
	emitStrings(w, "decompPrefix", d.decompPrefix)

	// dbRecord 6-tuple: {category, combining, bidirectional,
	// mirrored, east_asian_width, normalization_quick_check}.
	fmt.Fprint(w, "type dbRecord struct{ Category, Combining, Bidirectional, Mirrored, EastAsianWidth, NormalizationQC uint8 }\n\n")
	fmt.Fprintf(w, "var dbRecords = [%d]dbRecord{\n", len(d.records))
	for _, r := range d.records {
		fmt.Fprintf(w, "{%d, %d, %d, %d, %d, %d},\n", r[0], r[1], r[2], r[3], r[4], r[5])
	}
	fmt.Fprint(w, "}\n\n")

	emitUint16(w, "index1", d.index1)
	emitUint16(w, "index2", d.index2)
	emitUint32(w, "decompData", d.decompData)
	emitUint8(w, "decompIndex1", d.decompIndex1)
	emitUint16(w, "decompIndex2", d.decompIndex2)
	emitUint16(w, "compIndex", d.compIndex)
	emitUint32(w, "compData", d.compData)

	fmt.Fprint(w, "type reindexEntry struct{ Start, Count, Index int }\n\n")
	emitReindex(w, "nfcFirst", d.nfcFirst)
	emitReindex(w, "nfcLast", d.nfcLast)

	return nil
}

func emitStrings(w *bytes.Buffer, name string, ss []string) {
	fmt.Fprintf(w, "var %s = []string{\n", name)
	for _, s := range ss {
		fmt.Fprintf(w, "%q,\n", s)
	}
	fmt.Fprint(w, "}\n\n")
}

func emitUint8(w *bytes.Buffer, name string, xs []uint32) {
	fmt.Fprintf(w, "var %s = [...]uint8{\n", name)
	for i, x := range xs {
		fmt.Fprintf(w, "%d,", x)
		if i%32 == 31 {
			fmt.Fprintln(w)
		}
	}
	fmt.Fprint(w, "\n}\n\n")
}

func emitUint16(w *bytes.Buffer, name string, xs []uint32) {
	fmt.Fprintf(w, "var %s = [...]uint16{\n", name)
	for i, x := range xs {
		fmt.Fprintf(w, "%d,", x)
		if i%32 == 31 {
			fmt.Fprintln(w)
		}
	}
	fmt.Fprint(w, "\n}\n\n")
}

func emitUint32(w *bytes.Buffer, name string, xs []uint32) {
	fmt.Fprintf(w, "var %s = [...]uint32{\n", name)
	for i, x := range xs {
		fmt.Fprintf(w, "%d,", x)
		if i%16 == 15 {
			fmt.Fprintln(w)
		}
	}
	fmt.Fprint(w, "\n}\n\n")
}

func emitReindex(w *bytes.Buffer, name string, rs []reindex) {
	fmt.Fprintf(w, "var %s = []reindexEntry{\n", name)
	for _, r := range rs {
		fmt.Fprintf(w, "{%d, %d, %d},\n", r.start, r.count, r.index)
	}
	fmt.Fprint(w, "}\n\n")
}
