"""go_generators_common — Go-emitting helpers and macro binding table.

Companion to generators_common.py. Where generators_common.py
holds the C-side helpers used by every CPython emitter, this
module holds the Go-side equivalents that the gopy-targeted
emitters (Phase 2+ of spec 1714) will share:

  * write_go_header(out, generator, sources) — the
    "Code generated ... DO NOT EDIT." preamble plus package decl.
  * MACRO_BINDINGS — a dict mapping every constant DSL macro from
    Python/bytecodes.c to its gopy Go spelling. Values are
    callables (args -> Go text) so they handle 0-, 1-, and
    2-argument macros uniformly.
  * render_macro(name, args) — apply a binding by name.

The binding rows mirror what hand-written code in vm/eval_*.go
already does. Open rows (no gopy equivalent yet) live in
SUBSET.md so Phase 8 (body translation) knows what is in scope.

Spec: website/docs/specs/1700/1714_bytecodes_dsl_codegen.md
"""

from __future__ import annotations

from typing import Callable, Iterable, TextIO


# ----------------------------------------------------------------------
# File header
# ----------------------------------------------------------------------


def write_go_header(
    out: TextIO,
    generator: str,
    sources: Iterable[str],
    package: str,
    build_tag: str | None = None,
) -> None:
    """Emit the standard generated-file preamble for a Go output.

    Matches the upstream cases_generator header shape: a one-line
    "Code generated by Tools/cases_generator/<generator>" notice
    followed by "DO NOT EDIT." (recognized by Go tools via the
    `^// Code generated .* DO NOT EDIT\\.$` regex per cmd/go docs).
    """
    if build_tag is not None:
        out.write(f"//go:build {build_tag}\n\n")
    out.write(f"// Code generated by Tools/cases_generator/{generator}. DO NOT EDIT.\n")
    out.write("// Source:\n")
    for s in sources:
        out.write(f"//   {s}\n")
    out.write(f"// Regenerate via: go run ./Tools/regen-cases --target=go\n")
    out.write("\n")
    out.write(f"package {package}\n\n")


# ----------------------------------------------------------------------
# Macro binding table
# ----------------------------------------------------------------------
#
# Bindings are callables so callers do not have to special-case
# arity. Each callable takes a tuple of stringified Go expressions
# (already lowered by the body translator) and returns one Go
# expression or statement.
#
# CPython callers spell macros as `MACRO(a, b)`; we lower them to
# render_macro("MACRO", ("a", "b")) which dispatches here.
#
# Status legend embedded in comments:
#   READY    — binding is final, hand-written gopy code uses this
#              exact spelling today.
#   STAGED   — spelling is provisional; will be tightened in Phase 5
#              once op<NAME> signatures freeze.
#   GC_NOOP  — Go GC handles the lifecycle; bind to the empty
#              statement so the emitted Go has no leftover stub.

_Binding = Callable[[tuple[str, ...]], str]


def _stack_peek(args: tuple[str, ...]) -> str:
    (n,) = args
    return f"e.peek({n})"


def _stack_poke(args: tuple[str, ...]) -> str:
    n, v = args
    return f"e.poke({n}, {v})"


def _stack_grow(args: tuple[str, ...]) -> str:
    (n,) = args
    return f"e.f.StackTop += {n}"


def _stack_shrink(args: tuple[str, ...]) -> str:
    (n,) = args
    return f"e.f.StackTop -= {n}"


def _top(_args: tuple[str, ...]) -> str:
    return "e.peek(0)"


def _second(_args: tuple[str, ...]) -> str:
    return "e.peek(1)"


def _getlocal(args: tuple[str, ...]) -> str:
    (i,) = args
    return f"e.localAt({i})"


def _setlocal(args: tuple[str, ...]) -> str:
    i, v = args
    return f"e.setLocal({i}, {v})"


def _jumpby(args: tuple[str, ...]) -> str:
    (n,) = args
    return f"e.jumpBy({n})"


def _jumpto(args: tuple[str, ...]) -> str:
    (t,) = args
    return f"e.f.InstrPtr = {t}"


def _deopt_if(args: tuple[str, ...]) -> str:
    cond, parent = args
    return f"if {cond} {{ return e.deoptTo({parent}) }}"


def _error_if(args: tuple[str, ...]) -> str:
    cond, label = args
    # The body translator lowers `label` to a Go-side sentinel.
    # For Phase 1 we keep the label name verbatim as a `goto`
    # target; Phase 8 will rewrite jumps to structured returns.
    return f"if {cond} {{ goto {label} }}"


def _stackref_from_new(args: tuple[str, ...]) -> str:
    (o,) = args
    return f"stackref.FromObjectNew({o})"


def _stackref_borrow(args: tuple[str, ...]) -> str:
    (r,) = args
    return f"{r}.AsObject()"


def _stackref_close(args: tuple[str, ...]) -> str:
    # gopy is GC'd; closing a stackref is a no-op. We still emit a
    # blank statement so the body translator's statement counter
    # stays in sync.
    return "_ = 0 // PyStackRef_CLOSE: GC no-op"


def _refcount_noop(_args: tuple[str, ...]) -> str:
    return "_ = 0 // Py_INCREF/DECREF: GC no-op"


def _instruction_size(_args: tuple[str, ...]) -> str:
    return "2"


def _next_op_arg(_args: tuple[str, ...]) -> str:
    return "e.fetch()"


MACRO_BINDINGS: dict[str, _Binding] = {
    # Stack
    "PEEK": _stack_peek,           # READY
    "POKE": _stack_poke,           # READY
    "STACK_GROW": _stack_grow,     # READY
    "STACK_SHRINK": _stack_shrink, # READY
    "TOP": _top,                   # READY
    "SECOND": _second,             # READY
    # Fast locals
    "GETLOCAL": _getlocal,         # READY
    "SETLOCAL": _setlocal,         # READY
    # Branching
    "JUMPBY": _jumpby,             # READY
    "JUMPTO": _jumpto,             # READY
    # Specializer
    "DEOPT_IF": _deopt_if,         # STAGED
    "ERROR_IF": _error_if,         # STAGED
    # Stackref helpers
    "PyStackRef_FromPyObjectNew": _stackref_from_new,    # READY
    "PyStackRef_AsPyObjectBorrow": _stackref_borrow,     # READY
    "PyStackRef_CLOSE": _stackref_close,                 # GC_NOOP
    # Refcount: Go GC handles it
    "Py_INCREF": _refcount_noop,   # GC_NOOP
    "Py_DECREF": _refcount_noop,   # GC_NOOP
    "Py_XDECREF": _refcount_noop,  # GC_NOOP
    # Instruction layout
    "INSTRUCTION_SIZE": _instruction_size,  # READY
    "NEXTOPARG": _next_op_arg,              # READY
}


def render_macro(name: str, args: tuple[str, ...]) -> str:
    """Render macro `name` with the given pre-lowered argument
    expressions, returning the matching Go text.

    Raises KeyError if the macro is not yet bound. Phase 8 expands
    this table as the body translator matures; until then,
    SUBSET.md lists every macro that the translator must not see.
    """
    try:
        binding = MACRO_BINDINGS[name]
    except KeyError:
        raise KeyError(
            f"go_generators_common: macro {name!r} has no Go binding yet. "
            f"Add it to MACRO_BINDINGS or document it in SUBSET.md."
        )
    return binding(args)
