"""Generate the gopy abstract-interpreter spec file.

Go-emitting sibling of upstream optimizer_generator.py. Where that
script emits Python/optimizer_cases.c.h (one big switch of abstract-
interpreter C bodies #included by Python/optimizer_analysis.c), this
one emits optimizer/optimizer_cases_gen.go: a doc-only Go file
carrying one Tier-2-viable uop body per block, captured as a Go //
comment so the file stays valid Go.

The gopy abstract interpreter is currently hand-written in
optimizer/symbols.go + optimizer/analysis.go. This generated file is
the porting spec: when the dispatch-by-uop migration lands (spec 1714
phase 7+), the bodies translate one-by-one and analysis.go shrinks
to scaffolding.

The classification + body capture is reused verbatim by re-importing
upstream's optimizer_generator helpers: SKIPS, declare_variables,
emit_default (via write_uop), and write_uop itself. The only Go-
specific work is:

  1. Iterating in sorted order so the generated file is stable across
     runs.
  2. Wrapping the captured C body as a // comment block, line by line.
  3. Stamping the gopy banner + a single `package optimizer` so the
     file is valid Go.

Spec: website/docs/specs/1700/1714_bytecodes_dsl_codegen.md
"""

from __future__ import annotations

import argparse
from io import StringIO
from typing import TextIO

from analyzer import Analysis, Uop, analyze_files
from cwriter import CWriter
from generators_common import DEFAULT_INPUT, ROOT
from stack import Stack
from optimizer_generator import (
    SKIPS,
    declare_variables,
    write_uop,
)


DEFAULT_OUTPUT = "optimizer/optimizer_cases_gen.go"
DEFAULT_ABSTRACT_INPUT = (
    ROOT / "Python/optimizer_bytecodes.c"
).absolute().as_posix()


def _short_source(path: str) -> str:
    """Reduce a generator input path to a CPython tree reference so the
    embedded source line stays reproducible regardless of checkout
    location. Strips the leading inputs/ shim if present so the
    embedded path reads as `Python/optimizer_bytecodes.c` rather than
    `inputs/Python/optimizer_bytecodes.c`."""
    marker = "Tools/cases_generator/inputs/"
    if marker in path:
        return path.split(marker, 1)[1]
    if path.startswith("inputs/"):
        return path[len("inputs/"):]
    return path


def _write_header(out: TextIO, filenames: list[str]) -> None:
    """Stamp the generator banner. Matches the Phase L tier2 emitter
    so the gopy lint / drift checkers do not need a special case."""
    out.write(
        "// This file is generated by Tools/cases_generator/gopy_optimizer_generator.py\n"
    )
    out.write("// from:\n")
    out.write(f"//   {', '.join(_short_source(f) for f in filenames)}\n")
    out.write("// Do not edit!\n")
    out.write("// Code generated by Tools/cases_generator; DO NOT EDIT.\n\n")
    out.write("package optimizer\n\n")


_DOC = """// Per-uop abstract-interpreter bodies. One // comment block per
// Tier-2-viable uop, carrying the C body that Python/optimizer_bytecodes.c
// (overlaid on Python/bytecodes.c) lowers each uop to. The hand-
// written symbolic interpreter in symbols.go + analysis.go must
// match these bodies; when dispatch-by-uop lands (spec 1714 phase
// 7+), the bodies translate to Go one-by-one and this file gains
// real methods on *AbstractCtx.
//
// CPython: Python/optimizer_cases.c.h (per-uop case bodies)
"""


def is_viable_abstract_uop(uop: Uop) -> bool:
    """Mirror generate_abstract_interpreter's filter chain:
    not in SKIPS, not tier-1-only, not a replica, not a super-inst,
    and viable (no why_not_viable diagnostic)."""
    if uop.name in SKIPS:
        return False
    if uop.properties.tier == 1:
        return False
    if uop.replicates:
        return False
    if uop.is_super():
        return False
    if not uop.is_viable():
        return False
    return True


def render_uop_body(abstract: Analysis, uop: Uop) -> str:
    """Capture one uop's abstract-interp C body via the upstream
    pipeline. Mirrors optimizer_generator.generate_abstract_interpreter
    per-uop: open `case <UOP>: {`, declare locals, dispatch tokens
    through OptimizerEmitter (when overridden) or emit_default (when
    not), then close with `break;` + `}`."""
    override = abstract.uops.get(uop.name)
    buf = StringIO()
    out = CWriter(buf, 2, False)
    out.emit(f"case {uop.name}: {{\n")
    if override is not None:
        declare_variables(override, out, False)
    else:
        declare_variables(uop, out, True)
    stack = Stack(extract_bits=False, cast_type="JitOptSymbol *")
    write_uop(override, uop, out, stack, False, override is None)
    out.start_line()
    out.emit("break;\n")
    out.emit("}\n")
    return buf.getvalue()


def comment_prefix(body: str) -> str:
    """Turn a captured C-flavored body into a Go // comment block.
    Empty lines become bare `//`; content lines become `// <text>`.
    Trailing empty comments are trimmed so the block ends on a
    content line (followed by a newline)."""
    if not body:
        return ""
    lines = body.split("\n")
    out: list[str] = []
    for line in lines:
        stripped = line.rstrip("\r ")
        if stripped == "":
            out.append("//")
        else:
            out.append("// " + stripped)
    while out and out[-1] == "//":
        out.pop()
    return "\n".join(out) + "\n"


def generate_abstract_interpreter(
    filenames: list[str],
    abstract: Analysis,
    base: Analysis,
    outfile: TextIO,
) -> None:
    """Write the per-uop abstract-interp spec file. Iterates base.uops
    in sorted order, filters via is_viable_abstract_uop, and dumps
    one // comment block per surviving uop."""
    _write_header(outfile, filenames)
    outfile.write(_DOC)
    base_uop_names = {u.name for u in base.uops.values()}
    for abstract_uop_name in abstract.uops:
        assert (
            abstract_uop_name in base_uop_names
        ), f"All abstract uops should override base uops, but {abstract_uop_name} is not."
    abstract_names = set(abstract.uops)
    for name in sorted(base.uops):
        uop = base.uops[name]
        if not is_viable_abstract_uop(uop):
            continue
        body = render_uop_body(abstract, uop)
        tag = (
            "override from optimizer_bytecodes.c"
            if name in abstract_names
            else "default body"
        )
        outfile.write(f"\n// {uop.name}: {tag}.\n")
        outfile.write(comment_prefix(body))


arg_parser = argparse.ArgumentParser(
    description="Generate optimizer/optimizer_cases_gen.go from CPython DSL inputs.",
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
)

arg_parser.add_argument(
    "-o", "--output", type=str, help="Generated Go file", default=DEFAULT_OUTPUT
)

arg_parser.add_argument(
    "input",
    nargs=argparse.REMAINDER,
    help="base file (bytecodes.c) followed by abstract file (optimizer_bytecodes.c)",
)


if __name__ == "__main__":
    args = arg_parser.parse_args()
    if not args.input:
        args.input = [str(DEFAULT_INPUT), DEFAULT_ABSTRACT_INPUT]
    assert len(args.input) == 2, "Need a base file and an abstract file."
    base = analyze_files([args.input[0]])
    abstract = analyze_files([args.input[1]])
    with open(args.output, "w") as outfile:
        generate_abstract_interpreter(args.input, abstract, base, outfile)
