package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeTemp(t *testing.T, name, body string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatalf("write %s: %v", p, err)
	}
	return p
}

func TestStripHeader(t *testing.T) {
	cases := []struct {
		name    string
		body    string
		comment string
		want    string
	}{
		{
			name: "c_header_present",
			body: "// This file is generated by Tools/x.py\n" +
				"// from:\n" +
				"//   Python/bytecodes.c\n" +
				"// Do not edit!\n" +
				"int main(void) { return 0; }\n",
			comment: "//",
			want:    "int main(void) { return 0; }\n",
		},
		{
			name: "python_header_present",
			body: "# This file is generated by Tools/x.py\n" +
				"# Do not edit!\n" +
				"_specialized_opmap = {}\n",
			comment: "#",
			want:    "_specialized_opmap = {}\n",
		},
		{
			name:    "no_header_c",
			body:    "#if !Py_TAIL_CALL_INTERP\nstatic void *opcode_targets[256] = {};\n#endif\n",
			comment: "//",
			want:    "#if !Py_TAIL_CALL_INTERP\nstatic void *opcode_targets[256] = {};\n#endif\n",
		},
		{
			name: "header_beyond_scan_treated_as_no_header",
			body: strings.Repeat("// filler\n", headerScanLines+2) +
				"// Do not edit!\n" +
				"body\n",
			comment: "//",
			want: strings.Repeat("// filler\n", headerScanLines+2) +
				"// Do not edit!\n" +
				"body\n",
		},
		{
			name:    "marker_on_last_line_no_trailing_newline",
			body:    "// hdr\n// Do not edit!",
			comment: "//",
			want:    "",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			p := writeTemp(t, "in.txt", tc.body)
			got, err := stripHeader(p, tc.comment)
			if err != nil {
				t.Fatalf("stripHeader: %v", err)
			}
			if string(got) != tc.want {
				t.Errorf("stripHeader mismatch\n got: %q\nwant: %q", got, tc.want)
			}
		})
	}
}

func TestFilesEqual(t *testing.T) {
	a := writeTemp(t, "a", "hello\n")
	b := writeTemp(t, "b", "hello\n")
	c := writeTemp(t, "c", "world\n")
	if !filesEqual(a, b) {
		t.Error("filesEqual(a,b) = false; want true")
	}
	if filesEqual(a, c) {
		t.Error("filesEqual(a,c) = true; want false")
	}
	if filesEqual(a, filepath.Join(t.TempDir(), "missing")) {
		t.Error("filesEqual against missing = true; want false")
	}
}

func TestBodiesEqual(t *testing.T) {
	a := writeTemp(t, "a.h",
		"// gen ROOT-A\n// from x\n// y\n// Do not edit!\nBODY\n")
	b := writeTemp(t, "b.h",
		"// gen ROOT-B\n// from xx\n// yy\n// Do not edit!\nBODY\n")
	eq, err := bodiesEqual(a, b, "//")
	if err != nil {
		t.Fatalf("bodiesEqual: %v", err)
	}
	if !eq {
		t.Error("bodies with differing headers but same body must compare equal")
	}

	c := writeTemp(t, "c.h",
		"// gen ROOT-A\n// from x\n// y\n// Do not edit!\nDIFFERENT\n")
	eq, err = bodiesEqual(a, c, "//")
	if err != nil {
		t.Fatalf("bodiesEqual: %v", err)
	}
	if eq {
		t.Error("bodies with same header but different body must compare unequal")
	}
}

func TestCheckUpstreamSmoke(t *testing.T) {
	cpy := os.Getenv("CPYTHON_ROOT")
	if cpy == "" {
		home, _ := os.UserHomeDir()
		cpy = filepath.Join(home, "cpython-314")
	}
	if _, err := os.Stat(cpy); err != nil {
		t.Skipf("CPYTHON_ROOT %s unavailable: %v", cpy, err)
	}
	if _, err := os.Stat("/usr/bin/python3"); err != nil {
		if _, err2 := os.Stat("/usr/local/bin/python3"); err2 != nil {
			if _, err3 := os.Stat("/opt/homebrew/bin/python3"); err3 != nil {
				t.Skip("no python3 on PATH")
			}
		}
	}
	root, err := repoRoot()
	if err != nil {
		t.Fatalf("repoRoot: %v", err)
	}
	opts := options{
		repoRoot:      root,
		cpythonRoot:   cpy,
		outDir:        t.TempDir(),
		python:        defaultPython(),
		checkUpstream: true,
	}
	if err := emitUpstream(opts); err != nil {
		t.Fatalf("emitUpstream: %v", err)
	}
	if err := checkUpstream(opts); err != nil {
		t.Fatalf("checkUpstream: %v", err)
	}
}
