// Trace projection. Walks the live Tier-1 bytecode of a Code starting
// at instr and produces a linear sequence of uops. Branches are
// folded by guard substitution (POP_JUMP_IF_FALSE becomes
// _GUARD_IS_TRUE_POP, etc.) so the trace is straight-line; PUSH_FRAME
// inlines the callee up to TraceStackSize deep. Loops close with a
// _JUMP_TO_TOP back to the entry; everything else falls off the end
// with _EXIT_TRACE.
//
// The projection mirrors CPython opcode for opcode but omits the JIT
// path entirely. Per-opcode metadata that would normally come from
// the generated _PyOpcode_macro_expansion table lives here in a
// trimmed handcrafted version; the full table is generated by
// uops_gen in a follow-up pass and will replace macroExpansion when
// available.
//
// CPython: Python/optimizer.c:553-987 translate_bytecode_to_trace

package optimizer

import (
	"unsafe"

	"github.com/tamnd/gopy/compile"
	"github.com/tamnd/gopy/objects"
	"github.com/tamnd/gopy/specialize"
)

// ConfidenceRange is the starting branch-confidence value. Each
// branch instruction divides confidence by how heavily one side has
// been favored; once the running value drops below ConfidenceCutoff
// the projection bails to keep cold paths out of traces.
//
// CPython: Python/optimizer.c:466-467
const (
	ConfidenceRange  = 1000
	ConfidenceCutoff = 333
)

// MaxUopPerExpansion bounds the per-opcode uop fan-out. Matches
// CPython's macro-expansion limit so handcrafted entries stay sized
// the same as generated ones.
//
// CPython: Include/internal/pycore_opcode_metadata.h:1322
// MAX_UOP_PER_EXPANSION
const MaxUopPerExpansion = 10

// MacroOparg encodes how the projector pulls oparg/operand for one
// uop slot. The values match CPython's OPARG_* constants byte for
// byte; #430 will fold them into the generated table.
//
// CPython: Tools/cases_generator/analyzer.py CacheEffect / OpargSize
type MacroOparg uint8

const (
	OpargSimple           MacroOparg = 0
	OpargCache1           MacroOparg = 1
	OpargCache2           MacroOparg = 2
	OpargCache4           MacroOparg = 4
	OpargTop              MacroOparg = 5
	OpargBottom           MacroOparg = 6
	OpargSaveReturnOffset MacroOparg = 7
	OpargReplaced         MacroOparg = 8
	Operand1_1            MacroOparg = 9
	Operand1_2            MacroOparg = 10
	Operand1_4            MacroOparg = 11
)

// MacroUop is one slot in a Tier-1 opcode's uop expansion. Size picks
// where the operand comes from; Offset is the cache slot the operand
// reads from (in codeunits past the opcode pair).
//
// CPython: Include/internal/pycore_opcode_metadata.h:1325
type MacroUop struct {
	Uop    uint16
	Size   MacroOparg
	Offset uint8
}

// branchToGuard maps the four POP_JUMP_IF_* opcodes to the guard uop
// the projector substitutes. The second index picks the "jump
// likely" arm; when the runtime histogram says the branch usually
// falls through we emit the falls-through guard, and vice versa.
//
// CPython: Python/optimizer.c:453-463 BRANCH_TO_GUARD
var branchToGuard = [4][2]uint16{
	{UopGuardIsTruePop, UopGuardIsFalsePop},   // POP_JUMP_IF_FALSE
	{UopGuardIsFalsePop, UopGuardIsTruePop},   // POP_JUMP_IF_TRUE
	{UopGuardIsNotNonePop, UopGuardIsNonePop}, // POP_JUMP_IF_NONE
	{UopGuardIsNonePop, UopGuardIsNotNonePop}, // POP_JUMP_IF_NOT_NONE
}

// macroExpansion is the per-opcode uop expansion the projector reads
// in the default branch. Coverage is intentionally narrow: the few
// unspecialized opcodes that the v0.12 gate fixtures exercise. Every
// remaining unspecialized opcode falls back to the identity expansion
// in lookupMacro because UopXxx == compile.OPCODE for those slots.
// The generated table from #430 will supersede both paths.
var macroExpansion = map[compile.Opcode][]MacroUop{
	compile.BINARY_OP_ADD_INT: {
		{Uop: UopGuardTosInt, Size: OpargSimple, Offset: 0},
		{Uop: UopGuardNosInt, Size: OpargSimple, Offset: 0},
		{Uop: UopBinaryOpAddInt, Size: OpargSimple, Offset: 5},
	},
	compile.BINARY_OP_SUBTRACT_INT: {
		{Uop: UopGuardTosInt, Size: OpargSimple, Offset: 0},
		{Uop: UopGuardNosInt, Size: OpargSimple, Offset: 0},
		{Uop: UopBinaryOpSubtractInt, Size: OpargSimple, Offset: 5},
	},
}

// lookupMacro returns the uop expansion for op. If the opcode has no
// explicit entry but its UopXxx alias equals the Tier-1 opcode value
// we synthesize an identity expansion; otherwise the projector treats
// the opcode as unsupported and bails.
func lookupMacro(op compile.Opcode) ([]MacroUop, bool) {
	if exp, ok := macroExpansion[op]; ok {
		return exp, true
	}
	if name, ok := UopNames[uint16(op)]; ok && name != "" {
		return []MacroUop{{Uop: uint16(op), Size: OpargSimple, Offset: 0}}, true
	}
	return nil, false
}

// addToTrace appends one uop row in the Tier-1-target format the
// dispatcher and disassembler expect.
//
// CPython: Python/optimizer.c:477-495 add_to_trace
func addToTrace(trace []UOPInstruction, length int, opcode, oparg uint16, operand uint64, target uint32) int {
	trace[length].SetOpcode(opcode)
	trace[length].SetFormat(UOPFormatTarget)
	trace[length].Target = target
	trace[length].Oparg = oparg
	trace[length].Operand0 = operand
	tier2Log("project_add", "idx=%d uop=%s oparg=%d operand0=%d target=%d",
		length, tier2UopName(opcode), oparg, operand, target)
	return length + 1
}

// traceFrame mirrors the per-frame slot the trace_stack[] in CPython
// uses while inlining PUSH_FRAME chains.
//
// CPython: Python/optimizer.c:571-575 trace_stack
type traceFrame struct {
	code  *objects.Code
	instr int
}

// readU16, readU32, readU64 pull cache words out of the bytecode
// stream. CPython packs caches as raw _Py_CODEUNIT slots after the
// opcode/oparg pair; the byte layout is little-endian.
func readU16(code *objects.Code, instr, off int) uint64 {
	base := (instr + off) * 2
	return uint64(code.Code[base]) | uint64(code.Code[base+1])<<8
}

func readU32(code *objects.Code, instr, off int) uint64 {
	return readU16(code, instr, off) | readU16(code, instr, off+1)<<16
}

func readU64(code *objects.Code, instr, off int) uint64 {
	return readU32(code, instr, off) | readU32(code, instr, off+2)<<32
}

// hasNoSaveIP reports whether op is one of the few opcodes that skip
// the leading _SET_IP guard in their expansion. The set is small;
// gopy hardcodes it here while waiting for the generated metadata
// flag table.
//
// CPython: Include/internal/pycore_opcode_metadata.h:1058
// OPCODE_HAS_NO_SAVE_IP
func hasNoSaveIP(op compile.Opcode) bool {
	switch op {
	case compile.LOAD_FAST, compile.LOAD_FAST_BORROW,
		compile.LOAD_FAST_LOAD_FAST, compile.LOAD_FAST_BORROW_LOAD_FAST_BORROW,
		compile.LOAD_CONST, compile.LOAD_CONST_IMMORTAL, compile.LOAD_CONST_MORTAL,
		compile.LOAD_SMALL_INT, compile.STORE_FAST, compile.STORE_FAST_LOAD_FAST,
		compile.STORE_FAST_STORE_FAST, compile.POP_TOP, compile.NOP, compile.COPY,
		compile.SWAP, compile.PUSH_NULL, compile.NOT_TAKEN:
		return true
	}
	return false
}

// hasExit and hasError approximate the OPCODE_HAS_EXIT /
// OPCODE_HAS_ERROR metadata flags. The conservative defaults err on
// the side of reserving extra trace slots (a wasted _EXIT_TRACE byte
// is harmless; missing one corrupts the trace).
//
// CPython: Include/internal/pycore_opcode_metadata.h:1052-1057
func hasExit(op compile.Opcode) bool {
	parent := specialize.Deopt(op)
	return parent != op
}

func hasError(op compile.Opcode) bool {
	switch op {
	case compile.LOAD_FAST, compile.LOAD_FAST_BORROW,
		compile.LOAD_CONST, compile.LOAD_CONST_IMMORTAL, compile.LOAD_CONST_MORTAL,
		compile.LOAD_SMALL_INT, compile.STORE_FAST, compile.POP_TOP,
		compile.NOP, compile.COPY, compile.SWAP, compile.PUSH_NULL,
		compile.NOT_TAKEN, compile.JUMP_FORWARD, compile.JUMP_BACKWARD_NO_INTERRUPT:
		return false
	}
	return true
}

// TranslateBytecodeToTrace projects the live Tier-1 bytecode of code
// starting at codeunit offset instr into the uop buffer trace. On
// success it returns the trace length (>0); on a failure that should
// retire the warmup attempt without an error it returns 0; on a hard
// error it returns -1. The dependencies bloom is stamped with every
// Code object the trace inlines through PUSH_FRAME (gopy currently
// only stamps the entry code; PUSH_FRAME inlining bails).
//
// CPython: Python/optimizer.c:553-987 translate_bytecode_to_trace
func TranslateBytecodeToTrace(
	code *objects.Code,
	instr int,
	trace []UOPInstruction,
	bufferSize int,
	dependencies *BloomFilter,
	progressNeeded bool,
) int {
	first := true
	initialCode := code
	dependencies.Add(unsafe.Pointer(initialCode))
	initialInstr := instr
	traceLength := 0
	maxLength := bufferSize - 2
	stack := [TraceStackSize]traceFrame{}
	stackDepth := 0
	confidence := ConfidenceRange
	jumpSeen := false

	traceLength = addToTrace(trace, traceLength,
		UopStartExecutor, 0, uint64(uintptr(unsafe.Pointer(&code.Code[instr*2]))), uint32(instr))
	traceLength = addToTrace(trace, traceLength, UopMakeWarm, 0, 0, 0)
	target := uint32(0)

	for {
		target = uint32(instr)
		maxLength--

		opcode := compile.Opcode(code.Code[instr*2])
		oparg := uint16(code.Code[instr*2+1])

		if !first && instr == initialInstr {
			if traceLength+4 > maxLength {
				goto done
			}
			traceLength = addToTrace(trace, traceLength, UopJumpToTop, 0, 0, 0)
			goto done
		}

		if opcode == compile.EXTENDED_ARG {
			instr++
			opcode = compile.Opcode(code.Code[instr*2])
			oparg = (oparg << 8) | uint16(code.Code[instr*2+1])
			if opcode == compile.EXTENDED_ARG {
				goto done
			}
		}
		if opcode == compile.ENTER_EXECUTOR {
			goto done
		}
		if traceLength+2 > maxLength {
			goto done
		}
		traceLength = addToTrace(trace, traceLength, UopCheckValidity, 0, 0, target)
		if !hasNoSaveIP(opcode) {
			if traceLength+2 > maxLength {
				goto done
			}
			traceLength = addToTrace(trace, traceLength, UopSetIp, 0,
				uint64(uintptr(unsafe.Pointer(&code.Code[instr*2]))), target)
		}

		if first && progressNeeded {
			if hasExit(opcode) || specialize.Deopt(opcode) != opcode {
				opcode = specialize.Deopt(opcode)
			}
		}

		if hasExit(opcode) {
			if traceLength+2 > maxLength {
				goto done
			}
			maxLength--
		}
		if hasError(opcode) {
			if traceLength+2 > maxLength {
				goto done
			}
			maxLength--
		}

		switch opcode {
		case compile.POP_JUMP_IF_NONE, compile.POP_JUMP_IF_NOT_NONE,
			compile.POP_JUMP_IF_FALSE, compile.POP_JUMP_IF_TRUE:
			if traceLength+4 > maxLength {
				goto done
			}
			counter := readU16(code, instr, 1)
			bitcount := popcount32(uint32(counter))
			jumpLikely := bitcount > 8
			if jumpLikely {
				confidence = confidence * bitcount / 16
			} else {
				confidence = confidence * (16 - bitcount) / 16
			}
			arm := 0
			if jumpLikely {
				arm = 1
			}
			uopcode := branchToGuard[opcode-compile.POP_JUMP_IF_FALSE][arm]
			if confidence < ConfidenceCutoff {
				goto done
			}
			nextInstr := instr + 1 + specialize.CacheCount(specialize.Deopt(opcode))
			targetInstr := nextInstr + int(oparg)
			if jumpLikely {
				instr = targetInstr
				traceLength = addToTrace(trace, traceLength, uopcode, 0, 0, uint32(nextInstr))
				goto top
			}
			traceLength = addToTrace(trace, traceLength, uopcode, 0, 0, uint32(targetInstr))

		case compile.JUMP_BACKWARD, compile.JUMP_BACKWARD_JIT:
			traceLength = addToTrace(trace, traceLength, UopCheckPeriodic, 0, 0, target)
			fallthrough
		case compile.JUMP_BACKWARD_NO_INTERRUPT:
			instr += 1 + specialize.CacheCount(specialize.Deopt(opcode)) - int(oparg)
			if jumpSeen {
				goto done
			}
			jumpSeen = true
			goto top

		case compile.JUMP_FORWARD:
			instr += int(oparg)

		case compile.RESUME:
			traceLength = addToTrace(trace, traceLength, UopTier2ResumeCheck, 0, 0, target)

		default:
			expansion, ok := lookupMacro(opcode)
			if !ok {
				goto done
			}
			nuops := len(expansion)
			if traceLength+nuops+1+3 > maxLength {
				goto done
			}
			lastUop := expansion[nuops-1].Uop
			if lastUop == UopReturnValue || lastUop == UopReturnGenerator || lastUop == UopYieldValue {
				if stackDepth == 0 {
					return 0
				}
			}
			origOparg := oparg
			for i := 0; i < nuops; i++ {
				oparg = origOparg
				uop := expansion[i].Uop
				operand := uint64(0)
				offset := int(expansion[i].Offset) + 1
				switch expansion[i].Size {
				case OpargSimple:
				case OpargCache1:
					operand = readU16(code, instr, offset)
				case OpargCache2:
					operand = readU32(code, instr, offset)
				case OpargCache4:
					operand = readU64(code, instr, offset)
				case OpargTop:
					oparg = origOparg >> 4
				case OpargBottom:
					oparg = origOparg & 0xF
				case OpargSaveReturnOffset:
					oparg = uint16(offset)
				case OpargReplaced:
					uop = uopReplacement(uop)
					if uop == 0 {
						goto done
					}
				case Operand1_1:
					operand = readU16(code, instr, offset)
					trace[traceLength-1].Operand1 = operand
					continue
				case Operand1_2:
					operand = readU32(code, instr, offset)
					trace[traceLength-1].Operand1 = operand
					continue
				case Operand1_4:
					operand = readU64(code, instr, offset)
					trace[traceLength-1].Operand1 = operand
					continue
				}

				if uop == UopReturnValue || uop == UopReturnGenerator || uop == UopYieldValue {
					if stackDepth <= 0 || stackDepth > TraceStackSize {
						return 0
					}
					stackDepth--
					//nolint:gosec // bounds-checked above; gosec G602 false-positive on array index
					popped := stack[stackDepth]
					code = popped.code
					instr = popped.instr
					operand = uint64(uintptr(unsafe.Pointer(code))) | 1
					traceLength = addToTrace(trace, traceLength, uop, oparg, operand, target)
					goto top
				}

				if uop == UopPushFrame {
					traceLength = addToTrace(trace, traceLength, uop, oparg, 0, target)
					traceLength = addToTrace(trace, traceLength, UopExitTrace, 0, 0, 0)
					goto done
				}

				if uop == UopBinaryOpInplaceAddUnicode {
					nextInstr := instr + 1 + specialize.CacheCount(specialize.Deopt(opcode))
					operand = uint64(code.Code[nextInstr*2+1])
					instr++
				}

				traceLength = addToTrace(trace, traceLength, uop, oparg, operand, target)
			}
		}

		instr++
		instr += specialize.CacheCount(specialize.Deopt(opcode))

		if opcode == compile.CALL_LIST_APPEND {
			instr++
		}
	top:
		first = false
	}

done:
	for stackDepth > 0 {
		stackDepth--
		code = stack[stackDepth].code
	}
	if code != initialCode {
		return -1
	}
	if first {
		return 0
	}
	if !trace[traceLength-1].IsTerminator() {
		traceLength = addToTrace(trace, traceLength, UopExitTrace, 0, 0, target)
	}
	return traceLength
}

// uopReplacement implements the OPARG_REPLACED rewrite for FOR_ITER /
// ITER_JUMP variants. The handful of replacements live here while the
// generated _PyUOp_Replacements table is pending.
//
// CPython: Python/optimizer.c:436-443 _PyUOp_Replacements
func uopReplacement(uop uint16) uint16 {
	switch uop {
	case UopIterJumpRange:
		return UopGuardNotExhaustedRange
	case UopIterJumpList:
		return UopGuardNotExhaustedList
	case UopIterJumpTuple:
		return UopGuardNotExhaustedTuple
	case UopForIter:
		return UopForIterTierTwo
	case UopIterNextList:
		return UopIterNextListTierTwo
	}
	return 0
}

// popcount32 counts the set bits in v. The branch-confidence math
// uses the popcount of the per-branch counter to pick between guard
// arms.
func popcount32(v uint32) int {
	count := 0
	for v != 0 {
		v &= v - 1
		count++
	}
	return count
}
