// Code generated by tools/uops_gen. DO NOT EDIT.
// uop header sha256: 60fbd59734258e874ca1d7d2f65752702dc0ebecb453c8939a059a17418cfdd6

package optimizer

import "github.com/tamnd/gopy/compile"

// Tier-2 micro-op IDs. Numeric IDs (>= 300) name uops the Tier-2
// dispatch loop owns; aliased IDs reuse the Tier-1 opcode value so
// the trace projection can copy a Tier-1 instruction into the
// trace without remapping.
//
// CPython: Include/internal/pycore_uop_ids.h
const (
	UopExitTrace uint16 = 300
	UopSetIp uint16 = 301
	UopBinaryOp uint16 = 302
	UopBinaryOpAddFloat uint16 = 303
	UopBinaryOpAddInt uint16 = 304
	UopBinaryOpAddUnicode uint16 = 305
	UopBinaryOpExtend uint16 = 306
	UopBinaryOpInplaceAddUnicode uint16 = 307
	UopBinaryOpMultiplyFloat uint16 = 308
	UopBinaryOpMultiplyInt uint16 = 309
	UopBinaryOpSubscrCheckFunc uint16 = 310
	UopBinaryOpSubscrDict uint16 = 311
	UopBinaryOpSubscrInitCall uint16 = 312
	UopBinaryOpSubscrListInt uint16 = 313
	UopBinaryOpSubscrListSlice uint16 = 314
	UopBinaryOpSubscrStrInt uint16 = 315
	UopBinaryOpSubscrTupleInt uint16 = 316
	UopBinaryOpSubtractFloat uint16 = 317
	UopBinaryOpSubtractInt uint16 = 318
	UopBinarySlice uint16 = 319
	UopBuildInterpolation uint16 = uint16(compile.BUILD_INTERPOLATION)
	UopBuildList uint16 = uint16(compile.BUILD_LIST)
	UopBuildMap uint16 = uint16(compile.BUILD_MAP)
	UopBuildSet uint16 = uint16(compile.BUILD_SET)
	UopBuildSlice uint16 = uint16(compile.BUILD_SLICE)
	UopBuildString uint16 = uint16(compile.BUILD_STRING)
	UopBuildTemplate uint16 = uint16(compile.BUILD_TEMPLATE)
	UopBuildTuple uint16 = uint16(compile.BUILD_TUPLE)
	UopCallBuiltinClass uint16 = 320
	UopCallBuiltinFast uint16 = 321
	UopCallBuiltinFastWithKeywords uint16 = 322
	UopCallBuiltinO uint16 = 323
	UopCallIntrinsic1 uint16 = uint16(compile.CALL_INTRINSIC_1)
	UopCallIntrinsic2 uint16 = uint16(compile.CALL_INTRINSIC_2)
	UopCallIsinstance uint16 = uint16(compile.CALL_ISINSTANCE)
	UopCallKwNonPy uint16 = 324
	UopCallLen uint16 = 325
	UopCallListAppend uint16 = uint16(compile.CALL_LIST_APPEND)
	UopCallMethodDescriptorFast uint16 = 326
	UopCallMethodDescriptorFastWithKeywords uint16 = 327
	UopCallMethodDescriptorNoargs uint16 = 328
	UopCallMethodDescriptorO uint16 = 329
	UopCallNonPyGeneral uint16 = 330
	UopCallStr1 uint16 = 331
	UopCallTuple1 uint16 = 332
	UopCallType1 uint16 = 333
	UopCheckAndAllocateObject uint16 = 334
	UopCheckAttrClass uint16 = 335
	UopCheckAttrMethodLazyDict uint16 = 336
	UopCheckCallBoundMethodExactArgs uint16 = 337
	UopCheckEgMatch uint16 = uint16(compile.CHECK_EG_MATCH)
	UopCheckExcMatch uint16 = uint16(compile.CHECK_EXC_MATCH)
	UopCheckFunction uint16 = 338
	UopCheckFunctionExactArgs uint16 = 339
	UopCheckFunctionVersion uint16 = 340
	UopCheckFunctionVersionInline uint16 = 341
	UopCheckFunctionVersionKw uint16 = 342
	UopCheckIsNotPyCallable uint16 = 343
	UopCheckIsNotPyCallableKw uint16 = 344
	UopCheckManagedObjectHasValues uint16 = 345
	UopCheckMethodVersion uint16 = 346
	UopCheckMethodVersionKw uint16 = 347
	UopCheckPep523 uint16 = 348
	UopCheckPeriodic uint16 = 349
	UopCheckPeriodicIfNotYieldFrom uint16 = 350
	UopCheckRecursionRemaining uint16 = 351
	UopCheckStackSpace uint16 = 352
	UopCheckStackSpaceOperand uint16 = 353
	UopCheckValidity uint16 = 354
	UopCompareOp uint16 = 355
	UopCompareOpFloat uint16 = 356
	UopCompareOpInt uint16 = 357
	UopCompareOpStr uint16 = 358
	UopContainsOp uint16 = 359
	UopContainsOpDict uint16 = 360
	UopContainsOpSet uint16 = 361
	UopConvertValue uint16 = uint16(compile.CONVERT_VALUE)
	UopCopy uint16 = uint16(compile.COPY)
	UopCopyFreeVars uint16 = uint16(compile.COPY_FREE_VARS)
	UopCreateInitFrame uint16 = 362
	UopDeleteAttr uint16 = uint16(compile.DELETE_ATTR)
	UopDeleteDeref uint16 = uint16(compile.DELETE_DEREF)
	UopDeleteFast uint16 = uint16(compile.DELETE_FAST)
	UopDeleteGlobal uint16 = uint16(compile.DELETE_GLOBAL)
	UopDeleteName uint16 = uint16(compile.DELETE_NAME)
	UopDeleteSubscr uint16 = uint16(compile.DELETE_SUBSCR)
	UopDeopt uint16 = 363
	UopDictMerge uint16 = uint16(compile.DICT_MERGE)
	UopDictUpdate uint16 = uint16(compile.DICT_UPDATE)
	UopDoCall uint16 = 364
	UopDoCallFunctionEx uint16 = 365
	UopDoCallKw uint16 = 366
	UopEndFor uint16 = uint16(compile.END_FOR)
	UopEndSend uint16 = uint16(compile.END_SEND)
	UopErrorPopN uint16 = 367
	UopExitInitCheck uint16 = uint16(compile.EXIT_INIT_CHECK)
	UopExpandMethod uint16 = 368
	UopExpandMethodKw uint16 = 369
	UopFatalError uint16 = 370
	UopFormatSimple uint16 = uint16(compile.FORMAT_SIMPLE)
	UopFormatWithSpec uint16 = uint16(compile.FORMAT_WITH_SPEC)
	UopForIter uint16 = 371
	UopForIterGenFrame uint16 = 372
	UopForIterTierTwo uint16 = 373
	UopGetAiter uint16 = uint16(compile.GET_AITER)
	UopGetAnext uint16 = uint16(compile.GET_ANEXT)
	UopGetAwaitable uint16 = uint16(compile.GET_AWAITABLE)
	UopGetIter uint16 = uint16(compile.GET_ITER)
	UopGetLen uint16 = uint16(compile.GET_LEN)
	UopGetYieldFromIter uint16 = uint16(compile.GET_YIELD_FROM_ITER)
	UopGuardBinaryOpExtend uint16 = 374
	UopGuardCallableLen uint16 = 375
	UopGuardCallableStr1 uint16 = 376
	UopGuardCallableTuple1 uint16 = 377
	UopGuardCallableType1 uint16 = 378
	UopGuardDorvNoDict uint16 = 379
	UopGuardDorvValuesInstAttrFromDict uint16 = 380
	UopGuardGlobalsVersion uint16 = 381
	UopGuardIsFalsePop uint16 = 382
	UopGuardIsNonePop uint16 = 383
	UopGuardIsNotNonePop uint16 = 384
	UopGuardIsTruePop uint16 = 385
	UopGuardKeysVersion uint16 = 386
	UopGuardNosDict uint16 = 387
	UopGuardNosFloat uint16 = 388
	UopGuardNosInt uint16 = 389
	UopGuardNosList uint16 = 390
	UopGuardNosNull uint16 = 391
	UopGuardNosTuple uint16 = 392
	UopGuardNosUnicode uint16 = 393
	UopGuardNotExhaustedList uint16 = 394
	UopGuardNotExhaustedRange uint16 = 395
	UopGuardNotExhaustedTuple uint16 = 396
	UopGuardTosAnySet uint16 = 397
	UopGuardTosDict uint16 = 398
	UopGuardTosFloat uint16 = 399
	UopGuardTosInt uint16 = 400
	UopGuardTosList uint16 = 401
	UopGuardTosSlice uint16 = 402
	UopGuardTosTuple uint16 = 403
	UopGuardTosUnicode uint16 = 404
	UopGuardTypeVersion uint16 = 405
	UopGuardTypeVersionAndLock uint16 = 406
	UopImportFrom uint16 = uint16(compile.IMPORT_FROM)
	UopImportName uint16 = uint16(compile.IMPORT_NAME)
	UopInitCallBoundMethodExactArgs uint16 = 407
	UopInitCallPyExactArgs uint16 = 408
	UopInitCallPyExactArgs0 uint16 = 409
	UopInitCallPyExactArgs1 uint16 = 410
	UopInitCallPyExactArgs2 uint16 = 411
	UopInitCallPyExactArgs3 uint16 = 412
	UopInitCallPyExactArgs4 uint16 = 413
	UopInsertNull uint16 = 414
	UopInstrumentedForIter uint16 = uint16(compile.INSTRUMENTED_FOR_ITER)
	UopInstrumentedInstruction uint16 = uint16(compile.INSTRUMENTED_INSTRUCTION)
	UopInstrumentedJumpForward uint16 = uint16(compile.INSTRUMENTED_JUMP_FORWARD)
	UopInstrumentedLine uint16 = uint16(compile.INSTRUMENTED_LINE)
	UopInstrumentedNotTaken uint16 = uint16(compile.INSTRUMENTED_NOT_TAKEN)
	UopInstrumentedPopJumpIfFalse uint16 = uint16(compile.INSTRUMENTED_POP_JUMP_IF_FALSE)
	UopInstrumentedPopJumpIfNone uint16 = uint16(compile.INSTRUMENTED_POP_JUMP_IF_NONE)
	UopInstrumentedPopJumpIfNotNone uint16 = uint16(compile.INSTRUMENTED_POP_JUMP_IF_NOT_NONE)
	UopInstrumentedPopJumpIfTrue uint16 = uint16(compile.INSTRUMENTED_POP_JUMP_IF_TRUE)
	UopIsNone uint16 = 415
	UopIsOp uint16 = uint16(compile.IS_OP)
	UopIterCheckList uint16 = 416
	UopIterCheckRange uint16 = 417
	UopIterCheckTuple uint16 = 418
	UopIterJumpList uint16 = 419
	UopIterJumpRange uint16 = 420
	UopIterJumpTuple uint16 = 421
	UopIterNextList uint16 = 422
	UopIterNextListTierTwo uint16 = 423
	UopIterNextRange uint16 = 424
	UopIterNextTuple uint16 = 425
	UopJumpToTop uint16 = 426
	UopListAppend uint16 = uint16(compile.LIST_APPEND)
	UopListExtend uint16 = uint16(compile.LIST_EXTEND)
	UopLoadAttr uint16 = 427
	UopLoadAttrClass uint16 = 428
	UopLoadAttrGetattributeOverridden uint16 = uint16(compile.LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN)
	UopLoadAttrInstanceValue uint16 = 429
	UopLoadAttrMethodLazyDict uint16 = 430
	UopLoadAttrMethodNoDict uint16 = 431
	UopLoadAttrMethodWithValues uint16 = 432
	UopLoadAttrModule uint16 = 433
	UopLoadAttrNondescriptorNoDict uint16 = 434
	UopLoadAttrNondescriptorWithValues uint16 = 435
	UopLoadAttrPropertyFrame uint16 = 436
	UopLoadAttrSlot uint16 = 437
	UopLoadAttrWithHint uint16 = 438
	UopLoadBuildClass uint16 = uint16(compile.LOAD_BUILD_CLASS)
	UopLoadBytecode uint16 = 439
	UopLoadCommonConstant uint16 = uint16(compile.LOAD_COMMON_CONSTANT)
	UopLoadConst uint16 = uint16(compile.LOAD_CONST)
	UopLoadConstImmortal uint16 = uint16(compile.LOAD_CONST_IMMORTAL)
	UopLoadConstInline uint16 = 440
	UopLoadConstInlineBorrow uint16 = 441
	UopLoadConstMortal uint16 = uint16(compile.LOAD_CONST_MORTAL)
	UopLoadDeref uint16 = uint16(compile.LOAD_DEREF)
	UopLoadFast uint16 = 442
	UopLoadFast0 uint16 = 443
	UopLoadFast1 uint16 = 444
	UopLoadFast2 uint16 = 445
	UopLoadFast3 uint16 = 446
	UopLoadFast4 uint16 = 447
	UopLoadFast5 uint16 = 448
	UopLoadFast6 uint16 = 449
	UopLoadFast7 uint16 = 450
	UopLoadFastAndClear uint16 = uint16(compile.LOAD_FAST_AND_CLEAR)
	UopLoadFastBorrow uint16 = 451
	UopLoadFastBorrow0 uint16 = 452
	UopLoadFastBorrow1 uint16 = 453
	UopLoadFastBorrow2 uint16 = 454
	UopLoadFastBorrow3 uint16 = 455
	UopLoadFastBorrow4 uint16 = 456
	UopLoadFastBorrow5 uint16 = 457
	UopLoadFastBorrow6 uint16 = 458
	UopLoadFastBorrow7 uint16 = 459
	UopLoadFastBorrowLoadFastBorrow uint16 = uint16(compile.LOAD_FAST_BORROW_LOAD_FAST_BORROW)
	UopLoadFastCheck uint16 = uint16(compile.LOAD_FAST_CHECK)
	UopLoadFastLoadFast uint16 = uint16(compile.LOAD_FAST_LOAD_FAST)
	UopLoadFromDictOrDeref uint16 = uint16(compile.LOAD_FROM_DICT_OR_DEREF)
	UopLoadFromDictOrGlobals uint16 = uint16(compile.LOAD_FROM_DICT_OR_GLOBALS)
	UopLoadGlobal uint16 = 460
	UopLoadGlobalBuiltins uint16 = 461
	UopLoadGlobalModule uint16 = 462
	UopLoadLocals uint16 = uint16(compile.LOAD_LOCALS)
	UopLoadName uint16 = uint16(compile.LOAD_NAME)
	UopLoadSmallInt uint16 = 463
	UopLoadSmallInt0 uint16 = 464
	UopLoadSmallInt1 uint16 = 465
	UopLoadSmallInt2 uint16 = 466
	UopLoadSmallInt3 uint16 = 467
	UopLoadSpecial uint16 = 468
	UopLoadSuperAttrAttr uint16 = uint16(compile.LOAD_SUPER_ATTR_ATTR)
	UopLoadSuperAttrMethod uint16 = uint16(compile.LOAD_SUPER_ATTR_METHOD)
	UopMakeCallargsATuple uint16 = 469
	UopMakeCell uint16 = uint16(compile.MAKE_CELL)
	UopMakeFunction uint16 = uint16(compile.MAKE_FUNCTION)
	UopMakeWarm uint16 = 470
	UopMapAdd uint16 = uint16(compile.MAP_ADD)
	UopMatchClass uint16 = uint16(compile.MATCH_CLASS)
	UopMatchKeys uint16 = uint16(compile.MATCH_KEYS)
	UopMatchMapping uint16 = uint16(compile.MATCH_MAPPING)
	UopMatchSequence uint16 = uint16(compile.MATCH_SEQUENCE)
	UopMaybeExpandMethod uint16 = 471
	UopMaybeExpandMethodKw uint16 = 472
	UopMonitorCall uint16 = 473
	UopMonitorCallKw uint16 = 474
	UopMonitorJumpBackward uint16 = 475
	UopMonitorResume uint16 = 476
	UopNop uint16 = uint16(compile.NOP)
	UopPopExcept uint16 = uint16(compile.POP_EXCEPT)
	UopPopJumpIfFalse uint16 = 477
	UopPopJumpIfTrue uint16 = 478
	UopPopTop uint16 = uint16(compile.POP_TOP)
	UopPopTopLoadConstInline uint16 = 479
	UopPopTopLoadConstInlineBorrow uint16 = 480
	UopPopTwoLoadConstInlineBorrow uint16 = 481
	UopPushExcInfo uint16 = uint16(compile.PUSH_EXC_INFO)
	UopPushFrame uint16 = 482
	UopPushNull uint16 = uint16(compile.PUSH_NULL)
	UopPushNullConditional uint16 = 483
	UopPyFrameGeneral uint16 = 484
	UopPyFrameKw uint16 = 485
	UopQuickenResume uint16 = 486
	UopReplaceWithTrue uint16 = 487
	UopResumeCheck uint16 = uint16(compile.RESUME_CHECK)
	UopReturnGenerator uint16 = uint16(compile.RETURN_GENERATOR)
	UopReturnValue uint16 = uint16(compile.RETURN_VALUE)
	UopSaveReturnOffset uint16 = 488
	UopSend uint16 = 489
	UopSendGenFrame uint16 = 490
	UopSetupAnnotations uint16 = uint16(compile.SETUP_ANNOTATIONS)
	UopSetAdd uint16 = uint16(compile.SET_ADD)
	UopSetFunctionAttribute uint16 = uint16(compile.SET_FUNCTION_ATTRIBUTE)
	UopSetUpdate uint16 = uint16(compile.SET_UPDATE)
	UopStartExecutor uint16 = 491
	UopStoreAttr uint16 = 492
	UopStoreAttrInstanceValue uint16 = 493
	UopStoreAttrSlot uint16 = 494
	UopStoreAttrWithHint uint16 = 495
	UopStoreDeref uint16 = uint16(compile.STORE_DEREF)
	UopStoreFast uint16 = 496
	UopStoreFast0 uint16 = 497
	UopStoreFast1 uint16 = 498
	UopStoreFast2 uint16 = 499
	UopStoreFast3 uint16 = 500
	UopStoreFast4 uint16 = 501
	UopStoreFast5 uint16 = 502
	UopStoreFast6 uint16 = 503
	UopStoreFast7 uint16 = 504
	UopStoreFastLoadFast uint16 = uint16(compile.STORE_FAST_LOAD_FAST)
	UopStoreFastStoreFast uint16 = uint16(compile.STORE_FAST_STORE_FAST)
	UopStoreGlobal uint16 = uint16(compile.STORE_GLOBAL)
	UopStoreName uint16 = uint16(compile.STORE_NAME)
	UopStoreSlice uint16 = 505
	UopStoreSubscr uint16 = 506
	UopStoreSubscrDict uint16 = 507
	UopStoreSubscrListInt uint16 = 508
	UopSwap uint16 = uint16(compile.SWAP)
	UopTier2ResumeCheck uint16 = 509
	UopToBool uint16 = 510
	UopToBoolBool uint16 = uint16(compile.TO_BOOL_BOOL)
	UopToBoolInt uint16 = uint16(compile.TO_BOOL_INT)
	UopToBoolList uint16 = 511
	UopToBoolNone uint16 = uint16(compile.TO_BOOL_NONE)
	UopToBoolStr uint16 = 512
	UopUnaryInvert uint16 = uint16(compile.UNARY_INVERT)
	UopUnaryNegative uint16 = uint16(compile.UNARY_NEGATIVE)
	UopUnaryNot uint16 = uint16(compile.UNARY_NOT)
	UopUnpackEx uint16 = uint16(compile.UNPACK_EX)
	UopUnpackSequence uint16 = 513
	UopUnpackSequenceList uint16 = 514
	UopUnpackSequenceTuple uint16 = 515
	UopUnpackSequenceTwoTuple uint16 = 516
	UopWithExceptStart uint16 = uint16(compile.WITH_EXCEPT_START)
	UopYieldValue uint16 = uint16(compile.YIELD_VALUE)
	MaxUopID uint16 = 516
)

// UopNames maps a uop ID to its CPython spelling. The dispatch and
// disassembly paths use this to render trace rows with the same uop
// names dis.dis emits upstream.
var UopNames = map[uint16]string{
	UopExitTrace: "_EXIT_TRACE",
	UopSetIp: "_SET_IP",
	UopBinaryOp: "_BINARY_OP",
	UopBinaryOpAddFloat: "_BINARY_OP_ADD_FLOAT",
	UopBinaryOpAddInt: "_BINARY_OP_ADD_INT",
	UopBinaryOpAddUnicode: "_BINARY_OP_ADD_UNICODE",
	UopBinaryOpExtend: "_BINARY_OP_EXTEND",
	UopBinaryOpInplaceAddUnicode: "_BINARY_OP_INPLACE_ADD_UNICODE",
	UopBinaryOpMultiplyFloat: "_BINARY_OP_MULTIPLY_FLOAT",
	UopBinaryOpMultiplyInt: "_BINARY_OP_MULTIPLY_INT",
	UopBinaryOpSubscrCheckFunc: "_BINARY_OP_SUBSCR_CHECK_FUNC",
	UopBinaryOpSubscrDict: "_BINARY_OP_SUBSCR_DICT",
	UopBinaryOpSubscrInitCall: "_BINARY_OP_SUBSCR_INIT_CALL",
	UopBinaryOpSubscrListInt: "_BINARY_OP_SUBSCR_LIST_INT",
	UopBinaryOpSubscrListSlice: "_BINARY_OP_SUBSCR_LIST_SLICE",
	UopBinaryOpSubscrStrInt: "_BINARY_OP_SUBSCR_STR_INT",
	UopBinaryOpSubscrTupleInt: "_BINARY_OP_SUBSCR_TUPLE_INT",
	UopBinaryOpSubtractFloat: "_BINARY_OP_SUBTRACT_FLOAT",
	UopBinaryOpSubtractInt: "_BINARY_OP_SUBTRACT_INT",
	UopBinarySlice: "_BINARY_SLICE",
	UopBuildInterpolation: "_BUILD_INTERPOLATION",
	UopBuildList: "_BUILD_LIST",
	UopBuildMap: "_BUILD_MAP",
	UopBuildSet: "_BUILD_SET",
	UopBuildSlice: "_BUILD_SLICE",
	UopBuildString: "_BUILD_STRING",
	UopBuildTemplate: "_BUILD_TEMPLATE",
	UopBuildTuple: "_BUILD_TUPLE",
	UopCallBuiltinClass: "_CALL_BUILTIN_CLASS",
	UopCallBuiltinFast: "_CALL_BUILTIN_FAST",
	UopCallBuiltinFastWithKeywords: "_CALL_BUILTIN_FAST_WITH_KEYWORDS",
	UopCallBuiltinO: "_CALL_BUILTIN_O",
	UopCallIntrinsic1: "_CALL_INTRINSIC_1",
	UopCallIntrinsic2: "_CALL_INTRINSIC_2",
	UopCallIsinstance: "_CALL_ISINSTANCE",
	UopCallKwNonPy: "_CALL_KW_NON_PY",
	UopCallLen: "_CALL_LEN",
	UopCallListAppend: "_CALL_LIST_APPEND",
	UopCallMethodDescriptorFast: "_CALL_METHOD_DESCRIPTOR_FAST",
	UopCallMethodDescriptorFastWithKeywords: "_CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS",
	UopCallMethodDescriptorNoargs: "_CALL_METHOD_DESCRIPTOR_NOARGS",
	UopCallMethodDescriptorO: "_CALL_METHOD_DESCRIPTOR_O",
	UopCallNonPyGeneral: "_CALL_NON_PY_GENERAL",
	UopCallStr1: "_CALL_STR_1",
	UopCallTuple1: "_CALL_TUPLE_1",
	UopCallType1: "_CALL_TYPE_1",
	UopCheckAndAllocateObject: "_CHECK_AND_ALLOCATE_OBJECT",
	UopCheckAttrClass: "_CHECK_ATTR_CLASS",
	UopCheckAttrMethodLazyDict: "_CHECK_ATTR_METHOD_LAZY_DICT",
	UopCheckCallBoundMethodExactArgs: "_CHECK_CALL_BOUND_METHOD_EXACT_ARGS",
	UopCheckEgMatch: "_CHECK_EG_MATCH",
	UopCheckExcMatch: "_CHECK_EXC_MATCH",
	UopCheckFunction: "_CHECK_FUNCTION",
	UopCheckFunctionExactArgs: "_CHECK_FUNCTION_EXACT_ARGS",
	UopCheckFunctionVersion: "_CHECK_FUNCTION_VERSION",
	UopCheckFunctionVersionInline: "_CHECK_FUNCTION_VERSION_INLINE",
	UopCheckFunctionVersionKw: "_CHECK_FUNCTION_VERSION_KW",
	UopCheckIsNotPyCallable: "_CHECK_IS_NOT_PY_CALLABLE",
	UopCheckIsNotPyCallableKw: "_CHECK_IS_NOT_PY_CALLABLE_KW",
	UopCheckManagedObjectHasValues: "_CHECK_MANAGED_OBJECT_HAS_VALUES",
	UopCheckMethodVersion: "_CHECK_METHOD_VERSION",
	UopCheckMethodVersionKw: "_CHECK_METHOD_VERSION_KW",
	UopCheckPep523: "_CHECK_PEP_523",
	UopCheckPeriodic: "_CHECK_PERIODIC",
	UopCheckPeriodicIfNotYieldFrom: "_CHECK_PERIODIC_IF_NOT_YIELD_FROM",
	UopCheckRecursionRemaining: "_CHECK_RECURSION_REMAINING",
	UopCheckStackSpace: "_CHECK_STACK_SPACE",
	UopCheckStackSpaceOperand: "_CHECK_STACK_SPACE_OPERAND",
	UopCheckValidity: "_CHECK_VALIDITY",
	UopCompareOp: "_COMPARE_OP",
	UopCompareOpFloat: "_COMPARE_OP_FLOAT",
	UopCompareOpInt: "_COMPARE_OP_INT",
	UopCompareOpStr: "_COMPARE_OP_STR",
	UopContainsOp: "_CONTAINS_OP",
	UopContainsOpDict: "_CONTAINS_OP_DICT",
	UopContainsOpSet: "_CONTAINS_OP_SET",
	UopConvertValue: "_CONVERT_VALUE",
	UopCopy: "_COPY",
	UopCopyFreeVars: "_COPY_FREE_VARS",
	UopCreateInitFrame: "_CREATE_INIT_FRAME",
	UopDeleteAttr: "_DELETE_ATTR",
	UopDeleteDeref: "_DELETE_DEREF",
	UopDeleteFast: "_DELETE_FAST",
	UopDeleteGlobal: "_DELETE_GLOBAL",
	UopDeleteName: "_DELETE_NAME",
	UopDeleteSubscr: "_DELETE_SUBSCR",
	UopDeopt: "_DEOPT",
	UopDictMerge: "_DICT_MERGE",
	UopDictUpdate: "_DICT_UPDATE",
	UopDoCall: "_DO_CALL",
	UopDoCallFunctionEx: "_DO_CALL_FUNCTION_EX",
	UopDoCallKw: "_DO_CALL_KW",
	UopEndFor: "_END_FOR",
	UopEndSend: "_END_SEND",
	UopErrorPopN: "_ERROR_POP_N",
	UopExitInitCheck: "_EXIT_INIT_CHECK",
	UopExpandMethod: "_EXPAND_METHOD",
	UopExpandMethodKw: "_EXPAND_METHOD_KW",
	UopFatalError: "_FATAL_ERROR",
	UopFormatSimple: "_FORMAT_SIMPLE",
	UopFormatWithSpec: "_FORMAT_WITH_SPEC",
	UopForIter: "_FOR_ITER",
	UopForIterGenFrame: "_FOR_ITER_GEN_FRAME",
	UopForIterTierTwo: "_FOR_ITER_TIER_TWO",
	UopGetAiter: "_GET_AITER",
	UopGetAnext: "_GET_ANEXT",
	UopGetAwaitable: "_GET_AWAITABLE",
	UopGetIter: "_GET_ITER",
	UopGetLen: "_GET_LEN",
	UopGetYieldFromIter: "_GET_YIELD_FROM_ITER",
	UopGuardBinaryOpExtend: "_GUARD_BINARY_OP_EXTEND",
	UopGuardCallableLen: "_GUARD_CALLABLE_LEN",
	UopGuardCallableStr1: "_GUARD_CALLABLE_STR_1",
	UopGuardCallableTuple1: "_GUARD_CALLABLE_TUPLE_1",
	UopGuardCallableType1: "_GUARD_CALLABLE_TYPE_1",
	UopGuardDorvNoDict: "_GUARD_DORV_NO_DICT",
	UopGuardDorvValuesInstAttrFromDict: "_GUARD_DORV_VALUES_INST_ATTR_FROM_DICT",
	UopGuardGlobalsVersion: "_GUARD_GLOBALS_VERSION",
	UopGuardIsFalsePop: "_GUARD_IS_FALSE_POP",
	UopGuardIsNonePop: "_GUARD_IS_NONE_POP",
	UopGuardIsNotNonePop: "_GUARD_IS_NOT_NONE_POP",
	UopGuardIsTruePop: "_GUARD_IS_TRUE_POP",
	UopGuardKeysVersion: "_GUARD_KEYS_VERSION",
	UopGuardNosDict: "_GUARD_NOS_DICT",
	UopGuardNosFloat: "_GUARD_NOS_FLOAT",
	UopGuardNosInt: "_GUARD_NOS_INT",
	UopGuardNosList: "_GUARD_NOS_LIST",
	UopGuardNosNull: "_GUARD_NOS_NULL",
	UopGuardNosTuple: "_GUARD_NOS_TUPLE",
	UopGuardNosUnicode: "_GUARD_NOS_UNICODE",
	UopGuardNotExhaustedList: "_GUARD_NOT_EXHAUSTED_LIST",
	UopGuardNotExhaustedRange: "_GUARD_NOT_EXHAUSTED_RANGE",
	UopGuardNotExhaustedTuple: "_GUARD_NOT_EXHAUSTED_TUPLE",
	UopGuardTosAnySet: "_GUARD_TOS_ANY_SET",
	UopGuardTosDict: "_GUARD_TOS_DICT",
	UopGuardTosFloat: "_GUARD_TOS_FLOAT",
	UopGuardTosInt: "_GUARD_TOS_INT",
	UopGuardTosList: "_GUARD_TOS_LIST",
	UopGuardTosSlice: "_GUARD_TOS_SLICE",
	UopGuardTosTuple: "_GUARD_TOS_TUPLE",
	UopGuardTosUnicode: "_GUARD_TOS_UNICODE",
	UopGuardTypeVersion: "_GUARD_TYPE_VERSION",
	UopGuardTypeVersionAndLock: "_GUARD_TYPE_VERSION_AND_LOCK",
	UopImportFrom: "_IMPORT_FROM",
	UopImportName: "_IMPORT_NAME",
	UopInitCallBoundMethodExactArgs: "_INIT_CALL_BOUND_METHOD_EXACT_ARGS",
	UopInitCallPyExactArgs: "_INIT_CALL_PY_EXACT_ARGS",
	UopInitCallPyExactArgs0: "_INIT_CALL_PY_EXACT_ARGS_0",
	UopInitCallPyExactArgs1: "_INIT_CALL_PY_EXACT_ARGS_1",
	UopInitCallPyExactArgs2: "_INIT_CALL_PY_EXACT_ARGS_2",
	UopInitCallPyExactArgs3: "_INIT_CALL_PY_EXACT_ARGS_3",
	UopInitCallPyExactArgs4: "_INIT_CALL_PY_EXACT_ARGS_4",
	UopInsertNull: "_INSERT_NULL",
	UopInstrumentedForIter: "_INSTRUMENTED_FOR_ITER",
	UopInstrumentedInstruction: "_INSTRUMENTED_INSTRUCTION",
	UopInstrumentedJumpForward: "_INSTRUMENTED_JUMP_FORWARD",
	UopInstrumentedLine: "_INSTRUMENTED_LINE",
	UopInstrumentedNotTaken: "_INSTRUMENTED_NOT_TAKEN",
	UopInstrumentedPopJumpIfFalse: "_INSTRUMENTED_POP_JUMP_IF_FALSE",
	UopInstrumentedPopJumpIfNone: "_INSTRUMENTED_POP_JUMP_IF_NONE",
	UopInstrumentedPopJumpIfNotNone: "_INSTRUMENTED_POP_JUMP_IF_NOT_NONE",
	UopInstrumentedPopJumpIfTrue: "_INSTRUMENTED_POP_JUMP_IF_TRUE",
	UopIsNone: "_IS_NONE",
	UopIsOp: "_IS_OP",
	UopIterCheckList: "_ITER_CHECK_LIST",
	UopIterCheckRange: "_ITER_CHECK_RANGE",
	UopIterCheckTuple: "_ITER_CHECK_TUPLE",
	UopIterJumpList: "_ITER_JUMP_LIST",
	UopIterJumpRange: "_ITER_JUMP_RANGE",
	UopIterJumpTuple: "_ITER_JUMP_TUPLE",
	UopIterNextList: "_ITER_NEXT_LIST",
	UopIterNextListTierTwo: "_ITER_NEXT_LIST_TIER_TWO",
	UopIterNextRange: "_ITER_NEXT_RANGE",
	UopIterNextTuple: "_ITER_NEXT_TUPLE",
	UopJumpToTop: "_JUMP_TO_TOP",
	UopListAppend: "_LIST_APPEND",
	UopListExtend: "_LIST_EXTEND",
	UopLoadAttr: "_LOAD_ATTR",
	UopLoadAttrClass: "_LOAD_ATTR_CLASS",
	UopLoadAttrGetattributeOverridden: "_LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN",
	UopLoadAttrInstanceValue: "_LOAD_ATTR_INSTANCE_VALUE",
	UopLoadAttrMethodLazyDict: "_LOAD_ATTR_METHOD_LAZY_DICT",
	UopLoadAttrMethodNoDict: "_LOAD_ATTR_METHOD_NO_DICT",
	UopLoadAttrMethodWithValues: "_LOAD_ATTR_METHOD_WITH_VALUES",
	UopLoadAttrModule: "_LOAD_ATTR_MODULE",
	UopLoadAttrNondescriptorNoDict: "_LOAD_ATTR_NONDESCRIPTOR_NO_DICT",
	UopLoadAttrNondescriptorWithValues: "_LOAD_ATTR_NONDESCRIPTOR_WITH_VALUES",
	UopLoadAttrPropertyFrame: "_LOAD_ATTR_PROPERTY_FRAME",
	UopLoadAttrSlot: "_LOAD_ATTR_SLOT",
	UopLoadAttrWithHint: "_LOAD_ATTR_WITH_HINT",
	UopLoadBuildClass: "_LOAD_BUILD_CLASS",
	UopLoadBytecode: "_LOAD_BYTECODE",
	UopLoadCommonConstant: "_LOAD_COMMON_CONSTANT",
	UopLoadConst: "_LOAD_CONST",
	UopLoadConstImmortal: "_LOAD_CONST_IMMORTAL",
	UopLoadConstInline: "_LOAD_CONST_INLINE",
	UopLoadConstInlineBorrow: "_LOAD_CONST_INLINE_BORROW",
	UopLoadConstMortal: "_LOAD_CONST_MORTAL",
	UopLoadDeref: "_LOAD_DEREF",
	UopLoadFast: "_LOAD_FAST",
	UopLoadFast0: "_LOAD_FAST_0",
	UopLoadFast1: "_LOAD_FAST_1",
	UopLoadFast2: "_LOAD_FAST_2",
	UopLoadFast3: "_LOAD_FAST_3",
	UopLoadFast4: "_LOAD_FAST_4",
	UopLoadFast5: "_LOAD_FAST_5",
	UopLoadFast6: "_LOAD_FAST_6",
	UopLoadFast7: "_LOAD_FAST_7",
	UopLoadFastAndClear: "_LOAD_FAST_AND_CLEAR",
	UopLoadFastBorrow: "_LOAD_FAST_BORROW",
	UopLoadFastBorrow0: "_LOAD_FAST_BORROW_0",
	UopLoadFastBorrow1: "_LOAD_FAST_BORROW_1",
	UopLoadFastBorrow2: "_LOAD_FAST_BORROW_2",
	UopLoadFastBorrow3: "_LOAD_FAST_BORROW_3",
	UopLoadFastBorrow4: "_LOAD_FAST_BORROW_4",
	UopLoadFastBorrow5: "_LOAD_FAST_BORROW_5",
	UopLoadFastBorrow6: "_LOAD_FAST_BORROW_6",
	UopLoadFastBorrow7: "_LOAD_FAST_BORROW_7",
	UopLoadFastBorrowLoadFastBorrow: "_LOAD_FAST_BORROW_LOAD_FAST_BORROW",
	UopLoadFastCheck: "_LOAD_FAST_CHECK",
	UopLoadFastLoadFast: "_LOAD_FAST_LOAD_FAST",
	UopLoadFromDictOrDeref: "_LOAD_FROM_DICT_OR_DEREF",
	UopLoadFromDictOrGlobals: "_LOAD_FROM_DICT_OR_GLOBALS",
	UopLoadGlobal: "_LOAD_GLOBAL",
	UopLoadGlobalBuiltins: "_LOAD_GLOBAL_BUILTINS",
	UopLoadGlobalModule: "_LOAD_GLOBAL_MODULE",
	UopLoadLocals: "_LOAD_LOCALS",
	UopLoadName: "_LOAD_NAME",
	UopLoadSmallInt: "_LOAD_SMALL_INT",
	UopLoadSmallInt0: "_LOAD_SMALL_INT_0",
	UopLoadSmallInt1: "_LOAD_SMALL_INT_1",
	UopLoadSmallInt2: "_LOAD_SMALL_INT_2",
	UopLoadSmallInt3: "_LOAD_SMALL_INT_3",
	UopLoadSpecial: "_LOAD_SPECIAL",
	UopLoadSuperAttrAttr: "_LOAD_SUPER_ATTR_ATTR",
	UopLoadSuperAttrMethod: "_LOAD_SUPER_ATTR_METHOD",
	UopMakeCallargsATuple: "_MAKE_CALLARGS_A_TUPLE",
	UopMakeCell: "_MAKE_CELL",
	UopMakeFunction: "_MAKE_FUNCTION",
	UopMakeWarm: "_MAKE_WARM",
	UopMapAdd: "_MAP_ADD",
	UopMatchClass: "_MATCH_CLASS",
	UopMatchKeys: "_MATCH_KEYS",
	UopMatchMapping: "_MATCH_MAPPING",
	UopMatchSequence: "_MATCH_SEQUENCE",
	UopMaybeExpandMethod: "_MAYBE_EXPAND_METHOD",
	UopMaybeExpandMethodKw: "_MAYBE_EXPAND_METHOD_KW",
	UopMonitorCall: "_MONITOR_CALL",
	UopMonitorCallKw: "_MONITOR_CALL_KW",
	UopMonitorJumpBackward: "_MONITOR_JUMP_BACKWARD",
	UopMonitorResume: "_MONITOR_RESUME",
	UopNop: "_NOP",
	UopPopExcept: "_POP_EXCEPT",
	UopPopJumpIfFalse: "_POP_JUMP_IF_FALSE",
	UopPopJumpIfTrue: "_POP_JUMP_IF_TRUE",
	UopPopTop: "_POP_TOP",
	UopPopTopLoadConstInline: "_POP_TOP_LOAD_CONST_INLINE",
	UopPopTopLoadConstInlineBorrow: "_POP_TOP_LOAD_CONST_INLINE_BORROW",
	UopPopTwoLoadConstInlineBorrow: "_POP_TWO_LOAD_CONST_INLINE_BORROW",
	UopPushExcInfo: "_PUSH_EXC_INFO",
	UopPushFrame: "_PUSH_FRAME",
	UopPushNull: "_PUSH_NULL",
	UopPushNullConditional: "_PUSH_NULL_CONDITIONAL",
	UopPyFrameGeneral: "_PY_FRAME_GENERAL",
	UopPyFrameKw: "_PY_FRAME_KW",
	UopQuickenResume: "_QUICKEN_RESUME",
	UopReplaceWithTrue: "_REPLACE_WITH_TRUE",
	UopResumeCheck: "_RESUME_CHECK",
	UopReturnGenerator: "_RETURN_GENERATOR",
	UopReturnValue: "_RETURN_VALUE",
	UopSaveReturnOffset: "_SAVE_RETURN_OFFSET",
	UopSend: "_SEND",
	UopSendGenFrame: "_SEND_GEN_FRAME",
	UopSetupAnnotations: "_SETUP_ANNOTATIONS",
	UopSetAdd: "_SET_ADD",
	UopSetFunctionAttribute: "_SET_FUNCTION_ATTRIBUTE",
	UopSetUpdate: "_SET_UPDATE",
	UopStartExecutor: "_START_EXECUTOR",
	UopStoreAttr: "_STORE_ATTR",
	UopStoreAttrInstanceValue: "_STORE_ATTR_INSTANCE_VALUE",
	UopStoreAttrSlot: "_STORE_ATTR_SLOT",
	UopStoreAttrWithHint: "_STORE_ATTR_WITH_HINT",
	UopStoreDeref: "_STORE_DEREF",
	UopStoreFast: "_STORE_FAST",
	UopStoreFast0: "_STORE_FAST_0",
	UopStoreFast1: "_STORE_FAST_1",
	UopStoreFast2: "_STORE_FAST_2",
	UopStoreFast3: "_STORE_FAST_3",
	UopStoreFast4: "_STORE_FAST_4",
	UopStoreFast5: "_STORE_FAST_5",
	UopStoreFast6: "_STORE_FAST_6",
	UopStoreFast7: "_STORE_FAST_7",
	UopStoreFastLoadFast: "_STORE_FAST_LOAD_FAST",
	UopStoreFastStoreFast: "_STORE_FAST_STORE_FAST",
	UopStoreGlobal: "_STORE_GLOBAL",
	UopStoreName: "_STORE_NAME",
	UopStoreSlice: "_STORE_SLICE",
	UopStoreSubscr: "_STORE_SUBSCR",
	UopStoreSubscrDict: "_STORE_SUBSCR_DICT",
	UopStoreSubscrListInt: "_STORE_SUBSCR_LIST_INT",
	UopSwap: "_SWAP",
	UopTier2ResumeCheck: "_TIER2_RESUME_CHECK",
	UopToBool: "_TO_BOOL",
	UopToBoolBool: "_TO_BOOL_BOOL",
	UopToBoolInt: "_TO_BOOL_INT",
	UopToBoolList: "_TO_BOOL_LIST",
	UopToBoolNone: "_TO_BOOL_NONE",
	UopToBoolStr: "_TO_BOOL_STR",
	UopUnaryInvert: "_UNARY_INVERT",
	UopUnaryNegative: "_UNARY_NEGATIVE",
	UopUnaryNot: "_UNARY_NOT",
	UopUnpackEx: "_UNPACK_EX",
	UopUnpackSequence: "_UNPACK_SEQUENCE",
	UopUnpackSequenceList: "_UNPACK_SEQUENCE_LIST",
	UopUnpackSequenceTuple: "_UNPACK_SEQUENCE_TUPLE",
	UopUnpackSequenceTwoTuple: "_UNPACK_SEQUENCE_TWO_TUPLE",
	UopWithExceptStart: "_WITH_EXCEPT_START",
	UopYieldValue: "_YIELD_VALUE",
}
