// Base descriptor protocol. CPython implements __get__ / __set__ /
// __delete__ as type slots (tp_descr_get / tp_descr_set); the gopy
// port mirrors that and provides GetSetDescr as the building block
// for member, getset, and property descriptors.
//
// CPython: Objects/descrobject.c:144 descr_get_qualname

package objects

import "errors"

// GetSetDescr is the v0.10 base descriptor: a (name, fget, fset)
// triple that exposes a Go-backed property to Python attribute
// lookup. CPython uses this exact shape for type-level data
// descriptors generated by PyDescr_NewGetSet.
//
// CPython: Objects/descrobject.c:1620 PyGetSetDescr_Type
type GetSetDescr struct {
	Header
	name string
	fget func(owner Object) (Object, error)
	fset func(owner Object, value Object) error
}

// GetSetDescrType is the type singleton for getset descriptors.
//
// CPython: Objects/descrobject.c:1620 PyGetSetDescr_Type
var GetSetDescrType = NewType("getset_descriptor", []*Type{objectType})

func init() {
	GetSetDescrType.Repr = getsetDescrRepr
	GetSetDescrType.Str = getsetDescrRepr
	GetSetDescrType.DescrGet = getsetDescrGet
	GetSetDescrType.DescrSet = getsetDescrSet
}

// NewGetSetDescr builds a getset descriptor that exposes name on the
// host type. fget is required; fset may be nil for read-only
// descriptors (mirroring CPython's behavior of raising AttributeError
// on assignment when no setter is registered).
//
// CPython: Objects/descrobject.c:1696 PyDescr_NewGetSet
func NewGetSetDescr(name string, fget func(owner Object) (Object, error), fset func(owner Object, value Object) error) *GetSetDescr {
	d := &GetSetDescr{name: name, fget: fget, fset: fset}
	d.init(GetSetDescrType)
	return d
}

// Name returns the attribute name this descriptor binds to.
func (d *GetSetDescr) Name() string {
	return d.name
}

func getsetDescrRepr(o Object) (string, error) {
	d := o.(*GetSetDescr)
	return "<attribute '" + d.name + "'>", nil
}

// getsetDescrGet calls fget with the owner instance. Accessing the
// descriptor on the class itself (owner==nil) returns the descriptor
// unchanged, matching CPython's descr_check. Py_None is a regular
// instance and must not be confused with the C-level NULL that
// signals class access.
//
// CPython: Objects/descrobject.c:153 getset_get
// CPython: Objects/descrobject.c:115 descr_check
func getsetDescrGet(descr Object, owner Object, _ *Type) (Object, error) {
	d := descr.(*GetSetDescr)
	if owner == nil {
		return descr, nil
	}
	if d.fget == nil {
		return nil, errors.New("AttributeError: unreadable attribute " + d.name)
	}
	return d.fget(owner)
}

// getsetDescrSet calls fset, raising AttributeError when the
// descriptor is read-only (no setter registered).
//
// CPython: Objects/descrobject.c:175 getset_set
func getsetDescrSet(descr Object, owner Object, value Object) error {
	d := descr.(*GetSetDescr)
	if d.fset == nil {
		if value == nil {
			return errors.New("AttributeError: can't delete attribute " + d.name)
		}
		return errors.New("AttributeError: can't set attribute " + d.name)
	}
	return d.fset(owner, value)
}

// LookupDescriptor walks t's MRO looking for an attribute named
// `name` that implements the descriptor protocol. Returns the
// descriptor object plus the type whose dict supplied it, or
// (nil, nil) when no descriptor is found. The instance attribute
// lookup machinery uses this to decide whether to call DescrGet.
//
// CPython: Objects/typeobject.c:5121 _PyType_Lookup
func LookupDescriptor(t *Type, name string) (Object, *Type) {
	if t == nil {
		return nil, nil
	}
	for _, base := range t.MRO {
		if base == nil {
			continue
		}
		if d := lookupTypeMember(base, name); d != nil {
			return d, base
		}
	}
	return nil, nil
}

// lookupTypeMember is the per-type slot of the MRO walk above. The
// v0.10 baseline only stores descriptors in a side map populated by
// type setup helpers; once the typeobject port wires real type dicts
// (task #276), this routes through tp_dict instead.
//
// CPython: Objects/typeobject.c:5063 type_getattro (dict lookup)
func lookupTypeMember(t *Type, name string) Object {
	if descrs, ok := typeDescrTable[t]; ok {
		if d, ok := descrs[name]; ok {
			return d
		}
	}
	return nil
}

// typeDescrTable holds per-type descriptors registered through
// SetTypeDescr. Lives outside the Type struct to keep type.go small;
// the typeobject port replaces this with a real tp_dict.
//
// CPython: Objects/typeobject.c:1057 type_dict (analog)
var typeDescrTable = map[*Type]map[string]Object{}

// TypeDescrNames returns the names registered on t through
// SetTypeDescr, walking the MRO and de-duplicating. Used by builtins
// dir() to introspect a class.
func TypeDescrNames(t *Type) []string {
	seen := map[string]struct{}{}
	for _, base := range t.MRO {
		if base == nil {
			continue
		}
		for name := range typeDescrTable[base] {
			seen[name] = struct{}{}
		}
	}
	for name := range typeDescrTable[t] {
		seen[name] = struct{}{}
	}
	out := make([]string, 0, len(seen))
	for name := range seen {
		out = append(out, name)
	}
	return out
}

// SetTypeDescr installs d as the attribute name on t. Used by built-in
// type initialisers to expose properties before the typeobject port
// gives every type a real __dict__.
//
// CPython: Objects/typeobject.c:6012 type_add_method
func SetTypeDescr(t *Type, name string, d Object) {
	m, ok := typeDescrTable[t]
	if !ok {
		m = map[string]Object{}
		typeDescrTable[t] = m
	}
	m[name] = d
}

// TypeOwnDescrs returns the names and values registered directly on
// t (no MRO walk). Iteration order is not stable. Callers must not
// mutate the returned map; use SetTypeDescr / DelTypeDescr instead.
// Mirrors a read of tp_dict for a single class.
//
// CPython: Objects/typeobject.c:1057 type_dict
func TypeOwnDescrs(t *Type) map[string]Object {
	if t == nil {
		return nil
	}
	return typeDescrTable[t]
}

// DelTypeDescr removes name from t's own descriptor table. Returns
// true when the entry existed. Mirrors a PyDict_DelItem on tp_dict.
//
// CPython: Objects/typeobject.c:6012 type_add_method (inverse path)
func DelTypeDescr(t *Type, name string) bool {
	m, ok := typeDescrTable[t]
	if !ok {
		return false
	}
	if _, ok := m[name]; !ok {
		return false
	}
	delete(m, name)
	return true
}
