// Base descriptor protocol. CPython implements __get__ / __set__ /
// __delete__ as type slots (tp_descr_get / tp_descr_set); the gopy
// port mirrors that and provides GetSetDescr as the building block
// for member, getset, and property descriptors.
//
// CPython: Objects/descrobject.c:144 descr_get_qualname

package objects

import (
	"errors"
	"fmt"
)

// GetSetDescr is the v0.10 base descriptor: a (name, fget, fset)
// triple that exposes a Go-backed property to Python attribute
// lookup. CPython uses this exact shape for type-level data
// descriptors generated by PyDescr_NewGetSet.
//
// CPython: Objects/descrobject.c:1620 PyGetSetDescr_Type
type GetSetDescr struct {
	Header
	name  string
	doc   string
	owner *Type
	fget  func(owner Object) (Object, error)
	fset  func(owner Object, value Object) error
}

// GetSetDescrType is the type singleton for getset descriptors.
//
// CPython: Objects/descrobject.c:1620 PyGetSetDescr_Type
var GetSetDescrType = NewType("getset_descriptor", []*Type{objectType})

func init() {
	GetSetDescrType.Repr = getsetDescrRepr
	GetSetDescrType.Str = getsetDescrRepr
	GetSetDescrType.DescrGet = getsetDescrGet
	GetSetDescrType.DescrSet = getsetDescrSet
	addDescriptorSlotWrappers(GetSetDescrType)
	addDescrIntrospectionDescriptors(GetSetDescrType)
}

// addDescrIntrospectionDescriptors exposes __name__ and __objclass__
// on a descriptor type. CPython stuffs these on every PyDescrObject
// subclass through PyMemberDef descr_members and reads them from
// inspect.getattr_static / typing._ProtocolMeta when inferring whether
// an instance satisfies a protocol's attribute set.
//
// CPython: Objects/descrobject.c:642 descr_members
func addDescrIntrospectionDescriptors(t *Type) {
	SetTypeDescr(t, "__name__", NewGetSetDescr("__name__", descrNameGetter, nil))
	SetTypeDescr(t, "__objclass__", NewGetSetDescr("__objclass__", descrObjclassGetter, nil))
	SetTypeDescr(t, "__qualname__", NewGetSetDescr("__qualname__", descrQualnameGetter, nil))
	// CPython: Objects/descrobject.c:642 descr_members ml_doc → __doc__
	SetTypeDescr(t, "__doc__", NewGetSetDescr("__doc__", func(o Object) (Object, error) {
		if d, ok := o.(descrDocer); ok {
			doc := d.Doc()
			if doc != "" {
				return NewStr(doc), nil
			}
		}
		return None(), nil
	}, nil))
}

// descrName reads the bound name from any descriptor type the port
// installs through SetTypeDescr.
type descrNamer interface {
	Name() string
}

// descrOwner reads the owning type. MethodDescr exposes Owner();
// GetSetDescr exposes its owner via the field accessor here.
type descrOwner interface {
	Owner() *Type
}

// descrDocer exposes an optional documentation string for __doc__.
// CPython: Objects/descrobject.c:642 ml_doc member
type descrDocer interface {
	Doc() string
}

// Owner returns the type this getset descriptor is registered on.
func (d *GetSetDescr) Owner() *Type { return d.owner }

func descrNameGetter(owner Object) (Object, error) {
	if n, ok := owner.(descrNamer); ok {
		return NewStr(n.Name()), nil
	}
	return nil, errors.New("AttributeError: __name__")
}

func descrObjclassGetter(owner Object) (Object, error) {
	if o, ok := owner.(descrOwner); ok {
		if t := o.Owner(); t != nil {
			return t, nil
		}
	}
	return nil, errors.New("AttributeError: __objclass__")
}

// descrQualnameGetter returns Owner.__qualname__.Name, matching
// descr_get_qualname (Objects/descrobject.c:144).
func descrQualnameGetter(owner Object) (Object, error) {
	n, hasName := owner.(descrNamer)
	if !hasName {
		return nil, errors.New("AttributeError: __qualname__")
	}
	o, hasOwner := owner.(descrOwner)
	if !hasOwner || o.Owner() == nil {
		return NewStr(n.Name()), nil
	}
	return NewStr(o.Owner().Name + "." + n.Name()), nil
}

// NewGetSetDescr builds a getset descriptor that exposes name on the
// host type. fget is required; fset may be nil for read-only
// descriptors (mirroring CPython's behavior of raising AttributeError
// on assignment when no setter is registered).
//
// CPython: Objects/descrobject.c:1696 PyDescr_NewGetSet
func NewGetSetDescr(name string, fget func(owner Object) (Object, error), fset func(owner Object, value Object) error) *GetSetDescr {
	d := &GetSetDescr{name: name, fget: fget, fset: fset}
	d.init(GetSetDescrType)
	return d
}

// Name returns the attribute name this descriptor binds to.
func (d *GetSetDescr) Name() string {
	return d.name
}

// Doc returns the documentation string for this descriptor, or "".
func (d *GetSetDescr) Doc() string { return d.doc }

// WithDoc attaches a docstring to the descriptor and returns it. Mirrors
// the doc field set by PyGetSetDef rows in CPython.
//
// CPython: Objects/descrobject.c:1696 PyDescr_NewGetSet
func (d *GetSetDescr) WithDoc(doc string) *GetSetDescr {
	d.doc = doc
	return d
}

func getsetDescrRepr(o Object) (string, error) {
	d := o.(*GetSetDescr)
	return "<attribute '" + d.name + "'>", nil
}

// getsetDescrGet calls fget with the owner instance. Accessing the
// descriptor on the class itself (owner==nil) returns the descriptor
// unchanged, matching CPython's descr_check. Py_None is a regular
// instance and must not be confused with the C-level NULL that
// signals class access.
//
// CPython: Objects/descrobject.c:153 getset_get
// CPython: Objects/descrobject.c:115 descr_check
func getsetDescrGet(descr Object, owner Object, _ *Type) (Object, error) {
	d := descr.(*GetSetDescr)
	if owner == nil {
		return descr, nil
	}
	if d.fget == nil {
		return nil, errors.New("AttributeError: unreadable attribute " + d.name)
	}
	return d.fget(owner)
}

// getsetDescrSet calls fset, raising AttributeError when the
// descriptor is read-only (no setter registered).
//
// CPython: Objects/descrobject.c:243 getset_set
func getsetDescrSet(descr Object, owner Object, value Object) error {
	d := descr.(*GetSetDescr)
	if d.fset == nil {
		tname := "?"
		if d.owner != nil {
			tname = d.owner.Name
		}
		if value == nil {
			return fmt.Errorf("AttributeError: attribute '%s' of '%s' objects is not deletable", d.name, tname)
		}
		return fmt.Errorf("AttributeError: attribute '%s' of '%s' objects is not writable", d.name, tname)
	}
	return d.fset(owner, value)
}

// LookupDescriptor walks t's MRO looking for an attribute named
// `name` that implements the descriptor protocol. Returns the
// descriptor object plus the type whose dict supplied it, or
// (nil, nil) when no descriptor is found. The instance attribute
// lookup machinery uses this to decide whether to call DescrGet.
//
// CPython: Objects/typeobject.c:5121 _PyType_Lookup
func LookupDescriptor(t *Type, name string) (Object, *Type) {
	if t == nil {
		return nil, nil
	}
	for _, base := range t.MRO {
		if base == nil {
			continue
		}
		if d := lookupTypeMember(base, name); d != nil {
			return d, base
		}
	}
	return nil, nil
}

// lookupTypeMember is the per-type slot of the MRO walk above. The
// v0.10 baseline only stores descriptors in a side map populated by
// type setup helpers; once the typeobject port wires real type dicts
// (task #276), this routes through tp_dict instead.
//
// CPython: Objects/typeobject.c:5063 type_getattro (dict lookup)
func lookupTypeMember(t *Type, name string) Object {
	if descrs, ok := typeDescrTable[t]; ok {
		if d, ok := descrs[name]; ok {
			return d
		}
	}
	return nil
}

// typeDescrTable holds per-type descriptors registered through
// SetTypeDescr. Lives outside the Type struct to keep type.go small;
// the typeobject port replaces this with a real tp_dict.
//
// CPython: Objects/typeobject.c:1057 type_dict (analog)
var typeDescrTable = map[*Type]map[string]Object{}

// typeDescrOrder records the insertion order of keys in typeDescrTable[t].
// This mirrors the tp_dict insertion order that CPython's dict preserves,
// and is required so that type.__dict__ iterates attributes in definition
// order (e.g. enum members, dataclass fields).
var typeDescrOrder = map[*Type][]string{}

// TypeDescrNames returns the names registered on t through
// SetTypeDescr, walking the MRO and de-duplicating. Used by builtins
// dir() to introspect a class.
func TypeDescrNames(t *Type) []string {
	seen := map[string]struct{}{}
	for _, base := range t.MRO {
		if base == nil {
			continue
		}
		for name := range typeDescrTable[base] {
			seen[name] = struct{}{}
		}
	}
	for name := range typeDescrTable[t] {
		seen[name] = struct{}{}
	}
	out := make([]string, 0, len(seen))
	for name := range seen {
		out = append(out, name)
	}
	return out
}

// SetTypeDescr installs d as the attribute name on t. Used by built-in
// type initialisers to expose properties before the typeobject port
// gives every type a real __dict__. When d is a GetSetDescr without an
// owner, we record t there so that descr.__objclass__ resolves the way
// CPython exposes it via PyMemberDef.
//
// For user types that carry a ClassAttrDict (the live tp_dict mirror),
// the entry is also written there so PEP 695 type alias thunks that
// hold a __classdict__ closure cell always read the current value.
//
// CPython: Objects/typeobject.c:6012 type_add_method
func SetTypeDescr(t *Type, name string, d Object) {
	switch x := d.(type) {
	case *GetSetDescr:
		if x.owner == nil {
			x.owner = t
		}
	case *MemberDescr:
		if x.owner == nil {
			x.owner = t
		}
	case *StaticMethod:
		// type_add_method binds a METH_STATIC builtin to its owning type
		// via PyCFunction_NewEx(meth, (PyObject*)type, NULL); m_self then
		// feeds meth_get__qualname__ so str.maketrans.__qualname__ reads
		// 'str.maketrans'. The METH_STATIC flag keeps __self__ at None.
		//
		// CPython: Objects/typeobject.c:8026 type_add_method (METH_STATIC)
		if bf, ok := x.smCallable.(*BuiltinFunction); ok && bf.Self == nil {
			bf.Self = t
			bf.Conv |= MethStatic
		}
	}
	m, ok := typeDescrTable[t]
	if !ok {
		m = map[string]Object{}
		typeDescrTable[t] = m
	}
	if old, exists := m[name]; exists {
		// Replace: install new value then release old owned reference.
		// CPython: type_setattro -> PyDict_SetItem sets the value before
		// the dict releases the old entry (Objects/dictobject.c:1875).
		m[name] = d
		Incref(d)
		Decref(old)
	} else {
		typeDescrOrder[t] = append(typeDescrOrder[t], name)
		// typeDescrTable takes ownership: Incref so the value survives
		// independent of the class-body ns dict's lifetime. Mirrors
		// CPython's tp_dict (a real dict) holding a counted ref to every
		// stored value.
		//
		// CPython: Objects/typeobject.c:6088 type_setattro -> PyDict_SetItem
		m[name] = d
		Incref(d)
	}
	if t.ClassAttrDict != nil {
		_ = t.ClassAttrDict.SetItem(NewStr(name), d)
	}
	// Mutating tp_dict invalidates every adaptive cache keyed on this
	// type's version tag (LOAD_ATTR_CLASS stamps the value it read).
	// During construction versionTag is still 0 so this is a no-op.
	//
	// CPython: Objects/typeobject.c:6088 type_setattro -> PyType_Modified
	t.InvalidateVersionTag()
}

// TypeOwnDescrs returns the names and values registered directly on
// t (no MRO walk). Iteration order is not stable. Callers must not
// mutate the returned map; use SetTypeDescr / DelTypeDescr instead.
// Mirrors a read of tp_dict for a single class.
//
// CPython: Objects/typeobject.c:1057 type_dict
func TypeOwnDescrs(t *Type) map[string]Object {
	if t == nil {
		return nil
	}
	return typeDescrTable[t]
}

// TypeOwnDescrItems iterates the descriptors registered on t in insertion
// order, calling f(name, value) for each. Used by type.__dict__ to expose
// attributes in definition order, matching CPython's tp_dict behavior.
//
// CPython: Objects/typeobject.c:1057 type_dict
func TypeOwnDescrItems(t *Type, f func(name string, value Object)) {
	if t == nil {
		return
	}
	m := typeDescrTable[t]
	if m == nil {
		return
	}
	for _, name := range typeDescrOrder[t] {
		if v, ok := m[name]; ok {
			f(name, v)
		}
	}
}

// DelTypeDescr removes name from t's own descriptor table. Returns
// true when the entry existed. Mirrors a PyDict_DelItem on tp_dict.
//
// CPython: Objects/typeobject.c:6012 type_add_method (inverse path)
func DelTypeDescr(t *Type, name string) bool {
	m, ok := typeDescrTable[t]
	if !ok {
		return false
	}
	if _, ok := m[name]; !ok {
		return false
	}
	delete(m, name)
	order := typeDescrOrder[t]
	for i, n := range order {
		if n == name {
			typeDescrOrder[t] = append(order[:i], order[i+1:]...)
			break
		}
	}
	// CPython: Objects/typeobject.c:6088 type_setattro -> PyType_Modified
	t.InvalidateVersionTag()
	return true
}
