// Command cjkcodecs_go translates CPython's auto-generated cjkcodecs
// mapping headers into Go data files for codecs/cjkcodecs.
//
// Inputs (any number, processed independently):
//
//	$CPYTHON/Modules/cjkcodecs/mappings_kr.h
//	$CPYTHON/Modules/cjkcodecs/mappings_jp.h
//	$CPYTHON/Modules/cjkcodecs/mappings_cn.h
//	$CPYTHON/Modules/cjkcodecs/mappings_hk.h
//	$CPYTHON/Modules/cjkcodecs/mappings_tw.h
//	$CPYTHON/Modules/cjkcodecs/mappings_jisx0213_pair.h
//
// Output: one Go file per input, written to -outdir. Each output
// holds the same flat data arrays and the same 256-entry dispatch
// tables as the original C header, only re-expressed as Go literals.
// The U/N/M/D macros (UNIINV/NOCHAR/MULTIC/DBCINV) are expanded; the
// __NAME[offset] cursor in the C dispatch table becomes an integer
// offset paired with bottom/top byte bounds.
//
// The runtime in codecs/cjkcodecs reads these tables through dbcsIndex
// and unimIndex structs that mirror dbcs_index / unim_index from
// CPython/Modules/cjkcodecs/cjkcodecs.h:32.
//
// Run with:
//
//	go run ./tools/cjkcodecs_go \
//	  -cpython=$HOME/cpython-314 \
//	  -outdir=codecs/cjkcodecs
//
// CPython: Modules/cjkcodecs/mappings_*.h (auto-generated by genmap_*.py)
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

const (
	uniinv = 0xFFFE
	nochar = 0xFFFF
	multic = 0xFFFE
	dbcinv = 0xFFFD
)

var headers = []string{
	"mappings_kr.h",
	"mappings_jp.h",
	"mappings_cn.h",
	"mappings_hk.h",
	"mappings_tw.h",
	"mappings_jisx0213_pair.h",
}

func main() {
	cpython := flag.String("cpython", "", "path to cpython source tree")
	outdir := flag.String("outdir", "", "output directory under codecs/cjkcodecs")
	flag.Parse()
	if *cpython == "" || *outdir == "" {
		log.Fatal("both -cpython and -outdir required")
	}

	for _, name := range headers {
		in := filepath.Join(*cpython, "Modules", "cjkcodecs", name)
		src, err := os.ReadFile(in)
		if err != nil {
			log.Fatalf("read %s: %v", in, err)
		}
		out := filepath.Join(*outdir, strings.TrimSuffix(name, ".h")+"_gen.go")
		buf := &bytes.Buffer{}
		if err := translate(buf, string(src), strings.TrimSuffix(name, ".h")); err != nil {
			log.Fatalf("translate %s: %v", in, err)
		}
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			// Dump the unformatted output for debugging and bubble up.
			_ = os.WriteFile(out+".raw", buf.Bytes(), 0o644)
			log.Fatalf("gofmt %s: %v (raw written to %s.raw)", out, err, out)
		}
		if err := os.WriteFile(out, formatted, 0o644); err != nil {
			log.Fatalf("write %s: %v", out, err)
		}
		fmt.Printf("wrote %s (%d bytes)\n", out, len(formatted))
	}
}

func translate(w *bytes.Buffer, src, stem string) error {
	src = stripComments(src)
	src = stripCondBlock(src, "JISX0213_ENCPAIRS")

	header := fmt.Sprintf(`// Code generated by tools/cjkcodecs_go. DO NOT EDIT.
// Source: CPython Modules/cjkcodecs/%s.h

package cjkcodecs

`, stem)
	w.WriteString(header)

	// JISX0213_ENCPAIRS constant from mappings_jisx0213_pair.h.
	if c := findConst(src, "JISX0213_ENCPAIRS"); c != "" {
		fmt.Fprintf(w, "const JISX0213_ENCPAIRS = %s\n\n", c)
	}

	defs := parseDefs(src)

	// Emit flat data arrays first so dispatch arrays can reference them.
	for _, d := range defs {
		if d.kind == defFlat {
			if err := emitFlat(w, d); err != nil {
				return err
			}
		}
	}
	for _, d := range defs {
		switch d.kind {
		case defDBCSIndex:
			if err := emitDBCS(w, d); err != nil {
				return err
			}
		case defWideDBCSIndex:
			if err := emitWideDBCS(w, d); err != nil {
				return err
			}
		case defUnimIndex:
			if err := emitUnim(w, d); err != nil {
				return err
			}
		case defPairEnc:
			if err := emitPairEnc(w, d); err != nil {
				return err
			}
		}
	}
	return nil
}

type defKind int

const (
	defFlat defKind = iota
	defDBCSIndex
	defWideDBCSIndex
	defUnimIndex
	defPairEnc
)

type definition struct {
	kind     defKind
	name     string // identifier as it appears in C (without leading __ for flats)
	elemType string // "ucs2_t" | "DBCHAR" | "Py_UCS4" | "" for dispatch arrays
	flatLen  int    // declared array length
	body     string // raw body between the outer { }
}

var (
	reFlat       = regexp.MustCompile(`(?s)static\s+const\s+(ucs2_t|DBCHAR|Py_UCS4)\s+__(\w+)\s*\[(\d+)\]\s*=\s*\{(.*?)\};`)
	reDBCS       = regexp.MustCompile(`(?s)static\s+const\s+struct\s+dbcs_index\s+(\w+)\s*\[256\]\s*=\s*\{(.*?)\};`)
	reWideDBCS   = regexp.MustCompile(`(?s)static\s+const\s+struct\s+widedbcs_index\s+(\w+)\s*\[256\]\s*=\s*\{(.*?)\};`)
	reUnim       = regexp.MustCompile(`(?s)static\s+const\s+struct\s+unim_index\s+(\w+)\s*\[256\]\s*=\s*\{(.*?)\};`)
	rePairEnc    = regexp.MustCompile(`(?s)static\s+const\s+struct\s+pair_encodemap\s+(\w+)\s*\[\w+\]\s*=\s*\{(.*?)\};`)
	reConstMacro = regexp.MustCompile(`#define\s+(\w+)\s+(\d+)`)
)

func parseDefs(src string) []definition {
	var defs []definition
	for _, m := range reFlat.FindAllStringSubmatchIndex(src, -1) {
		defs = append(defs, definition{
			kind:     defFlat,
			elemType: src[m[2]:m[3]],
			name:     src[m[4]:m[5]],
			flatLen:  mustAtoi(src[m[6]:m[7]]),
			body:     src[m[8]:m[9]],
		})
	}
	for _, m := range reDBCS.FindAllStringSubmatchIndex(src, -1) {
		defs = append(defs, definition{
			kind: defDBCSIndex,
			name: src[m[2]:m[3]],
			body: src[m[4]:m[5]],
		})
	}
	for _, m := range reWideDBCS.FindAllStringSubmatchIndex(src, -1) {
		defs = append(defs, definition{
			kind: defWideDBCSIndex,
			name: src[m[2]:m[3]],
			body: src[m[4]:m[5]],
		})
	}
	for _, m := range reUnim.FindAllStringSubmatchIndex(src, -1) {
		defs = append(defs, definition{
			kind: defUnimIndex,
			name: src[m[2]:m[3]],
			body: src[m[4]:m[5]],
		})
	}
	for _, m := range rePairEnc.FindAllStringSubmatchIndex(src, -1) {
		defs = append(defs, definition{
			kind: defPairEnc,
			name: src[m[2]:m[3]],
			body: src[m[4]:m[5]],
		})
	}
	return defs
}

func emitFlat(w *bytes.Buffer, d definition) error {
	goType := ""
	switch d.elemType {
	case "ucs2_t", "DBCHAR":
		goType = "uint16"
	case "Py_UCS4":
		goType = "uint32"
	default:
		return fmt.Errorf("unknown flat element type %q for %s", d.elemType, d.name)
	}
	tokens := splitValues(d.body)
	if len(tokens) != d.flatLen {
		return fmt.Errorf("%s: declared len=%d but parsed %d values", d.name, d.flatLen, len(tokens))
	}
	fmt.Fprintf(w, "var _%s_flat = [%d]%s{\n", d.name, d.flatLen, goType)
	for i, t := range tokens {
		v, err := evalNum(t)
		if err != nil {
			return fmt.Errorf("%s[%d]: %w", d.name, i, err)
		}
		fmt.Fprintf(w, "0x%x,", v)
		if i%12 == 11 {
			fmt.Fprintln(w)
		}
	}
	fmt.Fprintln(w, "\n}")
	fmt.Fprintln(w)
	return nil
}

var reTriple = regexp.MustCompile(`\{\s*([^,}]+?)\s*,\s*([^,}]+?)\s*,\s*([^,}]+?)\s*\}`)

func emitDBCS(w *bytes.Buffer, d definition) error {
	rows, err := parseDispatch(d.body, d.name, "ucs2_t")
	if err != nil {
		return err
	}
	fmt.Fprintf(w, "var %s = [256]dbcsIndex{\n", d.name)
	for _, r := range rows {
		if r.empty {
			fmt.Fprint(w, "{},\n")
			continue
		}
		fmt.Fprintf(w, "{Map: _%s_flat[%d:], Bottom: %d, Top: %d},\n",
			r.flat, r.offset, r.bottom, r.top)
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
	return nil
}

func emitWideDBCS(w *bytes.Buffer, d definition) error {
	rows, err := parseDispatch(d.body, d.name, "Py_UCS4")
	if err != nil {
		return err
	}
	fmt.Fprintf(w, "var %s = [256]wideDBCSIndex{\n", d.name)
	for _, r := range rows {
		if r.empty {
			fmt.Fprint(w, "{},\n")
			continue
		}
		fmt.Fprintf(w, "{Map: _%s_flat[%d:], Bottom: %d, Top: %d},\n",
			r.flat, r.offset, r.bottom, r.top)
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
	return nil
}

func emitUnim(w *bytes.Buffer, d definition) error {
	rows, err := parseDispatch(d.body, d.name, "DBCHAR")
	if err != nil {
		return err
	}
	fmt.Fprintf(w, "var %s = [256]unimIndex{\n", d.name)
	for _, r := range rows {
		if r.empty {
			fmt.Fprint(w, "{},\n")
			continue
		}
		fmt.Fprintf(w, "{Map: _%s_flat[%d:], Bottom: %d, Top: %d},\n",
			r.flat, r.offset, r.bottom, r.top)
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
	return nil
}

func emitPairEnc(w *bytes.Buffer, d definition) error {
	// {0x...,0x...},{...} — already flat tuples.
	pairs := splitTuples(d.body)
	fmt.Fprintf(w, "var %s = [...]pairEncodeMap{\n", d.name)
	for _, p := range pairs {
		fields := splitValues(p)
		if len(fields) != 2 {
			return fmt.Errorf("%s pair has %d fields, want 2: %q", d.name, len(fields), p)
		}
		uni, err := evalNum(fields[0])
		if err != nil {
			return err
		}
		code, err := evalNum(fields[1])
		if err != nil {
			return err
		}
		fmt.Fprintf(w, "{UniSeq: 0x%x, Code: 0x%x},\n", uni, code)
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
	return nil
}

type dispatchRow struct {
	empty       bool
	flat        string
	offset      int
	bottom, top int
}

var reWS = regexp.MustCompile(`\s+`)

func parseDispatch(body, refname, _ string) ([]dispatchRow, error) {
	rows := make([]dispatchRow, 0, 256)
	for _, m := range reTriple.FindAllStringSubmatch(body, -1) {
		f0 := reWS.ReplaceAllString(m[1], "")
		bot := reWS.ReplaceAllString(m[2], "")
		top := reWS.ReplaceAllString(m[3], "")
		if f0 == "0" && bot == "0" && top == "0" {
			rows = append(rows, dispatchRow{empty: true})
			continue
		}
		// f0 like "__cp949_encmap+12345" or "__name+0"
		idx := strings.Index(f0, "+")
		var flat string
		var off int
		if idx == -1 {
			if !strings.HasPrefix(f0, "__") {
				return nil, fmt.Errorf("unexpected flat ref %q", f0)
			}
			flat = f0[2:]
			off = 0
		} else {
			lhs := f0[:idx]
			if !strings.HasPrefix(lhs, "__") {
				return nil, fmt.Errorf("unexpected flat ref %q", f0)
			}
			flat = lhs[2:]
			n, err := strconv.Atoi(strings.TrimSpace(f0[idx+1:]))
			if err != nil {
				return nil, fmt.Errorf("offset parse %q: %w", f0, err)
			}
			off = n
		}
		b, err := strconv.Atoi(bot)
		if err != nil {
			return nil, fmt.Errorf("bottom parse %q: %w", bot, err)
		}
		t, err := strconv.Atoi(top)
		if err != nil {
			return nil, fmt.Errorf("top parse %q: %w", top, err)
		}
		rows = append(rows, dispatchRow{flat: flat, offset: off, bottom: b, top: t})
	}
	if len(rows) != 256 {
		return nil, fmt.Errorf("%s dispatch has %d rows, want 256", refname, len(rows))
	}
	return rows, nil
}

func splitValues(body string) []string {
	body = strings.TrimSpace(body)
	parts := strings.Split(body, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		out = append(out, p)
	}
	return out
}

// splitTuples extracts substrings inside each top-level {...} pair.
func splitTuples(body string) []string {
	var out []string
	depth := 0
	start := -1
	for i, c := range body {
		switch c {
		case '{':
			if depth == 0 {
				start = i + 1
			}
			depth++
		case '}':
			depth--
			if depth == 0 && start >= 0 {
				out = append(out, body[start:i])
				start = -1
			}
		}
	}
	return out
}

func evalNum(s string) (uint64, error) {
	s = strings.TrimSpace(s)
	switch s {
	case "U":
		return uniinv, nil
	case "N":
		return nochar, nil
	case "M":
		return multic, nil
	case "D":
		return dbcinv, nil
	}
	// Plain integer (decimal or 0x...).
	if strings.HasPrefix(s, "0x") || strings.HasPrefix(s, "0X") {
		v, err := strconv.ParseUint(s[2:], 16, 64)
		return v, err
	}
	v, err := strconv.ParseUint(s, 10, 64)
	return v, err
}

func mustAtoi(s string) int {
	n, err := strconv.Atoi(s)
	if err != nil {
		log.Fatalf("atoi %q: %v", s, err)
	}
	return n
}

func stripComments(src string) string {
	// strip // line comments
	var out strings.Builder
	i := 0
	for i < len(src) {
		if i+1 < len(src) && src[i] == '/' && src[i+1] == '/' {
			j := i
			for j < len(src) && src[j] != '\n' {
				j++
			}
			i = j
			continue
		}
		if i+1 < len(src) && src[i] == '/' && src[i+1] == '*' {
			j := i + 2
			for j+1 < len(src) && !(src[j] == '*' && src[j+1] == '/') {
				j++
			}
			i = j + 2
			continue
		}
		out.WriteByte(src[i])
		i++
	}
	return out.String()
}

// stripCondBlock removes #ifdef <sentinel> ... #else ... #endif and keeps the
// #else branch. This is what mappings_jisx0213_pair.h needs: the #ifdef branch
// uses extern declarations the runtime never sees.
func stripCondBlock(src, sentinel string) string {
	startTag := "#ifdef " + sentinel
	idx := strings.Index(src, startTag)
	if idx < 0 {
		return src
	}
	elseIdx := strings.Index(src[idx:], "#else")
	endIdx := strings.Index(src[idx:], "#endif")
	if elseIdx < 0 || endIdx < 0 {
		return src
	}
	body := src[idx+elseIdx+len("#else") : idx+endIdx]
	return src[:idx] + body + src[idx+endIdx+len("#endif"):]
}

func findConst(src, name string) string {
	for _, m := range reConstMacro.FindAllStringSubmatch(src, -1) {
		if m[1] == name {
			return m[2]
		}
	}
	return ""
}
