// Code generated by tools/parser_gen from cpython/Grammar/python.gram. DO NOT EDIT.
//
// CPython: Grammar/python.gram

package pegen

import "errors"

// ErrParserNotImplemented is returned by Dispatch while the
// per-rule emitter is offline. Callers detect this sentinel
// and route through the fixture-driven path until the real
// rule bodies land.
var ErrParserNotImplemented = errors.New("pegen: generated rule bodies not yet emitted")

// Generated rule ids. The values are dense small ints in
// declaration order; they are stable across regenerations
// only as long as python.gram does not insert or reorder
// rules. The pegen runtime keys the memo cache on these.
const (
	Rule_void = 0
	Rule_file = 1
	Rule_interactive = 2
	Rule_eval = 3
	Rule_func_type = 4
	Rule_statements = 5
	Rule_statement = 6
	Rule_single_compound_stmt = 7
	Rule_statement_newline = 8
	Rule_simple_stmts = 9
	Rule_simple_stmt = 10
	Rule_compound_stmt = 11
	Rule_assignment = 12
	Rule_annotated_rhs = 13
	Rule_augassign = 14
	Rule_return_stmt = 15
	Rule_raise_stmt = 16
	Rule_pass_stmt = 17
	Rule_break_stmt = 18
	Rule_continue_stmt = 19
	Rule_global_stmt = 20
	Rule_nonlocal_stmt = 21
	Rule_del_stmt = 22
	Rule_yield_stmt = 23
	Rule_assert_stmt = 24
	Rule_import_stmt = 25
	Rule_import_name = 26
	Rule_import_from = 27
	Rule_import_from_targets = 28
	Rule_import_from_as_names = 29
	Rule_import_from_as_name = 30
	Rule_dotted_as_names = 31
	Rule_dotted_as_name = 32
	Rule_dotted_name = 33
	Rule_block = 34
	Rule_decorators = 35
	Rule_class_def = 36
	Rule_class_def_raw = 37
	Rule_function_def = 38
	Rule_function_def_raw = 39
	Rule_params = 40
	Rule_parameters = 41
	Rule_slash_no_default = 42
	Rule_slash_with_default = 43
	Rule_star_etc = 44
	Rule_kwds = 45
	Rule_param_no_default = 46
	Rule_param_no_default_star_annotation = 47
	Rule_param_with_default = 48
	Rule_param_maybe_default = 49
	Rule_param = 50
	Rule_param_star_annotation = 51
	Rule_annotation = 52
	Rule_star_annotation = 53
	Rule_default = 54
	Rule_if_stmt = 55
	Rule_elif_stmt = 56
	Rule_else_block = 57
	Rule_while_stmt = 58
	Rule_for_stmt = 59
	Rule_with_stmt = 60
	Rule_with_item = 61
	Rule_try_stmt = 62
	Rule_except_block = 63
	Rule_except_star_block = 64
	Rule_finally_block = 65
	Rule_match_stmt = 66
	Rule_subject_expr = 67
	Rule_case_block = 68
	Rule_guard = 69
	Rule_patterns = 70
	Rule_pattern = 71
	Rule_as_pattern = 72
	Rule_or_pattern = 73
	Rule_closed_pattern = 74
	Rule_literal_pattern = 75
	Rule_literal_expr = 76
	Rule_complex_number = 77
	Rule_signed_number = 78
	Rule_signed_real_number = 79
	Rule_real_number = 80
	Rule_imaginary_number = 81
	Rule_capture_pattern = 82
	Rule_pattern_capture_target = 83
	Rule_wildcard_pattern = 84
	Rule_value_pattern = 85
	Rule_attr = 86
	Rule_name_or_attr = 87
	Rule_group_pattern = 88
	Rule_sequence_pattern = 89
	Rule_open_sequence_pattern = 90
	Rule_maybe_sequence_pattern = 91
	Rule_maybe_star_pattern = 92
	Rule_star_pattern = 93
	Rule_mapping_pattern = 94
	Rule_items_pattern = 95
	Rule_key_value_pattern = 96
	Rule_double_star_pattern = 97
	Rule_class_pattern = 98
	Rule_positional_patterns = 99
	Rule_keyword_patterns = 100
	Rule_keyword_pattern = 101
	Rule_type_alias = 102
	Rule_type_params = 103
	Rule_type_param_seq = 104
	Rule_type_param = 105
	Rule_type_param_bound = 106
	Rule_type_param_default = 107
	Rule_type_param_starred_default = 108
	Rule_expressions = 109
	Rule_expression = 110
	Rule_yield_expr = 111
	Rule_star_expressions = 112
	Rule_star_expression = 113
	Rule_star_named_expressions = 114
	Rule_star_named_expression = 115
	Rule_assignment_expression = 116
	Rule_named_expression = 117
	Rule_disjunction = 118
	Rule_conjunction = 119
	Rule_inversion = 120
	Rule_comparison = 121
	Rule_compare_op_bitwise_or_pair = 122
	Rule_eq_bitwise_or = 123
	Rule_noteq_bitwise_or = 124
	Rule_lte_bitwise_or = 125
	Rule_lt_bitwise_or = 126
	Rule_gte_bitwise_or = 127
	Rule_gt_bitwise_or = 128
	Rule_notin_bitwise_or = 129
	Rule_in_bitwise_or = 130
	Rule_isnot_bitwise_or = 131
	Rule_is_bitwise_or = 132
	Rule_bitwise_or = 133
	Rule_bitwise_xor = 134
	Rule_bitwise_and = 135
	Rule_shift_expr = 136
	Rule_sum = 137
	Rule_term = 138
	Rule_factor = 139
	Rule_power = 140
	Rule_await_primary = 141
	Rule_primary = 142
	Rule_slices = 143
	Rule_slice = 144
	Rule_atom = 145
	Rule_group = 146
	Rule_lambdef = 147
	Rule_lambda_params = 148
	Rule_lambda_parameters = 149
	Rule_lambda_slash_no_default = 150
	Rule_lambda_slash_with_default = 151
	Rule_lambda_star_etc = 152
	Rule_lambda_kwds = 153
	Rule_lambda_param_no_default = 154
	Rule_lambda_param_with_default = 155
	Rule_lambda_param_maybe_default = 156
	Rule_lambda_param = 157
	Rule_fstring_middle = 158
	Rule_fstring_replacement_field = 159
	Rule_fstring_conversion = 160
	Rule_fstring_full_format_spec = 161
	Rule_fstring_format_spec = 162
	Rule_fstring = 163
	Rule_tstring_format_spec_replacement_field = 164
	Rule_tstring_format_spec = 165
	Rule_tstring_full_format_spec = 166
	Rule_tstring_replacement_field = 167
	Rule_tstring_middle = 168
	Rule_tstring = 169
	Rule_string = 170
	Rule_strings = 171
	Rule_list = 172
	Rule_tuple = 173
	Rule_set = 174
	Rule_dict = 175
	Rule_double_starred_kvpairs = 176
	Rule_double_starred_kvpair = 177
	Rule_kvpair = 178
	Rule_for_if_clauses = 179
	Rule_for_if_clause = 180
	Rule_listcomp = 181
	Rule_setcomp = 182
	Rule_genexp = 183
	Rule_dictcomp = 184
	Rule_arguments = 185
	Rule_args = 186
	Rule_kwargs = 187
	Rule_starred_expression = 188
	Rule_kwarg_or_starred = 189
	Rule_kwarg_or_double_starred = 190
	Rule_star_targets = 191
	Rule_star_targets_list_seq = 192
	Rule_star_targets_tuple_seq = 193
	Rule_star_target = 194
	Rule_target_with_star_atom = 195
	Rule_star_atom = 196
	Rule_single_target = 197
	Rule_single_subscript_attribute_target = 198
	Rule_t_primary = 199
	Rule_t_lookahead = 200
	Rule_del_targets = 201
	Rule_del_target = 202
	Rule_del_t_atom = 203
	Rule_type_expressions = 204
	Rule_func_type_comment = 205
	Rule_invalid_arguments = 206
	Rule_invalid_kwarg = 207
	Rule_expression_without_invalid = 208
	Rule_invalid_legacy_expression = 209
	Rule_invalid_type_param = 210
	Rule_invalid_expression = 211
	Rule_invalid_assignment = 212
	Rule_invalid_ann_assign_target = 213
	Rule_invalid_del_stmt = 214
	Rule_invalid_block = 215
	Rule_invalid_comprehension = 216
	Rule_invalid_dict_comprehension = 217
	Rule_invalid_parameters = 218
	Rule_invalid_default = 219
	Rule_invalid_star_etc = 220
	Rule_invalid_kwds = 221
	Rule_invalid_parameters_helper = 222
	Rule_invalid_lambda_parameters = 223
	Rule_invalid_lambda_parameters_helper = 224
	Rule_invalid_lambda_star_etc = 225
	Rule_invalid_lambda_kwds = 226
	Rule_invalid_double_type_comments = 227
	Rule_invalid_with_item = 228
	Rule_invalid_for_if_clause = 229
	Rule_invalid_for_target = 230
	Rule_invalid_group = 231
	Rule_invalid_import = 232
	Rule_invalid_dotted_as_name = 233
	Rule_invalid_import_from_as_name = 234
	Rule_invalid_import_from_targets = 235
	Rule_invalid_with_stmt = 236
	Rule_invalid_with_stmt_indent = 237
	Rule_invalid_try_stmt = 238
	Rule_invalid_except_stmt = 239
	Rule_invalid_except_star_stmt = 240
	Rule_invalid_finally_stmt = 241
	Rule_invalid_except_stmt_indent = 242
	Rule_invalid_except_star_stmt_indent = 243
	Rule_invalid_match_stmt = 244
	Rule_invalid_case_block = 245
	Rule_invalid_as_pattern = 246
	Rule_invalid_class_pattern = 247
	Rule_invalid_class_argument_pattern = 248
	Rule_invalid_if_stmt = 249
	Rule_invalid_elif_stmt = 250
	Rule_invalid_else_stmt = 251
	Rule_invalid_while_stmt = 252
	Rule_invalid_for_stmt = 253
	Rule_invalid_def_raw = 254
	Rule_invalid_class_def_raw = 255
	Rule_invalid_double_starred_kvpairs = 256
	Rule_invalid_kvpair = 257
	Rule_invalid_starred_expression_unpacking = 258
	Rule_invalid_starred_expression = 259
	Rule_invalid_fstring_replacement_field = 260
	Rule_invalid_fstring_conversion_character = 261
	Rule_invalid_tstring_replacement_field = 262
	Rule_invalid_tstring_conversion_character = 263
	Rule_invalid_string_tstring_concat = 264
	Rule_invalid_arithmetic = 265
	Rule_invalid_factor = 266
	Rule_invalid_type_params = 267
)

// GeneratedRuleNames is the parallel name table. Index
// by Rule_<name>. Used by debug logging and by the
// generator round-trip checksum test.
var GeneratedRuleNames = []string{
	"void",
	"file",
	"interactive",
	"eval",
	"func_type",
	"statements",
	"statement",
	"single_compound_stmt",
	"statement_newline",
	"simple_stmts",
	"simple_stmt",
	"compound_stmt",
	"assignment",
	"annotated_rhs",
	"augassign",
	"return_stmt",
	"raise_stmt",
	"pass_stmt",
	"break_stmt",
	"continue_stmt",
	"global_stmt",
	"nonlocal_stmt",
	"del_stmt",
	"yield_stmt",
	"assert_stmt",
	"import_stmt",
	"import_name",
	"import_from",
	"import_from_targets",
	"import_from_as_names",
	"import_from_as_name",
	"dotted_as_names",
	"dotted_as_name",
	"dotted_name",
	"block",
	"decorators",
	"class_def",
	"class_def_raw",
	"function_def",
	"function_def_raw",
	"params",
	"parameters",
	"slash_no_default",
	"slash_with_default",
	"star_etc",
	"kwds",
	"param_no_default",
	"param_no_default_star_annotation",
	"param_with_default",
	"param_maybe_default",
	"param",
	"param_star_annotation",
	"annotation",
	"star_annotation",
	"default",
	"if_stmt",
	"elif_stmt",
	"else_block",
	"while_stmt",
	"for_stmt",
	"with_stmt",
	"with_item",
	"try_stmt",
	"except_block",
	"except_star_block",
	"finally_block",
	"match_stmt",
	"subject_expr",
	"case_block",
	"guard",
	"patterns",
	"pattern",
	"as_pattern",
	"or_pattern",
	"closed_pattern",
	"literal_pattern",
	"literal_expr",
	"complex_number",
	"signed_number",
	"signed_real_number",
	"real_number",
	"imaginary_number",
	"capture_pattern",
	"pattern_capture_target",
	"wildcard_pattern",
	"value_pattern",
	"attr",
	"name_or_attr",
	"group_pattern",
	"sequence_pattern",
	"open_sequence_pattern",
	"maybe_sequence_pattern",
	"maybe_star_pattern",
	"star_pattern",
	"mapping_pattern",
	"items_pattern",
	"key_value_pattern",
	"double_star_pattern",
	"class_pattern",
	"positional_patterns",
	"keyword_patterns",
	"keyword_pattern",
	"type_alias",
	"type_params",
	"type_param_seq",
	"type_param",
	"type_param_bound",
	"type_param_default",
	"type_param_starred_default",
	"expressions",
	"expression",
	"yield_expr",
	"star_expressions",
	"star_expression",
	"star_named_expressions",
	"star_named_expression",
	"assignment_expression",
	"named_expression",
	"disjunction",
	"conjunction",
	"inversion",
	"comparison",
	"compare_op_bitwise_or_pair",
	"eq_bitwise_or",
	"noteq_bitwise_or",
	"lte_bitwise_or",
	"lt_bitwise_or",
	"gte_bitwise_or",
	"gt_bitwise_or",
	"notin_bitwise_or",
	"in_bitwise_or",
	"isnot_bitwise_or",
	"is_bitwise_or",
	"bitwise_or",
	"bitwise_xor",
	"bitwise_and",
	"shift_expr",
	"sum",
	"term",
	"factor",
	"power",
	"await_primary",
	"primary",
	"slices",
	"slice",
	"atom",
	"group",
	"lambdef",
	"lambda_params",
	"lambda_parameters",
	"lambda_slash_no_default",
	"lambda_slash_with_default",
	"lambda_star_etc",
	"lambda_kwds",
	"lambda_param_no_default",
	"lambda_param_with_default",
	"lambda_param_maybe_default",
	"lambda_param",
	"fstring_middle",
	"fstring_replacement_field",
	"fstring_conversion",
	"fstring_full_format_spec",
	"fstring_format_spec",
	"fstring",
	"tstring_format_spec_replacement_field",
	"tstring_format_spec",
	"tstring_full_format_spec",
	"tstring_replacement_field",
	"tstring_middle",
	"tstring",
	"string",
	"strings",
	"list",
	"tuple",
	"set",
	"dict",
	"double_starred_kvpairs",
	"double_starred_kvpair",
	"kvpair",
	"for_if_clauses",
	"for_if_clause",
	"listcomp",
	"setcomp",
	"genexp",
	"dictcomp",
	"arguments",
	"args",
	"kwargs",
	"starred_expression",
	"kwarg_or_starred",
	"kwarg_or_double_starred",
	"star_targets",
	"star_targets_list_seq",
	"star_targets_tuple_seq",
	"star_target",
	"target_with_star_atom",
	"star_atom",
	"single_target",
	"single_subscript_attribute_target",
	"t_primary",
	"t_lookahead",
	"del_targets",
	"del_target",
	"del_t_atom",
	"type_expressions",
	"func_type_comment",
	"invalid_arguments",
	"invalid_kwarg",
	"expression_without_invalid",
	"invalid_legacy_expression",
	"invalid_type_param",
	"invalid_expression",
	"invalid_assignment",
	"invalid_ann_assign_target",
	"invalid_del_stmt",
	"invalid_block",
	"invalid_comprehension",
	"invalid_dict_comprehension",
	"invalid_parameters",
	"invalid_default",
	"invalid_star_etc",
	"invalid_kwds",
	"invalid_parameters_helper",
	"invalid_lambda_parameters",
	"invalid_lambda_parameters_helper",
	"invalid_lambda_star_etc",
	"invalid_lambda_kwds",
	"invalid_double_type_comments",
	"invalid_with_item",
	"invalid_for_if_clause",
	"invalid_for_target",
	"invalid_group",
	"invalid_import",
	"invalid_dotted_as_name",
	"invalid_import_from_as_name",
	"invalid_import_from_targets",
	"invalid_with_stmt",
	"invalid_with_stmt_indent",
	"invalid_try_stmt",
	"invalid_except_stmt",
	"invalid_except_star_stmt",
	"invalid_finally_stmt",
	"invalid_except_stmt_indent",
	"invalid_except_star_stmt_indent",
	"invalid_match_stmt",
	"invalid_case_block",
	"invalid_as_pattern",
	"invalid_class_pattern",
	"invalid_class_argument_pattern",
	"invalid_if_stmt",
	"invalid_elif_stmt",
	"invalid_else_stmt",
	"invalid_while_stmt",
	"invalid_for_stmt",
	"invalid_def_raw",
	"invalid_class_def_raw",
	"invalid_double_starred_kvpairs",
	"invalid_kvpair",
	"invalid_starred_expression_unpacking",
	"invalid_starred_expression",
	"invalid_fstring_replacement_field",
	"invalid_fstring_conversion_character",
	"invalid_tstring_replacement_field",
	"invalid_tstring_conversion_character",
	"invalid_string_tstring_concat",
	"invalid_arithmetic",
	"invalid_factor",
	"invalid_type_params",
}

// Dispatch is the entry point the top-level Parse driver
// calls. It picks the rule for m and invokes the
// generated body. While the emitter is offline this
// returns ErrParserNotImplemented for every mode.
//
// CPython: Parser/parser.c entry-point dispatch
func Dispatch(p *Parser, m StartRule) (any, error) {
	_ = p
	_ = m
	return nil, ErrParserNotImplemented
}
