// Code generated by tools/opcodes_go. DO NOT EDIT.
// Source: cpython/Lib/_opcode_metadata.py + cpython/Include/internal/pycore_opcode_metadata.h

package compile

// Opcode flag bits. Mirror HAS_*_FLAG in pycore_opcode_metadata.h.
const (
	flagArg         = 1 << 0
	flagConst       = 1 << 1
	flagName        = 1 << 2
	flagJump        = 1 << 3
	flagFree        = 1 << 4
	flagLocal       = 1 << 5
	flagEvalBreak   = 1 << 6
	flagDeopt       = 1 << 7
	flagError       = 1 << 8
	flagEscapes     = 1 << 9
	flagExit        = 1 << 10
	flagPure        = 1 << 11
	flagPassthrough = 1 << 12
	flagOpargAnd1   = 1 << 13
	flagErrorNoPop  = 1 << 14
	flagNoSaveIP    = 1 << 15
)

// Opcode constants. Numeric values match cpython 3.14 opmap.
const (
	CACHE                             Opcode = 0
	BINARY_SLICE                      Opcode = 1
	BUILD_TEMPLATE                    Opcode = 2
	CALL_FUNCTION_EX                  Opcode = 4
	CHECK_EG_MATCH                    Opcode = 5
	CHECK_EXC_MATCH                   Opcode = 6
	CLEANUP_THROW                     Opcode = 7
	DELETE_SUBSCR                     Opcode = 8
	END_FOR                           Opcode = 9
	END_SEND                          Opcode = 10
	EXIT_INIT_CHECK                   Opcode = 11
	FORMAT_SIMPLE                     Opcode = 12
	FORMAT_WITH_SPEC                  Opcode = 13
	GET_AITER                         Opcode = 14
	GET_ANEXT                         Opcode = 15
	GET_ITER                          Opcode = 16
	RESERVED                          Opcode = 17
	GET_LEN                           Opcode = 18
	GET_YIELD_FROM_ITER               Opcode = 19
	INTERPRETER_EXIT                  Opcode = 20
	LOAD_BUILD_CLASS                  Opcode = 21
	LOAD_LOCALS                       Opcode = 22
	MAKE_FUNCTION                     Opcode = 23
	MATCH_KEYS                        Opcode = 24
	MATCH_MAPPING                     Opcode = 25
	MATCH_SEQUENCE                    Opcode = 26
	NOP                               Opcode = 27
	NOT_TAKEN                         Opcode = 28
	POP_EXCEPT                        Opcode = 29
	POP_ITER                          Opcode = 30
	POP_TOP                           Opcode = 31
	PUSH_EXC_INFO                     Opcode = 32
	PUSH_NULL                         Opcode = 33
	RETURN_GENERATOR                  Opcode = 34
	RETURN_VALUE                      Opcode = 35
	SETUP_ANNOTATIONS                 Opcode = 36
	STORE_SLICE                       Opcode = 37
	STORE_SUBSCR                      Opcode = 38
	TO_BOOL                           Opcode = 39
	UNARY_INVERT                      Opcode = 40
	UNARY_NEGATIVE                    Opcode = 41
	UNARY_NOT                         Opcode = 42
	WITH_EXCEPT_START                 Opcode = 43
	BINARY_OP                         Opcode = 44
	BUILD_INTERPOLATION               Opcode = 45
	BUILD_LIST                        Opcode = 46
	BUILD_MAP                         Opcode = 47
	BUILD_SET                         Opcode = 48
	BUILD_SLICE                       Opcode = 49
	BUILD_STRING                      Opcode = 50
	BUILD_TUPLE                       Opcode = 51
	CALL                              Opcode = 52
	CALL_INTRINSIC_1                  Opcode = 53
	CALL_INTRINSIC_2                  Opcode = 54
	CALL_KW                           Opcode = 55
	COMPARE_OP                        Opcode = 56
	CONTAINS_OP                       Opcode = 57
	CONVERT_VALUE                     Opcode = 58
	COPY                              Opcode = 59
	COPY_FREE_VARS                    Opcode = 60
	DELETE_ATTR                       Opcode = 61
	DELETE_DEREF                      Opcode = 62
	DELETE_FAST                       Opcode = 63
	DELETE_GLOBAL                     Opcode = 64
	DELETE_NAME                       Opcode = 65
	DICT_MERGE                        Opcode = 66
	DICT_UPDATE                       Opcode = 67
	END_ASYNC_FOR                     Opcode = 68
	EXTENDED_ARG                      Opcode = 69
	FOR_ITER                          Opcode = 70
	GET_AWAITABLE                     Opcode = 71
	IMPORT_FROM                       Opcode = 72
	IMPORT_NAME                       Opcode = 73
	IS_OP                             Opcode = 74
	JUMP_BACKWARD                     Opcode = 75
	JUMP_BACKWARD_NO_INTERRUPT        Opcode = 76
	JUMP_FORWARD                      Opcode = 77
	LIST_APPEND                       Opcode = 78
	LIST_EXTEND                       Opcode = 79
	LOAD_ATTR                         Opcode = 80
	LOAD_COMMON_CONSTANT              Opcode = 81
	LOAD_CONST                        Opcode = 82
	LOAD_DEREF                        Opcode = 83
	LOAD_FAST                         Opcode = 84
	LOAD_FAST_AND_CLEAR               Opcode = 85
	LOAD_FAST_BORROW                  Opcode = 86
	LOAD_FAST_BORROW_LOAD_FAST_BORROW Opcode = 87
	LOAD_FAST_CHECK                   Opcode = 88
	LOAD_FAST_LOAD_FAST               Opcode = 89
	LOAD_FROM_DICT_OR_DEREF           Opcode = 90
	LOAD_FROM_DICT_OR_GLOBALS         Opcode = 91
	LOAD_GLOBAL                       Opcode = 92
	LOAD_NAME                         Opcode = 93
	LOAD_SMALL_INT                    Opcode = 94
	LOAD_SPECIAL                      Opcode = 95
	LOAD_SUPER_ATTR                   Opcode = 96
	MAKE_CELL                         Opcode = 97
	MAP_ADD                           Opcode = 98
	MATCH_CLASS                       Opcode = 99
	POP_JUMP_IF_FALSE                 Opcode = 100
	POP_JUMP_IF_NONE                  Opcode = 101
	POP_JUMP_IF_NOT_NONE              Opcode = 102
	POP_JUMP_IF_TRUE                  Opcode = 103
	RAISE_VARARGS                     Opcode = 104
	RERAISE                           Opcode = 105
	SEND                              Opcode = 106
	SET_ADD                           Opcode = 107
	SET_FUNCTION_ATTRIBUTE            Opcode = 108
	SET_UPDATE                        Opcode = 109
	STORE_ATTR                        Opcode = 110
	STORE_DEREF                       Opcode = 111
	STORE_FAST                        Opcode = 112
	STORE_FAST_LOAD_FAST              Opcode = 113
	STORE_FAST_STORE_FAST             Opcode = 114
	STORE_GLOBAL                      Opcode = 115
	STORE_NAME                        Opcode = 116
	SWAP                              Opcode = 117
	UNPACK_EX                         Opcode = 118
	UNPACK_SEQUENCE                   Opcode = 119
	YIELD_VALUE                       Opcode = 120
	RESUME                            Opcode = 128
	INSTRUMENTED_END_FOR              Opcode = 234
	INSTRUMENTED_POP_ITER             Opcode = 235
	INSTRUMENTED_END_SEND             Opcode = 236
	INSTRUMENTED_FOR_ITER             Opcode = 237
	INSTRUMENTED_INSTRUCTION          Opcode = 238
	INSTRUMENTED_JUMP_FORWARD         Opcode = 239
	INSTRUMENTED_NOT_TAKEN            Opcode = 240
	INSTRUMENTED_POP_JUMP_IF_TRUE     Opcode = 241
	INSTRUMENTED_POP_JUMP_IF_FALSE    Opcode = 242
	INSTRUMENTED_POP_JUMP_IF_NONE     Opcode = 243
	INSTRUMENTED_POP_JUMP_IF_NOT_NONE Opcode = 244
	INSTRUMENTED_RESUME               Opcode = 245
	INSTRUMENTED_RETURN_VALUE         Opcode = 246
	INSTRUMENTED_YIELD_VALUE          Opcode = 247
	INSTRUMENTED_END_ASYNC_FOR        Opcode = 248
	INSTRUMENTED_LOAD_SUPER_ATTR      Opcode = 249
	INSTRUMENTED_CALL                 Opcode = 250
	INSTRUMENTED_CALL_KW              Opcode = 251
	INSTRUMENTED_CALL_FUNCTION_EX     Opcode = 252
	INSTRUMENTED_JUMP_BACKWARD        Opcode = 253
	INSTRUMENTED_LINE                 Opcode = 254
	ENTER_EXECUTOR                    Opcode = 255
	ANNOTATIONS_PLACEHOLDER           Opcode = 256
	JUMP                              Opcode = 257
	JUMP_IF_FALSE                     Opcode = 258
	JUMP_IF_TRUE                      Opcode = 259
	JUMP_NO_INTERRUPT                 Opcode = 260
	LOAD_CLOSURE                      Opcode = 261
	POP_BLOCK                         Opcode = 262
	SETUP_CLEANUP                     Opcode = 263
	SETUP_FINALLY                     Opcode = 264
	SETUP_WITH                        Opcode = 265
	STORE_FAST_MAYBE_NULL             Opcode = 266
)

// opcodeFlags is indexed by opcode value.
var opcodeFlags = [267]uint16{
	BINARY_SLICE:                      0x0300,
	BUILD_TEMPLATE:                    0x0300,
	CALL_FUNCTION_EX:                  0x4340,
	CHECK_EG_MATCH:                    0x0300,
	CHECK_EXC_MATCH:                   0x4300,
	CLEANUP_THROW:                     0x4300,
	DELETE_SUBSCR:                     0x0300,
	END_FOR:                           0x8200,
	END_SEND:                          0x0a00,
	EXIT_INIT_CHECK:                   0x4300,
	FORMAT_SIMPLE:                     0x0300,
	FORMAT_WITH_SPEC:                  0x0300,
	GET_AITER:                         0x0300,
	GET_ANEXT:                         0x4300,
	GET_ITER:                          0x0300,
	GET_LEN:                           0x0300,
	GET_YIELD_FROM_ITER:               0x4300,
	INTERPRETER_EXIT:                  0x0200,
	LOAD_BUILD_CLASS:                  0x0300,
	LOAD_LOCALS:                       0x0300,
	MAKE_FUNCTION:                     0x0300,
	MATCH_KEYS:                        0x0300,
	NOP:                               0x0800,
	NOT_TAKEN:                         0x0800,
	POP_EXCEPT:                        0x0200,
	POP_ITER:                          0x0a00,
	POP_TOP:                           0x0a00,
	PUSH_NULL:                         0x0800,
	RETURN_GENERATOR:                  0x0300,
	RETURN_VALUE:                      0x0200,
	SETUP_ANNOTATIONS:                 0x0300,
	STORE_SLICE:                       0x0300,
	STORE_SUBSCR:                      0x0300,
	TO_BOOL:                           0x0300,
	UNARY_INVERT:                      0x0300,
	UNARY_NEGATIVE:                    0x0300,
	UNARY_NOT:                         0x0800,
	WITH_EXCEPT_START:                 0x0300,
	BINARY_OP:                         0x4301,
	BUILD_INTERPOLATION:               0x0301,
	BUILD_LIST:                        0x4301,
	BUILD_MAP:                         0x0301,
	BUILD_SET:                         0x0301,
	BUILD_SLICE:                       0x0101,
	BUILD_STRING:                      0x0101,
	BUILD_TUPLE:                       0x4101,
	CALL:                              0x4341,
	CALL_INTRINSIC_1:                  0x0301,
	CALL_INTRINSIC_2:                  0x0301,
	CALL_KW:                           0x4301,
	COMPARE_OP:                        0x0301,
	CONTAINS_OP:                       0x0301,
	CONVERT_VALUE:                     0x0301,
	COPY:                              0x0801,
	COPY_FREE_VARS:                    0x0001,
	DELETE_ATTR:                       0x0305,
	DELETE_DEREF:                      0x4311,
	DELETE_FAST:                       0x0321,
	DELETE_GLOBAL:                     0x4305,
	DELETE_NAME:                       0x4305,
	DICT_MERGE:                        0x0301,
	DICT_UPDATE:                       0x0301,
	END_ASYNC_FOR:                     0x4309,
	EXTENDED_ARG:                      0x0001,
	FOR_ITER:                          0x4309,
	GET_AWAITABLE:                     0x0301,
	IMPORT_FROM:                       0x0305,
	IMPORT_NAME:                       0x0305,
	IS_OP:                             0x0001,
	JUMP_BACKWARD:                     0x0349,
	JUMP_BACKWARD_NO_INTERRUPT:        0x0009,
	JUMP_FORWARD:                      0x0009,
	LIST_APPEND:                       0x0101,
	LIST_EXTEND:                       0x0301,
	LOAD_ATTR:                         0x0305,
	LOAD_COMMON_CONSTANT:              0x0001,
	LOAD_CONST:                        0x0003,
	LOAD_DEREF:                        0x0321,
	LOAD_FAST:                         0x0821,
	LOAD_FAST_AND_CLEAR:               0x0021,
	LOAD_FAST_BORROW:                  0x0821,
	LOAD_FAST_BORROW_LOAD_FAST_BORROW: 0x0021,
	LOAD_FAST_CHECK:                   0x0321,
	LOAD_FAST_LOAD_FAST:               0x0021,
	LOAD_FROM_DICT_OR_DEREF:           0x4311,
	LOAD_FROM_DICT_OR_GLOBALS:         0x4305,
	LOAD_GLOBAL:                       0x0305,
	LOAD_NAME:                         0x0305,
	LOAD_SMALL_INT:                    0x0001,
	LOAD_SPECIAL:                      0x4301,
	LOAD_SUPER_ATTR:                   0x0305,
	MAKE_CELL:                         0x4311,
	MAP_ADD:                           0x0301,
	MATCH_CLASS:                       0x0301,
	POP_JUMP_IF_FALSE:                 0x0009,
	POP_JUMP_IF_NONE:                  0x0009,
	POP_JUMP_IF_NOT_NONE:              0x0009,
	POP_JUMP_IF_TRUE:                  0x0009,
	RAISE_VARARGS:                     0x4301,
	RERAISE:                           0x4301,
	SEND:                              0x0309,
	SET_ADD:                           0x0301,
	SET_FUNCTION_ATTRIBUTE:            0x0301,
	SET_UPDATE:                        0x0301,
	STORE_ATTR:                        0x0305,
	STORE_DEREF:                       0x0211,
	STORE_FAST:                        0x0221,
	STORE_FAST_LOAD_FAST:              0x0221,
	STORE_FAST_STORE_FAST:             0x0221,
	STORE_GLOBAL:                      0x0305,
	STORE_NAME:                        0x0305,
	SWAP:                              0x0801,
	UNPACK_EX:                         0x0301,
	UNPACK_SEQUENCE:                   0x0301,
	YIELD_VALUE:                       0x0001,
	RESUME:                            0x4341,
	INSTRUMENTED_END_FOR:              0xc300,
	INSTRUMENTED_POP_ITER:             0x0200,
	INSTRUMENTED_END_SEND:             0x4300,
	INSTRUMENTED_FOR_ITER:             0x4309,
	INSTRUMENTED_INSTRUCTION:          0x0300,
	INSTRUMENTED_JUMP_FORWARD:         0x0001,
	INSTRUMENTED_POP_JUMP_IF_TRUE:     0x0001,
	INSTRUMENTED_POP_JUMP_IF_FALSE:    0x0001,
	INSTRUMENTED_POP_JUMP_IF_NONE:     0x0201,
	INSTRUMENTED_POP_JUMP_IF_NOT_NONE: 0x0201,
	INSTRUMENTED_RESUME:               0x4341,
	INSTRUMENTED_RETURN_VALUE:         0x0300,
	INSTRUMENTED_YIELD_VALUE:          0x4301,
	INSTRUMENTED_END_ASYNC_FOR:        0x4309,
	INSTRUMENTED_LOAD_SUPER_ATTR:      0x0305,
	INSTRUMENTED_CALL:                 0x4341,
	INSTRUMENTED_CALL_KW:              0x4301,
	INSTRUMENTED_CALL_FUNCTION_EX:     0x4340,
	INSTRUMENTED_JUMP_BACKWARD:        0x0341,
	INSTRUMENTED_LINE:                 0x0200,
	ENTER_EXECUTOR:                    0x0001,
}

var opcodeName = [267]string{
	CACHE:                             "CACHE",
	BINARY_SLICE:                      "BINARY_SLICE",
	BUILD_TEMPLATE:                    "BUILD_TEMPLATE",
	CALL_FUNCTION_EX:                  "CALL_FUNCTION_EX",
	CHECK_EG_MATCH:                    "CHECK_EG_MATCH",
	CHECK_EXC_MATCH:                   "CHECK_EXC_MATCH",
	CLEANUP_THROW:                     "CLEANUP_THROW",
	DELETE_SUBSCR:                     "DELETE_SUBSCR",
	END_FOR:                           "END_FOR",
	END_SEND:                          "END_SEND",
	EXIT_INIT_CHECK:                   "EXIT_INIT_CHECK",
	FORMAT_SIMPLE:                     "FORMAT_SIMPLE",
	FORMAT_WITH_SPEC:                  "FORMAT_WITH_SPEC",
	GET_AITER:                         "GET_AITER",
	GET_ANEXT:                         "GET_ANEXT",
	GET_ITER:                          "GET_ITER",
	RESERVED:                          "RESERVED",
	GET_LEN:                           "GET_LEN",
	GET_YIELD_FROM_ITER:               "GET_YIELD_FROM_ITER",
	INTERPRETER_EXIT:                  "INTERPRETER_EXIT",
	LOAD_BUILD_CLASS:                  "LOAD_BUILD_CLASS",
	LOAD_LOCALS:                       "LOAD_LOCALS",
	MAKE_FUNCTION:                     "MAKE_FUNCTION",
	MATCH_KEYS:                        "MATCH_KEYS",
	MATCH_MAPPING:                     "MATCH_MAPPING",
	MATCH_SEQUENCE:                    "MATCH_SEQUENCE",
	NOP:                               "NOP",
	NOT_TAKEN:                         "NOT_TAKEN",
	POP_EXCEPT:                        "POP_EXCEPT",
	POP_ITER:                          "POP_ITER",
	POP_TOP:                           "POP_TOP",
	PUSH_EXC_INFO:                     "PUSH_EXC_INFO",
	PUSH_NULL:                         "PUSH_NULL",
	RETURN_GENERATOR:                  "RETURN_GENERATOR",
	RETURN_VALUE:                      "RETURN_VALUE",
	SETUP_ANNOTATIONS:                 "SETUP_ANNOTATIONS",
	STORE_SLICE:                       "STORE_SLICE",
	STORE_SUBSCR:                      "STORE_SUBSCR",
	TO_BOOL:                           "TO_BOOL",
	UNARY_INVERT:                      "UNARY_INVERT",
	UNARY_NEGATIVE:                    "UNARY_NEGATIVE",
	UNARY_NOT:                         "UNARY_NOT",
	WITH_EXCEPT_START:                 "WITH_EXCEPT_START",
	BINARY_OP:                         "BINARY_OP",
	BUILD_INTERPOLATION:               "BUILD_INTERPOLATION",
	BUILD_LIST:                        "BUILD_LIST",
	BUILD_MAP:                         "BUILD_MAP",
	BUILD_SET:                         "BUILD_SET",
	BUILD_SLICE:                       "BUILD_SLICE",
	BUILD_STRING:                      "BUILD_STRING",
	BUILD_TUPLE:                       "BUILD_TUPLE",
	CALL:                              "CALL",
	CALL_INTRINSIC_1:                  "CALL_INTRINSIC_1",
	CALL_INTRINSIC_2:                  "CALL_INTRINSIC_2",
	CALL_KW:                           "CALL_KW",
	COMPARE_OP:                        "COMPARE_OP",
	CONTAINS_OP:                       "CONTAINS_OP",
	CONVERT_VALUE:                     "CONVERT_VALUE",
	COPY:                              "COPY",
	COPY_FREE_VARS:                    "COPY_FREE_VARS",
	DELETE_ATTR:                       "DELETE_ATTR",
	DELETE_DEREF:                      "DELETE_DEREF",
	DELETE_FAST:                       "DELETE_FAST",
	DELETE_GLOBAL:                     "DELETE_GLOBAL",
	DELETE_NAME:                       "DELETE_NAME",
	DICT_MERGE:                        "DICT_MERGE",
	DICT_UPDATE:                       "DICT_UPDATE",
	END_ASYNC_FOR:                     "END_ASYNC_FOR",
	EXTENDED_ARG:                      "EXTENDED_ARG",
	FOR_ITER:                          "FOR_ITER",
	GET_AWAITABLE:                     "GET_AWAITABLE",
	IMPORT_FROM:                       "IMPORT_FROM",
	IMPORT_NAME:                       "IMPORT_NAME",
	IS_OP:                             "IS_OP",
	JUMP_BACKWARD:                     "JUMP_BACKWARD",
	JUMP_BACKWARD_NO_INTERRUPT:        "JUMP_BACKWARD_NO_INTERRUPT",
	JUMP_FORWARD:                      "JUMP_FORWARD",
	LIST_APPEND:                       "LIST_APPEND",
	LIST_EXTEND:                       "LIST_EXTEND",
	LOAD_ATTR:                         "LOAD_ATTR",
	LOAD_COMMON_CONSTANT:              "LOAD_COMMON_CONSTANT",
	LOAD_CONST:                        "LOAD_CONST",
	LOAD_DEREF:                        "LOAD_DEREF",
	LOAD_FAST:                         "LOAD_FAST",
	LOAD_FAST_AND_CLEAR:               "LOAD_FAST_AND_CLEAR",
	LOAD_FAST_BORROW:                  "LOAD_FAST_BORROW",
	LOAD_FAST_BORROW_LOAD_FAST_BORROW: "LOAD_FAST_BORROW_LOAD_FAST_BORROW",
	LOAD_FAST_CHECK:                   "LOAD_FAST_CHECK",
	LOAD_FAST_LOAD_FAST:               "LOAD_FAST_LOAD_FAST",
	LOAD_FROM_DICT_OR_DEREF:           "LOAD_FROM_DICT_OR_DEREF",
	LOAD_FROM_DICT_OR_GLOBALS:         "LOAD_FROM_DICT_OR_GLOBALS",
	LOAD_GLOBAL:                       "LOAD_GLOBAL",
	LOAD_NAME:                         "LOAD_NAME",
	LOAD_SMALL_INT:                    "LOAD_SMALL_INT",
	LOAD_SPECIAL:                      "LOAD_SPECIAL",
	LOAD_SUPER_ATTR:                   "LOAD_SUPER_ATTR",
	MAKE_CELL:                         "MAKE_CELL",
	MAP_ADD:                           "MAP_ADD",
	MATCH_CLASS:                       "MATCH_CLASS",
	POP_JUMP_IF_FALSE:                 "POP_JUMP_IF_FALSE",
	POP_JUMP_IF_NONE:                  "POP_JUMP_IF_NONE",
	POP_JUMP_IF_NOT_NONE:              "POP_JUMP_IF_NOT_NONE",
	POP_JUMP_IF_TRUE:                  "POP_JUMP_IF_TRUE",
	RAISE_VARARGS:                     "RAISE_VARARGS",
	RERAISE:                           "RERAISE",
	SEND:                              "SEND",
	SET_ADD:                           "SET_ADD",
	SET_FUNCTION_ATTRIBUTE:            "SET_FUNCTION_ATTRIBUTE",
	SET_UPDATE:                        "SET_UPDATE",
	STORE_ATTR:                        "STORE_ATTR",
	STORE_DEREF:                       "STORE_DEREF",
	STORE_FAST:                        "STORE_FAST",
	STORE_FAST_LOAD_FAST:              "STORE_FAST_LOAD_FAST",
	STORE_FAST_STORE_FAST:             "STORE_FAST_STORE_FAST",
	STORE_GLOBAL:                      "STORE_GLOBAL",
	STORE_NAME:                        "STORE_NAME",
	SWAP:                              "SWAP",
	UNPACK_EX:                         "UNPACK_EX",
	UNPACK_SEQUENCE:                   "UNPACK_SEQUENCE",
	YIELD_VALUE:                       "YIELD_VALUE",
	RESUME:                            "RESUME",
	INSTRUMENTED_END_FOR:              "INSTRUMENTED_END_FOR",
	INSTRUMENTED_POP_ITER:             "INSTRUMENTED_POP_ITER",
	INSTRUMENTED_END_SEND:             "INSTRUMENTED_END_SEND",
	INSTRUMENTED_FOR_ITER:             "INSTRUMENTED_FOR_ITER",
	INSTRUMENTED_INSTRUCTION:          "INSTRUMENTED_INSTRUCTION",
	INSTRUMENTED_JUMP_FORWARD:         "INSTRUMENTED_JUMP_FORWARD",
	INSTRUMENTED_NOT_TAKEN:            "INSTRUMENTED_NOT_TAKEN",
	INSTRUMENTED_POP_JUMP_IF_TRUE:     "INSTRUMENTED_POP_JUMP_IF_TRUE",
	INSTRUMENTED_POP_JUMP_IF_FALSE:    "INSTRUMENTED_POP_JUMP_IF_FALSE",
	INSTRUMENTED_POP_JUMP_IF_NONE:     "INSTRUMENTED_POP_JUMP_IF_NONE",
	INSTRUMENTED_POP_JUMP_IF_NOT_NONE: "INSTRUMENTED_POP_JUMP_IF_NOT_NONE",
	INSTRUMENTED_RESUME:               "INSTRUMENTED_RESUME",
	INSTRUMENTED_RETURN_VALUE:         "INSTRUMENTED_RETURN_VALUE",
	INSTRUMENTED_YIELD_VALUE:          "INSTRUMENTED_YIELD_VALUE",
	INSTRUMENTED_END_ASYNC_FOR:        "INSTRUMENTED_END_ASYNC_FOR",
	INSTRUMENTED_LOAD_SUPER_ATTR:      "INSTRUMENTED_LOAD_SUPER_ATTR",
	INSTRUMENTED_CALL:                 "INSTRUMENTED_CALL",
	INSTRUMENTED_CALL_KW:              "INSTRUMENTED_CALL_KW",
	INSTRUMENTED_CALL_FUNCTION_EX:     "INSTRUMENTED_CALL_FUNCTION_EX",
	INSTRUMENTED_JUMP_BACKWARD:        "INSTRUMENTED_JUMP_BACKWARD",
	INSTRUMENTED_LINE:                 "INSTRUMENTED_LINE",
	ENTER_EXECUTOR:                    "ENTER_EXECUTOR",
	ANNOTATIONS_PLACEHOLDER:           "ANNOTATIONS_PLACEHOLDER",
	JUMP:                              "JUMP",
	JUMP_IF_FALSE:                     "JUMP_IF_FALSE",
	JUMP_IF_TRUE:                      "JUMP_IF_TRUE",
	JUMP_NO_INTERRUPT:                 "JUMP_NO_INTERRUPT",
	LOAD_CLOSURE:                      "LOAD_CLOSURE",
	POP_BLOCK:                         "POP_BLOCK",
	SETUP_CLEANUP:                     "SETUP_CLEANUP",
	SETUP_FINALLY:                     "SETUP_FINALLY",
	SETUP_WITH:                        "SETUP_WITH",
	STORE_FAST_MAYBE_NULL:             "STORE_FAST_MAYBE_NULL",
}

// Name returns the symbolic name for op, or "" if op is not a known opcode.
func (op Opcode) Name() string {
	if op < 0 || int(op) >= len(opcodeName) {
		return ""
	}
	return opcodeName[op]
}

// HasArg reports whether op carries the arg metadata flag.
func (op Opcode) HasArg() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagArg != 0
}

// HasConst reports whether op carries the const metadata flag.
func (op Opcode) HasConst() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagConst != 0
}

// HasName reports whether op carries the name metadata flag.
func (op Opcode) HasName() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagName != 0
}

// HasJump reports whether op carries the jump metadata flag.
func (op Opcode) HasJump() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagJump != 0
}

// HasFree reports whether op carries the free metadata flag.
func (op Opcode) HasFree() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagFree != 0
}

// HasLocal reports whether op carries the local metadata flag.
func (op Opcode) HasLocal() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagLocal != 0
}

// HasEvalBreak reports whether op carries the eval break metadata flag.
func (op Opcode) HasEvalBreak() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagEvalBreak != 0
}

// HasDeopt reports whether op carries the deopt metadata flag.
func (op Opcode) HasDeopt() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagDeopt != 0
}

// HasError reports whether op carries the error metadata flag.
func (op Opcode) HasError() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagError != 0
}

// HasEscapes reports whether op carries the escapes metadata flag.
func (op Opcode) HasEscapes() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagEscapes != 0
}

// HasExit reports whether op carries the exit metadata flag.
func (op Opcode) HasExit() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagExit != 0
}

// HasPure reports whether op carries the pure metadata flag.
func (op Opcode) HasPure() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagPure != 0
}

// HasPassthrough reports whether op carries the passthrough metadata flag.
func (op Opcode) HasPassthrough() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagPassthrough != 0
}

// HasOpargAnd1 reports whether op carries the oparg and 1 metadata flag.
func (op Opcode) HasOpargAnd1() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagOpargAnd1 != 0
}

// HasErrorNoPop reports whether op carries the error no pop metadata flag.
func (op Opcode) HasErrorNoPop() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagErrorNoPop != 0
}

// HasNoSaveIP reports whether op carries the no save ip metadata flag.
func (op Opcode) HasNoSaveIP() bool {
	if op < 0 || int(op) >= len(opcodeFlags) {
		return false
	}
	return opcodeFlags[op]&flagNoSaveIP != 0
}

// HasTarget reports whether op carries a jump target oparg.
// CPython spells this OPCODE_HAS_JUMP and uses it from the
// instruction-sequence label resolver.
func HasTarget(op Opcode) bool { return op.HasJump() }
