// Shared rewrite passes used by tier1, tier2, and optimizer generators: token-replacement registry and the body-emission walker.
//
// CPython: Tools/cases_generator/generators_common.py
package main

import (
	"errors"
	"fmt"
	"io"
	"path/filepath"
	"strings"
)

// debug toggles the emit_tokens storage commentary.
//
// CPython: Tools/cases_generator/generators_common.py:17 DEBUG
var debug = false

// TokenIterator is a positionable cursor over a token slice with one
// slot of look-ahead, mirroring the upstream generator.
//
// CPython: Tools/cases_generator/generators_common.py:19-44 TokenIterator
type TokenIterator struct {
	tokens []Token
	pos    int
}

// NewTokenIterator wraps a token slice as an iterator.
//
// CPython: Tools/cases_generator/generators_common.py:24-26 TokenIterator.__init__
func NewTokenIterator(tkns []Token) *TokenIterator {
	return &TokenIterator{tokens: tkns}
}

// Next returns the next token and true, or a zero Token and false at EOF.
//
// CPython: Tools/cases_generator/generators_common.py:31-37 TokenIterator.__next__
func (it *TokenIterator) Next() (Token, bool) {
	if it.pos >= len(it.tokens) {
		return Token{}, false
	}
	t := it.tokens[it.pos]
	it.pos++
	return t, true
}

// Peek returns the next token without advancing, or zero Token and false.
//
// CPython: Tools/cases_generator/generators_common.py:39-44 TokenIterator.peek
func (it *TokenIterator) Peek() (Token, bool) {
	if it.pos >= len(it.tokens) {
		return Token{}, false
	}
	return it.tokens[it.pos], true
}

// rootRelativePath echoes the upstream helper, returning a path that
// is relative to projectRoot when possible and the original otherwise.
//
// CPython: Tools/cases_generator/generators_common.py:50-55 root_relative_path
func rootRelativePath(filename, projectRoot string) string {
	if projectRoot == "" {
		return filepath.ToSlash(filename)
	}
	abs, err := filepath.Abs(filename)
	if err != nil {
		return filepath.ToSlash(filename)
	}
	rel, err := filepath.Rel(projectRoot, abs)
	if err != nil || strings.HasPrefix(rel, "..") {
		return filepath.ToSlash(filename)
	}
	return filepath.ToSlash(rel)
}

// typeAndNull returns (decltype, null_literal) for a stack item.
//
// CPython: Tools/cases_generator/generators_common.py:58-64 type_and_null
func typeAndNull(v *StackItem) (string, string) {
	switch {
	case v.Type != "":
		return v.Type, "NULL"
	case v.IsArray():
		return "_PyStackRef *", "NULL"
	default:
		return "_PyStackRef", "PyStackRef_NULL"
	}
}

// writeHeader writes the generator banner that opens every emitted file.
//
// CPython: Tools/cases_generator/generators_common.py:67-76 write_header
func writeHeader(generator string, sources []string, out io.Writer, comment, projectRoot string) error {
	if comment == "" {
		comment = "//"
	}
	parts := make([]string, 0, len(sources))
	for _, s := range sources {
		parts = append(parts, rootRelativePath(s, projectRoot))
	}
	_, err := fmt.Fprintf(out,
		"%s This file is generated by %s\n%s from:\n%s   %s\n%s Do not edit!\n",
		comment, rootRelativePath(generator, projectRoot),
		comment,
		comment, strings.Join(parts, ", "),
		comment,
	)
	return err
}

// emitTo copies tokens straight to out until it sees a top-level token
// matching kind. The matched token is consumed and returned.
//
// CPython: Tools/cases_generator/generators_common.py:79-89 emit_to
func emitTo(out *CWriter, it *TokenIterator, end string) (Token, error) {
	parens := 0
	for {
		tkn, ok := it.Next()
		if !ok {
			var anchor Token
			if it.pos > 0 {
				anchor = it.tokens[it.pos-1]
			}
			return Token{}, analysisError(
				fmt.Sprintf("Expecting %s. Reached end of file", end),
				anchor,
			)
		}
		if tkn.Kind == end && parens == 0 {
			return tkn, nil
		}
		switch tkn.Kind {
		case TokLParen:
			parens++
		case TokRParen:
			parens--
		}
		out.Emit(tkn)
	}
}

// alwaysTrue reports whether tkn is the boolean literal "true" or "1".
//
// CPython: Tools/cases_generator/generators_common.py:96-99 always_true
func alwaysTrue(tkn Token, ok bool) bool {
	if !ok {
		return false
	}
	return tkn.Text == "true" || tkn.Text == "1"
}

// nonEscapingDeallocs is the carve-out of dealloc helpers that do not
// trigger a stack save when called.
//
// CPython: Tools/cases_generator/generators_common.py:101-105 NON_ESCAPING_DEALLOCS
var nonEscapingDeallocs = map[string]struct{}{
	"_PyFloat_ExactDealloc":   {},
	"_PyLong_ExactDealloc":    {},
	"_PyUnicode_ExactDealloc": {},
}

// CodeSection is the union Uop | Label that the body emitter walks.
//
// CPython: Tools/cases_generator/analyzer.py:247 CodeSection
type CodeSection interface {
	GetBody() *BlockStmt
	GetProperties() *Properties
	GetLocalStores() []Token
	GetInstructionSize() *int
}

// GetBody returns the uop block.
func (u *Uop) GetBody() *BlockStmt { return u.Body }

// GetProperties returns the uop properties.
func (u *Uop) GetProperties() *Properties { return u.Properties }

// GetLocalStores returns the per-uop local store tokens.
func (u *Uop) GetLocalStores() []Token { return u.LocalStores }

// GetInstructionSize returns the size, if known.
func (u *Uop) GetInstructionSize() *int { return u.InstructionSize }

// GetBody returns the label block.
func (l *Label) GetBody() *BlockStmt { return l.Body }

// GetProperties returns the label properties.
func (l *Label) GetProperties() *Properties { return l.Properties }

// GetLocalStores returns the label's local stores.
func (l *Label) GetLocalStores() []Token { return l.LocalStores }

// GetInstructionSize returns the label's instruction size if any.
func (l *Label) GetInstructionSize() *int { return l.InstructionSize }

// ReplacementFunc dispatches on a recognized identifier inside a uop body.
// It returns (reachable, error): reachable=false means the dispatched
// keyword unconditionally exits the surrounding statement.
//
// CPython: Tools/cases_generator/generators_common.py:92-94 ReplacementFunctionType
type ReplacementFunc func(
	tkn Token,
	it *TokenIterator,
	uop CodeSection,
	storage *Storage,
	inst *Instruction,
) (bool, error)

// Emitter walks a CodeSection body, dispatching keyword identifiers
// through a replacement registry and emitting the rest verbatim.
//
// CPython: Tools/cases_generator/generators_common.py:107-131 Emitter
type Emitter struct {
	Out       *CWriter
	Labels    map[string]*Label
	replacers map[string]ReplacementFunc
}

// NewEmitter builds an Emitter wired to the default replacement registry.
//
// CPython: Tools/cases_generator/generators_common.py:112-131 Emitter.__init__
func NewEmitter(out *CWriter, labels map[string]*Label) *Emitter {
	e := &Emitter{Out: out, Labels: labels}
	e.replacers = map[string]ReplacementFunc{
		"EXIT_IF":                      e.ExitIf,
		"DEOPT_IF":                     e.DeoptIf,
		"ERROR_IF":                     e.ErrorIf,
		"ERROR_NO_POP":                 e.ErrorNoPop,
		"DECREF_INPUTS":                e.DecrefInputs,
		"DEAD":                         e.Kill,
		"INPUTS_DEAD":                  e.KillInputs,
		"SYNC_SP":                      e.SyncSp,
		"SAVE_STACK":                   e.SaveStack,
		"RELOAD_STACK":                 e.ReloadStack,
		"PyStackRef_CLOSE_SPECIALIZED": e.StackrefCloseSpecialized,
		"PyStackRef_AsPyObjectSteal":   e.StackrefSteal,
		"DISPATCH":                     e.Dispatch,
		"INSTRUCTION_SIZE":             e.InstructionSize,
		"stack_pointer":                e.StackPointer,
	}
	return e
}

// Replacers exposes the dispatch table for callers (e.g. for derived
// generators that want to override individual entries).
func (e *Emitter) Replacers() map[string]ReplacementFunc { return e.replacers }

// SetReplacer overrides one entry in the dispatch table.
func (e *Emitter) SetReplacer(name string, fn ReplacementFunc) {
	e.replacers[name] = fn
}

// Emit is a thin wrapper around CWriter.Emit accepting Token or string.
//
// CPython: Tools/cases_generator/generators_common.py:671-672 Emitter.emit
func (e *Emitter) Emit(v any) { e.Out.Emit(v) }

// Dispatch handles the bare DISPATCH() identifier: it must be reached
// with the stack already reloaded.
//
// CPython: Tools/cases_generator/generators_common.py:133-144 Emitter.dispatch
func (e *Emitter) Dispatch(
	tkn Token, _ *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	if storage.Spilled != 0 {
		return false, analysisError("stack_pointer needs reloading before dispatch", tkn)
	}
	e.Emit(tkn)
	return false, nil
}

// DeoptIf rewrites DEOPT_IF(cond); into the standard if-block plus the
// JUMP_TO_PREDICTED tail. Returns false (unreachable past) when the
// condition is the literal true/1.
//
// CPython: Tools/cases_generator/generators_common.py:146-169 Emitter.deopt_if
func (e *Emitter) DeoptIf(
	_ Token, it *TokenIterator, _ CodeSection, _ *Storage, inst *Instruction,
) (bool, error) {
	e.Out.StartLine()
	e.Out.Emit("if (")
	lparen, ok := it.Next()
	if !ok || lparen.Kind != TokLParen {
		return false, analysisError("Expected '(' after DEOPT_IF", lparen)
	}
	first, hasFirst := it.Peek()
	if _, err := emitTo(e.Out, it, TokRParen); err != nil {
		return false, err
	}
	e.Emit(") {\n")
	if _, ok := it.Next(); !ok { // semicolon
		return false, analysisError("Expected ';' after DEOPT_IF", lparen)
	}
	if inst == nil || inst.Family == nil {
		return false, analysisError("DEOPT_IF requires an instruction with a family", lparen)
	}
	familyName := inst.Family.Name
	e.Emit(fmt.Sprintf("UPDATE_MISS_STATS(%s);\n", familyName))
	e.Emit(fmt.Sprintf("assert(_PyOpcode_Deopt[opcode] == (%s));\n", familyName))
	e.Emit(fmt.Sprintf("JUMP_TO_PREDICTED(%s);\n", familyName))
	e.Emit("}\n")
	return !alwaysTrue(first, hasFirst), nil
}

// ExitIf is identical to DeoptIf in upstream (`exit_if = deopt_if`).
//
// CPython: Tools/cases_generator/generators_common.py:171 Emitter.exit_if
func (e *Emitter) ExitIf(
	tkn Token, it *TokenIterator, uop CodeSection, storage *Storage, inst *Instruction,
) (bool, error) {
	return e.DeoptIf(tkn, it, uop, storage, inst)
}

// gotoError renders the matching JUMP_TO_LABEL(...) for an offset.
//
// CPython: Tools/cases_generator/generators_common.py:173-178 Emitter.gotoTknerror
func (e *Emitter) gotoError(offset int, storage *Storage) string {
	if offset > 0 {
		return fmt.Sprintf("JUMP_TO_LABEL(pop_%d_error);", offset)
	}
	if offset < 0 {
		_ = storage.Copy().Flush(e.Out)
	}
	return "JUMP_TO_LABEL(error);"
}

// ErrorIf rewrites ERROR_IF(cond); into the if/jump pair.
//
// CPython: Tools/cases_generator/generators_common.py:180-213 Emitter.error_if
func (e *Emitter) ErrorIf(
	tkn Token, it *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	lparen, ok := it.Next()
	if !ok || lparen.Kind != TokLParen {
		return false, analysisError("Expected '(' after ERROR_IF", tkn)
	}
	first, hasFirst := it.Peek()
	unconditional := alwaysTrue(first, hasFirst)
	if unconditional {
		if _, ok := it.Next(); !ok {
			return false, analysisError("Truncated ERROR_IF", tkn)
		}
		if _, ok := it.Next(); !ok { // RPAREN
			return false, analysisError("Truncated ERROR_IF", tkn)
		}
		e.Out.StartLine()
	} else {
		e.Out.EmitAt("if ", tkn)
		e.Emit(lparen)
		if _, err := emitTo(e.Out, it, TokRParen); err != nil {
			return false, err
		}
		e.Out.Emit(") {\n")
	}
	if _, ok := it.Next(); !ok { // semicolon
		return false, analysisError("Expected ';' after ERROR_IF", tkn)
	}
	if err := storage.ClearInputs("at ERROR_IF"); err != nil {
		return false, err
	}
	cOffset := storage.Stack.SpOffset()
	offset, err := atoiStrict(cOffset)
	if err != nil {
		offset = -1
	}
	e.Out.Emit(e.gotoError(offset, storage))
	e.Out.Emit("\n")
	if !unconditional {
		e.Out.Emit("}\n")
	}
	return !unconditional, nil
}

// ErrorNoPop rewrites ERROR_NO_POP(); into JUMP_TO_LABEL(error).
//
// CPython: Tools/cases_generator/generators_common.py:215-227 Emitter.error_no_pop
func (e *Emitter) ErrorNoPop(
	tkn Token, it *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	for i := 0; i < 3; i++ { // LPAREN, RPAREN, SEMI
		if _, ok := it.Next(); !ok {
			return false, analysisError("Truncated ERROR_NO_POP", tkn)
		}
	}
	e.Out.EmitAt(e.gotoError(0, storage), tkn)
	return false, nil
}

// DecrefInputs lowers DECREF_INPUTS(); through Storage.CloseInputs.
//
// CPython: Tools/cases_generator/generators_common.py:229-248 Emitter.decref_inputs
func (e *Emitter) DecrefInputs(
	tkn Token, it *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	for i := 0; i < 3; i++ {
		if _, ok := it.Next(); !ok {
			return false, analysisError("Truncated DECREF_INPUTS", tkn)
		}
	}
	e.printStorage("DECREF_INPUTS", storage)
	if err := storage.CloseInputs(e.Out); err != nil {
		var se *StackError
		if errors.As(err, &se) {
			return false, analysisError(se.Msg, tkn)
		}
		return false, err
	}
	return true, nil
}

// KillInputs marks every input dead without emitting anything.
//
// CPython: Tools/cases_generator/generators_common.py:250-263 Emitter.kill_inputs
func (e *Emitter) KillInputs(
	tkn Token, it *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	for i := 0; i < 3; i++ {
		if _, ok := it.Next(); !ok {
			return false, analysisError("Truncated INPUTS_DEAD", tkn)
		}
	}
	for _, v := range storage.Inputs {
		v.Kill()
	}
	return true, nil
}

// Kill marks DEAD(name); the named input dead.
//
// CPython: Tools/cases_generator/generators_common.py:265-286 Emitter.kill
func (e *Emitter) Kill(
	tkn Token, it *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	if _, ok := it.Next(); !ok { // LPAREN
		return false, analysisError("Truncated DEAD", tkn)
	}
	nameTkn, ok := it.Next()
	if !ok {
		return false, analysisError("Truncated DEAD", tkn)
	}
	name := nameTkn.Text
	if _, ok := it.Next(); !ok { // RPAREN
		return false, analysisError("Truncated DEAD", tkn)
	}
	if _, ok := it.Next(); !ok { // SEMI
		return false, analysisError("Truncated DEAD", tkn)
	}
	for _, v := range storage.Inputs {
		if v.Name() == name {
			v.Kill()
			return true, nil
		}
	}
	return false, analysisError(
		fmt.Sprintf("'%s' is not a live input-only variable", name),
		nameTkn,
	)
}

// stackrefKill closes a single PyStackRef by name, optionally checking
// that no later live local prevents an escaping close.
//
// CPython: Tools/cases_generator/generators_common.py:288-305 Emitter.stackref_kill
func (e *Emitter) stackrefKill(name Token, storage *Storage, escapes bool) (bool, error) {
	live := ""
	for i := len(storage.Inputs) - 1; i >= 0; i-- {
		v := storage.Inputs[i]
		if v.Name() == name.Text {
			if live != "" && escapes {
				return false, analysisError(
					fmt.Sprintf("Cannot close '%s' when '%s' is still live", name.Text, live),
					name,
				)
			}
			v.Kill()
			break
		}
		if v.InLocal {
			live = v.Name()
		}
	}
	return true, nil
}

// StackrefCloseSpecialized handles PyStackRef_CLOSE_SPECIALIZED(name, dealloc).
//
// CPython: Tools/cases_generator/generators_common.py:307-335 Emitter.stackref_close_specialized
func (e *Emitter) StackrefCloseSpecialized(
	tkn Token, it *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	e.Out.Emit(tkn)
	lp, ok := it.Next()
	if !ok || lp.Kind != TokLParen {
		return false, analysisError("Expected '(' after PyStackRef_CLOSE_SPECIALIZED", tkn)
	}
	e.Out.Emit(lp)
	name, ok := it.Next()
	if !ok {
		return false, analysisError("Expected identifier", tkn)
	}
	e.Out.Emit(name)
	comma, ok := it.Next()
	if !ok || comma.Kind != TokComma {
		return false, analysisError("Expected comma", comma)
	}
	e.Out.Emit(comma)
	dealloc, ok := it.Next()
	if !ok || dealloc.Kind != TokIdentifier {
		return false, analysisError("Expected identifier", dealloc)
	}
	e.Out.Emit(dealloc)
	if name.Kind == TokIdentifier {
		_, escapes := nonEscapingDeallocs[dealloc.Text]
		return e.stackrefKill(name, storage, !escapes)
	}
	rparen, err := emitTo(e.Out, it, TokRParen)
	if err != nil {
		return false, err
	}
	e.Emit(rparen)
	return true, nil
}

// StackrefSteal handles PyStackRef_AsPyObjectSteal(name).
//
// CPython: Tools/cases_generator/generators_common.py:337-355 Emitter.stackref_steal
func (e *Emitter) StackrefSteal(
	tkn Token, it *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	e.Out.Emit(tkn)
	lp, ok := it.Next()
	if !ok || lp.Kind != TokLParen {
		return false, analysisError("Expected '(' after PyStackRef_AsPyObjectSteal", tkn)
	}
	e.Out.Emit(lp)
	name, ok := it.Next()
	if !ok {
		return false, analysisError("Expected identifier", tkn)
	}
	e.Out.Emit(name)
	if name.Kind == TokIdentifier {
		return e.stackrefKill(name, storage, false)
	}
	rparen, err := emitTo(e.Out, it, TokRParen)
	if err != nil {
		return false, err
	}
	e.Emit(rparen)
	return true, nil
}

// SyncSp handles SYNC_SP(); flushing storage and clearing the stash.
//
// CPython: Tools/cases_generator/generators_common.py:357-371 Emitter.sync_sp
func (e *Emitter) SyncSp(
	tkn Token, it *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	for i := 0; i < 3; i++ {
		if _, ok := it.Next(); !ok {
			return false, analysisError("Truncated SYNC_SP", tkn)
		}
	}
	if err := storage.ClearInputs("when syncing stack"); err != nil {
		return false, err
	}
	if err := storage.Flush(e.Out); err != nil {
		return false, err
	}
	storage.Stack.Clear(e.Out)
	return true, nil
}

// StackPointer guards bare references to the stack_pointer identifier
// when storage is spilled.
//
// CPython: Tools/cases_generator/generators_common.py:373-384 Emitter.stack_pointer
func (e *Emitter) StackPointer(
	tkn Token, _ *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	if storage.Spilled != 0 {
		return false, analysisError("stack_pointer is invalid when stack is spilled to memory", tkn)
	}
	e.Emit(tkn)
	return true, nil
}

// gotoLabel emits JUMP_TO_LABEL(label), spilling first when required.
//
// CPython: Tools/cases_generator/generators_common.py:386-399 Emitter.gotoTknlabel
func (e *Emitter) gotoLabel(gotoTkn, label Token, storage *Storage) error {
	node, ok := e.Labels[label.Text]
	if !ok {
		return analysisError(fmt.Sprintf("Label '%s' does not exist", label.Text), label)
	}
	switch {
	case node.Spilled:
		if storage.Spilled == 0 {
			e.emitSave(storage)
		}
	case storage.Spilled != 0:
		return analysisError("Cannot jump from spilled label without reloading the stack pointer", gotoTkn)
	}
	e.Out.StartLine()
	e.Out.Emit("JUMP_TO_LABEL(")
	e.Out.Emit(label)
	e.Out.Emit(")")
	return nil
}

// emitSave flushes storage, then arms a spill edge.
//
// CPython: Tools/cases_generator/generators_common.py:401-403 Emitter.emit_save
func (e *Emitter) emitSave(storage *Storage) {
	_ = storage.Flush(e.Out)
	storage.Save(e.Out)
}

// SaveStack handles SAVE_STACK(); flushing+spilling.
//
// CPython: Tools/cases_generator/generators_common.py:405-417 Emitter.save_stack
func (e *Emitter) SaveStack(
	tkn Token, it *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	for i := 0; i < 3; i++ {
		if _, ok := it.Next(); !ok {
			return false, analysisError("Truncated SAVE_STACK", tkn)
		}
	}
	e.emitSave(storage)
	return true, nil
}

// emitReload pops a spill region.
//
// CPython: Tools/cases_generator/generators_common.py:419-420 Emitter.emit_reload
func (e *Emitter) emitReload(storage *Storage) error {
	return storage.Reload(e.Out)
}

// ReloadStack handles RELOAD_STACK(); pairing with SAVE_STACK.
//
// CPython: Tools/cases_generator/generators_common.py:422-434 Emitter.reload_stack
func (e *Emitter) ReloadStack(
	tkn Token, it *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	for i := 0; i < 3; i++ {
		if _, ok := it.Next(); !ok {
			return false, analysisError("Truncated RELOAD_STACK", tkn)
		}
	}
	if err := e.emitReload(storage); err != nil {
		return false, err
	}
	return true, nil
}

// InstructionSize substitutes uop.instruction_size for the macro.
//
// CPython: Tools/cases_generator/generators_common.py:436-447 Emitter.instruction_size
func (e *Emitter) InstructionSize(
	tkn Token, _ *TokenIterator, uop CodeSection, _ *Storage, _ *Instruction,
) (bool, error) {
	sz := uop.GetInstructionSize()
	if sz == nil {
		return false, analysisError(
			"The INSTRUCTION_SIZE macro requires uop.instruction_size to be set",
			tkn,
		)
	}
	e.Out.Emit(fmt.Sprintf(" %du ", *sz))
	return true, nil
}

// printStorage dumps the current storage as a comment when DEBUG is on.
//
// CPython: Tools/cases_generator/generators_common.py:449-454 Emitter._print_storage
func (e *Emitter) printStorage(reason string, storage *Storage) {
	if !debug {
		return
	}
	e.Out.StartLine()
	e.Emit(fmt.Sprintf("/* %s */\n", reason))
	e.Emit(storage.AsComment())
	e.Out.StartLine()
}

// emitStmt dispatches a statement to its specific emitter.
//
// CPython: Tools/cases_generator/generators_common.py:456-467 Emitter._emit_stmt
func (e *Emitter) emitStmt(
	stmt Stmt, uop CodeSection, storage *Storage, inst *Instruction,
) (bool, *Token, *Storage, error) {
	switch s := stmt.(type) {
	case *SimpleStmt:
		return e.emitSimpleStmt(s, uop, storage, inst)
	case *MacroIfStmt:
		return e.emitMacroIfStmt(s, uop, storage, inst)
	case *IfStmt:
		return e.emitIfStmt(s, uop, storage, inst)
	case *BlockStmt:
		return e.emitBlockStmt(s, uop, storage, inst, true)
	case *ForStmt:
		return e.emitForStmt(s, uop, storage, inst)
	case *WhileStmt:
		return e.emitWhileStmt(s, uop, storage, inst)
	}
	return false, nil, storage, fmt.Errorf("emitStmt: unsupported %T", stmt)
}

// emitSimpleStmt walks the tokens of a simple statement, dispatching
// each recognized identifier through the replacement registry.
//
// CPython: Tools/cases_generator/generators_common.py:469-521 Emitter.emit_SimpleStmt
func (e *Emitter) emitSimpleStmt(
	stmt *SimpleStmt, uop CodeSection, storage *Storage, inst *Instruction,
) (bool, *Token, *Storage, error) {
	localStores := map[Token]struct{}{}
	for _, t := range uop.GetLocalStores() {
		localStores[t] = struct{}{}
	}
	reachable := true
	var lastTkn Token
	if len(stmt.Contents) > 0 {
		lastTkn = stmt.Contents[len(stmt.Contents)-1]
	}
	props := uop.GetProperties()
	if escape, ok := props.EscapingCalls[stmt]; ok {
		if escape.Kills != nil {
			if _, err := e.stackrefKill(*escape.Kills, storage, true); err != nil {
				return false, nil, storage, err
			}
		}
		e.emitSave(storage)
	}
	it := NewTokenIterator(stmt.Contents)
	for {
		tkn, ok := it.Next()
		if !ok {
			break
		}
		lastTkn = tkn
		switch tkn.Kind {
		case TokGoto:
			labelTkn, ok := it.Next()
			if !ok {
				return false, nil, storage, analysisError("Expected label after goto", tkn)
			}
			if err := e.gotoLabel(tkn, labelTkn, storage); err != nil {
				return false, nil, storage, err
			}
			reachable = false
		case TokReturn:
			e.Emit(tkn)
			semi, err := emitTo(e.Out, it, TokSemi)
			if err != nil {
				return false, nil, storage, err
			}
			e.Emit(semi)
			reachable = false
		case TokIdentifier:
			if fn, ok := e.replacers[tkn.Text]; ok {
				ok2, err := fn(tkn, it, uop, storage, inst)
				if err != nil {
					var se *StackError
					if errors.As(err, &se) {
						return false, nil, storage, analysisError(se.Msg, tkn)
					}
					return false, nil, storage, err
				}
				if !ok2 {
					reachable = false
				}
			} else {
				if _, isStore := localStores[tkn]; isStore {
					for _, v := range storage.Inputs {
						if v.Name() == tkn.Text {
							v.InLocal = true
							v.MemoryOffset = nil
							break
						}
					}
					for _, v := range storage.Outputs {
						if v.Name() == tkn.Text {
							v.InLocal = true
							v.MemoryOffset = nil
							break
						}
					}
				}
				if strings.HasPrefix(tkn.Text, "DISPATCH") {
					reachable = false
				}
				e.Out.Emit(tkn)
			}
		default:
			e.Out.Emit(tkn)
		}
	}
	if _, ok := props.EscapingCalls[stmt]; ok {
		if err := e.emitReload(storage); err != nil {
			var se *StackError
			if errors.As(err, &se) {
				return false, nil, storage, analysisError(se.Msg, lastTkn)
			}
			return false, nil, storage, err
		}
	}
	return reachable, nil, storage, nil
}

// emitMacroIfStmt walks both arms of a #if and merges the resulting storages.
//
// CPython: Tools/cases_generator/generators_common.py:524-555 Emitter.emit_MacroIfStmt
func (e *Emitter) emitMacroIfStmt(
	stmt *MacroIfStmt, uop CodeSection, storage *Storage, inst *Instruction,
) (bool, *Token, *Storage, error) {
	e.Out.Emit(stmt.Condition)
	branch := stmt.Else != nil
	reachable := true
	var elseStorage *Storage
	if branch {
		elseStorage = storage.Copy()
	}
	for _, s := range stmt.Body {
		r, tkn, st, err := e.emitStmt(s, uop, storage, inst)
		if err != nil {
			return false, nil, storage, err
		}
		storage = st
		if tkn != nil {
			e.Out.Emit(*tkn)
		}
		if !r {
			reachable = false
		}
	}
	if branch {
		e.Out.Emit(*stmt.Else)
		for _, s := range stmt.ElseBody {
			r, tkn, st, err := e.emitStmt(s, uop, elseStorage, inst)
			if err != nil {
				return false, nil, storage, err
			}
			elseStorage = st
			if tkn != nil {
				e.Out.Emit(*tkn)
			}
			if !r {
				reachable = false
			}
		}
		if err := elseStorage.Merge(storage, e.Out); err != nil {
			return false, nil, storage, err
		}
		storage = elseStorage
	}
	e.Out.Emit(stmt.Endif)
	return reachable, nil, storage, nil
}

// emitIfStmt rewrites an if/else with merged storage at the join.
//
// CPython: Tools/cases_generator/generators_common.py:558-597 Emitter.emit_IfStmt
func (e *Emitter) emitIfStmt(
	stmt *IfStmt, uop CodeSection, storage *Storage, inst *Instruction,
) (bool, *Token, *Storage, error) {
	e.Out.Emit(stmt.If)
	for _, t := range stmt.Condition {
		e.Out.Emit(t)
	}
	ifStorage := storage.Copy()
	rbrace := &stmt.If
	reachable, rb, ifStorage2, err := e.emitStmt(stmt.Body, uop, ifStorage, inst)
	if err != nil {
		return false, rb, storage, err
	}
	if rb != nil {
		rbrace = rb
	}
	ifStorage = ifStorage2
	if stmt.Else != nil {
		e.Out.Emit(*rbrace)
		e.Out.Emit(*stmt.Else)
	}
	if stmt.ElseBody != nil {
		elseReachable, rb2, elseStorage, err := e.emitStmt(stmt.ElseBody, uop, storage, inst)
		if err != nil {
			return false, rb2, storage, err
		}
		if rb2 != nil {
			rbrace = rb2
		}
		switch {
		case !reachable:
			reachable = elseReachable
			storage = elseStorage
		case !elseReachable:
			storage = ifStorage
		default:
			if err := elseStorage.Merge(ifStorage, e.Out); err != nil {
				return false, rbrace, storage, err
			}
			storage = elseStorage
		}
	} else {
		if reachable {
			if err := ifStorage.Merge(storage, e.Out); err != nil {
				return false, rbrace, storage, err
			}
			storage = ifStorage
		} else {
			reachable = true
		}
	}
	return reachable, rbrace, storage, nil
}

// emitBlockStmt walks a brace-delimited body, optionally emitting the braces.
//
// CPython: Tools/cases_generator/generators_common.py:599-623 Emitter.emit_BlockStmt
func (e *Emitter) emitBlockStmt(
	stmt *BlockStmt, uop CodeSection, storage *Storage, inst *Instruction, emitBraces bool,
) (bool, *Token, *Storage, error) {
	if emitBraces {
		e.Out.Emit(stmt.Open)
	}
	reachable := true
	for _, s := range stmt.Body {
		r, tkn, st, err := e.emitStmt(s, uop, storage, inst)
		if err != nil {
			return false, &stmt.Close, storage, err
		}
		storage = st
		if tkn != nil {
			e.Out.Emit(*tkn)
		}
		if !r {
			reachable = false
			break
		}
	}
	closeTok := stmt.Close
	return reachable, &closeTok, storage, nil
}

// emitForStmt walks the header tokens then descends into the body.
//
// CPython: Tools/cases_generator/generators_common.py:625-636 Emitter.emit_ForStmt
func (e *Emitter) emitForStmt(
	stmt *ForStmt, uop CodeSection, storage *Storage, inst *Instruction,
) (bool, *Token, *Storage, error) {
	e.Out.Emit(stmt.For)
	for _, t := range stmt.Header {
		e.Out.Emit(t)
	}
	return e.emitStmt(stmt.Body, uop, storage, inst)
}

// emitWhileStmt walks the condition then descends into the body.
//
// CPython: Tools/cases_generator/generators_common.py:638-649 Emitter.emit_WhileStmt
func (e *Emitter) emitWhileStmt(
	stmt *WhileStmt, uop CodeSection, storage *Storage, inst *Instruction,
) (bool, *Token, *Storage, error) {
	e.Out.Emit(stmt.While)
	for _, t := range stmt.Condition {
		e.Out.Emit(t)
	}
	return e.emitStmt(stmt.Body, uop, storage, inst)
}

// EmitTokens is the entrypoint that rewrites a CodeSection's body.
//
// CPython: Tools/cases_generator/generators_common.py:652-669 Emitter.emit_tokens
func (e *Emitter) EmitTokens(
	code CodeSection, storage *Storage, inst *Instruction, emitBraces bool,
) (bool, *Storage, error) {
	e.Out.StartLine()
	reachable, tkn, storage, err := e.emitBlockStmt(code.GetBody(), code, storage, inst, emitBraces)
	if err != nil {
		return false, storage, err
	}
	if tkn == nil {
		return false, storage, fmt.Errorf("emit_tokens: missing closing brace")
	}
	if reachable {
		if err := storage.PushOutputs(); err != nil {
			var se *StackError
			if errors.As(err, &se) {
				return false, storage, analysisError(se.Msg, *tkn)
			}
			return false, storage, err
		}
	}
	if emitBraces {
		e.Out.Emit(*tkn)
	}
	return reachable, storage, nil
}

// CFlags renders the C flags string for a Properties bag, mirroring
// the upstream cflags() helper.
//
// CPython: Tools/cases_generator/generators_common.py:675-708 cflags
func CFlags(p *Properties) string {
	var flags []string
	if p.Oparg {
		flags = append(flags, "HAS_ARG_FLAG")
	}
	if p.UsesCoConsts {
		flags = append(flags, "HAS_CONST_FLAG")
	}
	if p.UsesCoNames {
		flags = append(flags, "HAS_NAME_FLAG")
	}
	if p.Jumps {
		flags = append(flags, "HAS_JUMP_FLAG")
	}
	if p.HasFree {
		flags = append(flags, "HAS_FREE_FLAG")
	}
	if p.UsesLocals {
		flags = append(flags, "HAS_LOCAL_FLAG")
	}
	if p.EvalBreaker {
		flags = append(flags, "HAS_EVAL_BREAK_FLAG")
	}
	if p.Deopts {
		flags = append(flags, "HAS_DEOPT_FLAG")
	}
	if p.SideExit {
		flags = append(flags, "HAS_EXIT_FLAG")
	}
	if !p.Infallible() {
		flags = append(flags, "HAS_ERROR_FLAG")
	}
	if p.ErrorWithoutPop {
		flags = append(flags, "HAS_ERROR_NO_POP_FLAG")
	}
	if p.Escapes {
		flags = append(flags, "HAS_ESCAPES_FLAG")
	}
	if p.Pure {
		flags = append(flags, "HAS_PURE_FLAG")
	}
	if p.NoSaveIP {
		flags = append(flags, "HAS_NO_SAVE_IP_FLAG")
	}
	if len(flags) == 0 {
		return "0"
	}
	return strings.Join(flags, " | ")
}
