// Emitter for optimizer/uop_ids_gen.go. Walks the parsed UopID list
// and produces a Go const block. Numeric uops emit as plain uint16
// literals; aliased uops emit as `uint16(compile.NAME)` so the Go
// constant evaluates to the same value the C alias would expand to
// (the Tier-1 opcode value).
//
// CPython: Tools/cases_generator/uop_id_generator.py output preamble

package main

import (
	"fmt"
	"strings"
)

// pascal converts an UPPER_SNAKE name to UpperCamelCase. Numeric
// suffixes are joined directly (LOAD_FAST_0 -> LoadFast0).
func pascal(s string) string {
	var b strings.Builder
	for _, part := range strings.Split(s, "_") {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(strings.ToLower(part[1:]))
	}
	return b.String()
}

// EmitIDsFile renders the uop ID const block for pkg, with hash
// stamped in the preamble for drift checking.
func EmitIDsFile(pkg, hash string, ids []UopID, maxID uint16) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/uops_gen. DO NOT EDIT.\n")
	b.WriteString(MarkerLine(hash))
	b.WriteString("\npackage " + pkg + "\n\n")
	b.WriteString("import \"github.com/tamnd/gopy/compile\"\n\n")
	b.WriteString("// Tier-2 micro-op IDs. Numeric IDs (>= 300) name uops the Tier-2\n")
	b.WriteString("// dispatch loop owns; aliased IDs reuse the Tier-1 opcode value so\n")
	b.WriteString("// the trace projection can copy a Tier-1 instruction into the\n")
	b.WriteString("// trace without remapping.\n")
	b.WriteString("//\n")
	b.WriteString("// CPython: Include/internal/pycore_uop_ids.h\n")
	b.WriteString("const (\n")
	for _, id := range ids {
		name := "Uop" + pascal(id.Name)
		if id.IsAlias {
			fmt.Fprintf(&b, "\t%s uint16 = uint16(compile.%s)\n", name, id.Alias)
		} else {
			fmt.Fprintf(&b, "\t%s uint16 = %d\n", name, id.Value)
		}
	}
	fmt.Fprintf(&b, "\tMaxUopID uint16 = %d\n", maxID)
	b.WriteString(")\n\n")

	b.WriteString("// UopNames maps a uop ID to its CPython spelling. The dispatch and\n")
	b.WriteString("// disassembly paths use this to render trace rows with the same uop\n")
	b.WriteString("// names dis.dis emits upstream.\n")
	b.WriteString("var UopNames = map[uint16]string{\n")
	for _, id := range ids {
		fmt.Fprintf(&b, "\tUop%s: %q,\n", pascal(id.Name), "_"+id.Name)
	}
	b.WriteString("}\n")
	return b.String()
}
