// Emitter for optimizer/uop_meta_gen.go. Renders the per-uop flag
// bitmask, replication count, and the popped-stack-effect switch as a
// Go map keyed by uop name. The optimizer's analysis pass and the
// trace projection both read this table.
//
// CPython: Tools/cases_generator/uop_metadata_generator.py output
// preamble

package main

import (
	"fmt"
	"sort"
	"strings"
)

// EmitMetaFile renders the metadata table for pkg, with hash stamped
// in the preamble. Only entries that actually carry a flag, a
// replication count, or a popped expression appear in the output.
func EmitMetaFile(pkg, hash string, meta map[string]*UopMeta) string {
	names := make([]string, 0, len(meta))
	for k := range meta {
		names = append(names, k)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by tools/uops_gen. DO NOT EDIT.\n")
	b.WriteString(MarkerLine(hash))
	b.WriteString("\npackage " + pkg + "\n\n")
	b.WriteString("// UopFlag is the flag bitmask the analysis pass reads to learn how a\n")
	b.WriteString("// uop affects program state. Bit positions match the order in\n")
	b.WriteString("// pycore_uop_metadata.h's HAS_*_FLAG enum.\n")
	b.WriteString("//\n")
	b.WriteString("// CPython: Include/internal/pycore_uop_metadata.h HAS_*_FLAG\n")
	b.WriteString("type UopFlag uint16\n\n")
	b.WriteString("const (\n")
	for i, f := range knownFlags {
		fmt.Fprintf(&b, "\tFlag%s UopFlag = 1 << %d\n", pascal(f), i)
	}
	b.WriteString(")\n\n")

	b.WriteString("// UopMetaEntry is one row of the uop metadata table.\n")
	b.WriteString("type UopMetaEntry struct {\n")
	b.WriteString("\tFlags       UopFlag\n")
	b.WriteString("\tReplication uint8\n")
	b.WriteString("\tPopped      int8 // -1 when oparg-dependent or absent\n")
	b.WriteString("}\n\n")

	b.WriteString("// UopMeta maps a uop name (with leading underscore stripped) to its\n")
	b.WriteString("// static metadata. Lookup is by name rather than ID so the table\n")
	b.WriteString("// stays robust against ID renumbering across CPython releases.\n")
	b.WriteString("var UopMeta = map[string]UopMetaEntry{\n")
	for _, name := range names {
		m := meta[name]
		flags := emitFlagExpr(m.Flags)
		popped := emitPopped(m)
		fmt.Fprintf(&b, "\t%q: {Flags: %s, Replication: %d, Popped: %s},\n",
			"_"+name, flags, m.Replication, popped)
	}
	b.WriteString("}\n")
	return b.String()
}

// knownFlags is the canonical order of HAS_*_FLAG values from
// pycore_opcode_metadata.h. Bit positions follow the order so the
// generated FlagX constants stay stable across runs.
var knownFlags = []string{
	"ARG", "CONST", "NAME", "JUMP", "FREE", "LOCAL",
	"EVAL_BREAK", "DEOPT", "ERROR", "ESCAPES", "EXIT",
	"PURE", "PASSTHROUGH", "OPARG_AND_1", "ERROR_NO_POP", "NO_SAVE_IP",
}

// emitFlagExpr builds a `Flag1 | Flag2` expression from the parsed
// flag tokens. Unknown flags are skipped (a flag that ships in CPython
// but lacks a Go-side mirror should not break the generator).
func emitFlagExpr(flags []string) string {
	if len(flags) == 0 {
		return "0"
	}
	parts := make([]string, 0, len(flags))
	for _, f := range flags {
		if !contains(knownFlags, f) {
			continue
		}
		parts = append(parts, "Flag"+pascal(f))
	}
	if len(parts) == 0 {
		return "0"
	}
	return strings.Join(parts, " | ")
}

// emitPopped renders the popped-count column. CPython's switch returns
// either a literal int or an `oparg`-derived expression; for the
// latter we emit -1 and let the analysis pass compute the value at
// run time.
func emitPopped(m *UopMeta) string {
	if !m.HasPopped {
		return "0"
	}
	if n, ok := parseInt(m.Popped); ok {
		return fmt.Sprintf("%d", n)
	}
	return "-1"
}

func parseInt(s string) (int, bool) {
	s = strings.TrimSpace(s)
	n := 0
	if s == "" {
		return 0, false
	}
	for _, r := range s {
		if r < '0' || r > '9' {
			return 0, false
		}
		n = n*10 + int(r-'0')
	}
	return n, true
}

func contains(xs []string, s string) bool {
	for _, x := range xs {
		if x == s {
			return true
		}
	}
	return false
}
