// Tier-2 abstract-interpreter case generator: overlays optimizer_bytecodes.c onto bytecodes.c and emits one symbolic-execution stub per viable uop.
//
// CPython: Tools/cases_generator/optimizer_generator.py
package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// optimizerSkips mirrors the upstream SKIPS tuple: opcodes that have
// no symbolic body even though they survive the viability filter.
//
// CPython: Tools/cases_generator/optimizer_generator.py:159 SKIPS
var optimizerSkips = map[string]struct{}{
	"_EXTENDED_ARG": {},
}

// validateOptimizerUop is the upstream stub validate_uop: kept as a
// hook for future symbolic-vs-base sanity checks.
//
// CPython: Tools/cases_generator/optimizer_generator.py:32-34 validate_uop
func validateOptimizerUop(_ *Uop, _ *Uop) {}

// optimizerTypeName returns the C declaration prefix for a stack slot
// in the symbolic interpreter. Arrays become JitOptSymbol **, scalar
// items keep their explicit type, and the rest default to a single
// JitOptSymbol *.
//
// CPython: Tools/cases_generator/optimizer_generator.py:37-42 type_name
func optimizerTypeName(v *StackItem) string {
	switch {
	case v.IsArray():
		return "JitOptSymbol **"
	case v.Type != "":
		return v.Type
	default:
		return "JitOptSymbol *"
	}
}

// declareOptimizerVariables emits the local declarations for one uop's
// stack slots: inputs (when not skipped) followed by non-peek outputs.
//
// CPython: Tools/cases_generator/optimizer_generator.py:45-57 declare_variables
func declareOptimizerVariables(uop *Uop, out *CWriter, skipInputs bool) {
	seen := map[string]struct{}{"unused": {}}
	if !skipInputs {
		for i := len(uop.Stack.Inputs) - 1; i >= 0; i-- {
			v := uop.Stack.Inputs[i]
			if !v.Used {
				continue
			}
			if _, dup := seen[v.Name]; dup {
				continue
			}
			seen[v.Name] = struct{}{}
			out.Emit(fmt.Sprintf("%s%s;\n", optimizerTypeName(v), v.Name))
		}
	}
	for _, v := range uop.Stack.Outputs {
		if v.Peek {
			continue
		}
		if _, dup := seen[v.Name]; dup {
			continue
		}
		seen[v.Name] = struct{}{}
		out.Emit(fmt.Sprintf("%s%s;\n", optimizerTypeName(v), v.Name))
	}
}

// emitOptimizerDefault is the autogenerated symbolic body used when
// optimizer_bytecodes.c does not override a uop. It pops every input
// from the abstract stack and pushes one fresh symbol per output,
// honoring array shapes and the special "null" name.
//
// CPython: Tools/cases_generator/optimizer_generator.py:74-99 emit_default
func emitOptimizerDefault(out *CWriter, uop *Uop, stack *Stack) error {
	null := NullCWriter()
	for i := len(uop.Stack.Inputs) - 1; i >= 0; i-- {
		if _, err := stack.Pop(uop.Stack.Inputs[i], null); err != nil {
			return err
		}
	}
	offset := stack.BaseOffset.Sub(stack.PhysicalSp)
	for _, v := range uop.Stack.Outputs {
		if v.IsArray() && !v.Peek && v.Name != "unused" {
			out.Emit(fmt.Sprintf("%s = &stack_pointer[%s];\n", v.Name, offset.ToC()))
		}
		offset = offset.Push(v)
	}
	for _, v := range uop.Stack.Outputs {
		local := LocalUndefined(v)
		stack.Push(local)
		if v.Name == "unused" || v.Peek {
			continue
		}
		local.InLocal = true
		switch {
		case v.IsArray():
			if v.Size == "1" {
				out.Emit(fmt.Sprintf("%s[0] = sym_new_not_null(ctx);\n", v.Name))
			} else {
				out.Emit(fmt.Sprintf("for (int _i = %s; --_i >= 0;) {\n", v.Size))
				out.Emit(fmt.Sprintf("%s[_i] = sym_new_not_null(ctx);\n", v.Name))
				out.Emit("}\n")
			}
		case v.Name == "null":
			out.Emit(fmt.Sprintf("%s = sym_new_null(ctx);\n", v.Name))
		default:
			out.Emit(fmt.Sprintf("%s = sym_new_not_null(ctx);\n", v.Name))
		}
	}
	return nil
}

// OptimizerEmitter is the symbolic-interpreter Emitter subclass. It
// turns SAVE_STACK into a flush, drops RELOAD_STACK, and carries goto
// straight through (no JUMP_TO_LABEL rewrite).
//
// CPython: Tools/cases_generator/optimizer_generator.py:102-112 OptimizerEmitter
type OptimizerEmitter struct {
	*Emitter
}

// newOptimizerEmitter wraps a plain Emitter and overrides the entries
// that the abstract interpreter handles differently. Specifically it
// rebinds SAVE_STACK to flush-only (no spill counter), RELOAD_STACK to
// a no-op, and supplies its own goto handler.
//
// CPython: Tools/cases_generator/optimizer_generator.py:102-112 OptimizerEmitter
func newOptimizerEmitter(out *CWriter) *OptimizerEmitter {
	base := NewEmitter(out, map[string]*Label{})
	oe := &OptimizerEmitter{Emitter: base}
	base.SetReplacer("SAVE_STACK", oe.optimizerSaveStack)
	base.SetReplacer("RELOAD_STACK", oe.optimizerReloadStack)
	base.GotoLabelHook = func(gotoTkn, label Token, _ *Storage) error {
		base.Out.Emit(gotoTkn)
		base.Out.Emit(label)
		return nil
	}
	return oe
}

// optimizerSaveStack overrides emit_save: flush the storage but skip
// the spill counter, since the abstract interpreter never reloads.
//
// CPython: Tools/cases_generator/optimizer_generator.py:104-105 OptimizerEmitter.emit_save
//
//nolint:gocritic // hugeParam: matches the ReplacementFunc signature.
func (e *OptimizerEmitter) optimizerSaveStack(
	tkn Token, it *TokenIterator, _ CodeSection, storage *Storage, _ *Instruction,
) (bool, error) {
	for i := 0; i < 3; i++ {
		if _, ok := it.Next(); !ok {
			return false, analysisError("Truncated SAVE_STACK", tkn)
		}
	}
	if err := storage.Flush(e.Out); err != nil {
		return false, err
	}
	return true, nil
}

// optimizerReloadStack overrides emit_reload: the abstract interpreter
// has no reload step, so consume the macro and emit nothing.
//
// CPython: Tools/cases_generator/optimizer_generator.py:107-108 OptimizerEmitter.emit_reload
//
//nolint:gocritic // hugeParam: matches the ReplacementFunc signature.
func (e *OptimizerEmitter) optimizerReloadStack(
	tkn Token, it *TokenIterator, _ CodeSection, _ *Storage, _ *Instruction,
) (bool, error) {
	for i := 0; i < 3; i++ {
		if _, ok := it.Next(); !ok {
			return false, analysisError("Truncated RELOAD_STACK", tkn)
		}
	}
	return true, nil
}

// writeOptimizerUop emits the body for one uop case: when override is
// non-nil the symbolic DSL body wins, otherwise emit_default fires.
//
// CPython: Tools/cases_generator/optimizer_generator.py:114-156 write_uop
func writeOptimizerUop(
	override *Uop, uop *Uop, out *CWriter, stack *Stack, debug, skipInputs bool,
) error {
	prototype := uop
	if override != nil {
		prototype = override
	}
	out.StartLine()
	var storage *Storage
	if override != nil {
		var err error
		storage, err = StorageForUop(stack, prototype, out, false)
		if err != nil {
			return err
		}
	}
	if debug {
		args := make([]string, 0, len(prototype.Stack.Inputs))
		for _, in := range prototype.Stack.Inputs {
			if !in.Peek || override != nil {
				args = append(args, in.Name)
			}
		}
		out.Emit(fmt.Sprintf("DEBUG_PRINTF(%s);\n", strings.Join(args, ", ")))
	}
	if override != nil {
		for _, c := range uop.Caches {
			if c.Name == "unused" {
				continue
			}
			var ctype, cast string
			if c.Size == 4 {
				ctype = "PyObject *"
				cast = "PyObject *"
			} else {
				ctype = fmt.Sprintf("uint%d_t ", c.Size*16)
				cast = fmt.Sprintf("uint%d_t", c.Size*16)
			}
			out.Emit(fmt.Sprintf("%s%s = (%s)this_instr->operand0;\n", ctype, c.Name, cast))
		}
	}
	if override != nil {
		emitter := newOptimizerEmitter(out)
		for _, v := range storage.Inputs {
			v.InLocal = false
		}
		_, storage2, err := emitter.EmitTokens(override, storage, nil, false)
		if err != nil {
			return err
		}
		out.StartLine()
		if err := storage2.Flush(out); err != nil {
			return err
		}
		_ = skipInputs
		return nil
	}
	if err := emitOptimizerDefault(out, uop, stack); err != nil {
		return err
	}
	out.StartLine()
	stack.Flush(out)
	return nil
}

// optimizerOrderedUops returns base.Uops in a deterministic order so
// that the generated Go file is stable across runs.
func optimizerOrderedUops(base *Analysis) []*Uop {
	seen := make(map[string]struct{}, len(base.Uops))
	out := make([]*Uop, 0, len(base.Uops))
	for _, u := range base.Uops {
		if _, dup := seen[u.Name]; dup {
			continue
		}
		seen[u.Name] = struct{}{}
		out = append(out, u)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// shouldSkipForOptimizer mirrors the filter chain in
// generate_abstract_interpreter: tier-1, replicas, super-instructions,
// non-viable uops, and the explicit SKIPS tuple are dropped.
//
// CPython: Tools/cases_generator/optimizer_generator.py:178-191 generate_abstract_interpreter (filter)
func shouldSkipForOptimizer(uop *Uop) (bool, string) {
	if _, skip := optimizerSkips[uop.Name]; skip {
		return true, "skipped"
	}
	if uop.Properties != nil && uop.Properties.Tier == 1 {
		return true, "tier 1 only"
	}
	if uop.Replicates != nil {
		return true, "replica"
	}
	if uop.IsSuper() {
		return true, "super-instruction"
	}
	if reason := uop.WhyNotViable(); reason != "" {
		return true, reason
	}
	return false, ""
}

// GenerateOptimizer is the gopy entry point: it overlays
// override.Uops on base.Uops and emits one Go stub per viable uop,
// each carrying its rewritten symbolic-DSL body as a comment block.
// The shape matches the v0.12 plan: hand-written symbolic interpreter
// in optimizer/symbols.go will plug into the stubs once the lattice
// is fully wired.
//
// CPython: Tools/cases_generator/optimizer_generator.py:162-202 generate_abstract_interpreter
func GenerateOptimizer(
	base, override *Analysis, projectRoot string, out *bytes.Buffer,
) error {
	if base == nil {
		return fmt.Errorf("GenerateOptimizer: base analysis is nil")
	}
	if override == nil {
		override = &Analysis{Uops: map[string]*Uop{}}
	}
	// Match the upstream check: compare by Uop.Name, not the dict key.
	// desugar_inst stores synthetic uops under inst.name (no underscore)
	// but their Uop.Name carries the leading underscore.
	baseNames := make(map[string]struct{}, len(base.Uops))
	for _, u := range base.Uops {
		baseNames[u.Name] = struct{}{}
	}
	for _, u := range override.Uops {
		if _, ok := baseNames[u.Name]; !ok {
			return fmt.Errorf(
				"all abstract uops should override base uops, but %s is not", u.Name,
			)
		}
	}

	out.WriteString("// Code generated; DO NOT EDIT.\n")
	out.WriteString("// Source: Python/bytecodes.c overlaid with Python/optimizer_bytecodes.c\n")
	out.WriteString("\n")
	out.WriteString("package optimizer\n\n")
	_ = projectRoot

	overrideByName := make(map[string]*Uop, len(override.Uops))
	for _, u := range override.Uops {
		overrideByName[u.Name] = u
	}
	for _, uop := range optimizerOrderedUops(base) {
		if skip, reason := shouldSkipForOptimizer(uop); skip {
			fmt.Fprintf(out, "// %s skipped: %s\n\n", uop.Name, reason)
			continue
		}
		var override2 *Uop
		if o, ok := overrideByName[uop.Name]; ok {
			override2 = o
			validateOptimizerUop(o, uop)
		}
		if err := emitOneOptimizerStub(out, uop, override2, projectRoot); err != nil {
			return fmt.Errorf("emit %s: %w", uop.Name, err)
		}
	}
	return nil
}

// emitOneOptimizerStub renders one uop case as a Go function plus a
// /* C body */ comment block. The C body is produced by the same
// pipeline upstream uses to emit optimizer_cases.c.h: declare locals,
// dispatch the override's tokens through OptimizerEmitter, fall back
// to emit_default when no override exists.
//
// CPython: Tools/cases_generator/optimizer_generator.py:192-202 generate_abstract_interpreter (per-uop)
func emitOneOptimizerStub(
	out *bytes.Buffer, uop, override *Uop, _ string,
) error {
	var cbuf bytes.Buffer
	cw := NewCWriter(&cbuf, 2, false)
	cw.Emit(fmt.Sprintf("case %s: {\n", uop.Name))
	switch {
	case override != nil:
		declareOptimizerVariables(override, cw, false)
	default:
		declareOptimizerVariables(uop, cw, true)
	}
	stack := NewStackOpt(false, "JitOptSymbol *")
	if err := writeOptimizerUop(override, uop, cw, stack, false, override == nil); err != nil {
		return err
	}
	cw.StartLine()
	cw.Emit("break;\n")
	cw.Emit("}\n")

	hasOverride := override != nil
	tag := "default body"
	if hasOverride {
		tag = "override from optimizer_bytecodes.c"
	}
	fmt.Fprintf(out, "// %s: %s.\n", uop.Name, tag)
	fmt.Fprintf(out, "//\n")
	fmt.Fprintf(out, "/*\n%s*/\n", cbuf.String())
	fmt.Fprintf(out, "func op_%s() {}\n\n", uop.Name)
	return nil
}
