// Family + deopt emitter (B9 / spec 1714 phase 4). Walks the parsed
// bytecodes.c AST and produces a Go source file with the family
// table (parent -> []variants) and the inverse deopt map
// (variant -> parent). specialize/quicken.go and specialize/deopt.go
// consume these tables instead of carrying hand-rolled literals.
//
// CPython source of truth: family(...) declarations in
// Python/bytecodes.c that the upstream cases_generator folds into
// pycore_opcode_metadata.h _PyOpcode_Deopt[] and the per-family
// metadata arrays.

package main

import (
	"fmt"
	"sort"
	"strings"
)

// FamilyEntry is the per-parent fan-out: the parent opcode plus the
// list of specialized variants it deopts to. The variant list is the
// raw `family(PARENT, ...) = { ... }` membership minus the parent
// itself (some declarations list the parent alongside its variants).
type FamilyEntry struct {
	Parent   string
	Variants []string
}

// CollectFamilies returns one FamilyEntry per family() declaration in
// defs, in deterministic order. Variants are sorted alphabetically so
// the generated file is byte-stable across reorderings of the input.
//
// Mirrors CPython's analyzer.analyze_forest: BINARY_OP_INPLACE_ADD_UNICODE
// is grafted onto the BINARY_OP family even though it is commented out
// of the upstream family() declaration. The cases_generator does the
// same graft to keep _PyOpcode_Deopt[] honoring the historical deopt.
//
// CPython: Tools/cases_generator/analyzer.py:1167 analyze_forest
// (Special case BINARY_OP_INPLACE_ADD_UNICODE)
func CollectFamilies(defs []Def) []FamilyEntry {
	var out []FamilyEntry
	for _, d := range defs {
		f, ok := d.(*FamilyDef)
		if !ok {
			continue
		}
		variants := make([]string, 0, len(f.Members))
		for _, m := range f.Members {
			if m == f.Name {
				continue
			}
			variants = append(variants, m)
		}
		if f.Name == "BINARY_OP" && instructionExists(defs, "BINARY_OP_INPLACE_ADD_UNICODE") {
			variants = append(variants, "BINARY_OP_INPLACE_ADD_UNICODE")
		}
		sort.Strings(variants)
		out = append(out, FamilyEntry{Parent: f.Name, Variants: variants})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Parent < out[j].Parent })
	return out
}

// instructionExists reports whether defs declares an inst or macro with
// the given name. Used by the BINARY_OP_INPLACE_ADD_UNICODE graft so
// the special case stays self-disabling if the opcode is ever removed
// upstream.
func instructionExists(defs []Def, name string) bool {
	for _, d := range defs {
		switch v := d.(type) {
		case *InstDef:
			if v.Name == name {
				return true
			}
		case *MacroDef:
			if v.Name == name {
				return true
			}
		}
	}
	return false
}

// EmitFamilyFile renders the family table and deopt map. The target
// package is specialize and every opcode is referenced through the
// compile package, matching how specialize/deopt.go is shaped today.
func EmitFamilyFile(pkg, hash string, families []FamilyEntry) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/bytecodes_gen. DO NOT EDIT.\n")
	b.WriteString(MarkerLine(hash))
	b.WriteString("\npackage " + pkg + "\n\n")
	b.WriteString("import \"github.com/tamnd/gopy/compile\"\n\n")
	b.WriteString("// Family lists every specialized variant a parent opcode\n")
	b.WriteString("// can be specialized into. Emitted from family() declarations\n")
	b.WriteString("// in Python/bytecodes.c.\n")
	b.WriteString("//\n")
	b.WriteString("// CPython: Include/internal/pycore_opcode_metadata.h family arrays\n")
	b.WriteString("var Family = map[compile.Opcode][]compile.Opcode{\n")
	for _, f := range families {
		fmt.Fprintf(&b, "\tcompile.%s: {\n", f.Parent)
		for _, v := range f.Variants {
			fmt.Fprintf(&b, "\t\tcompile.%s,\n", v)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("// DeoptParent maps every specialized variant back to its\n")
	b.WriteString("// adaptive parent. The dispatch loop consults this table\n")
	b.WriteString("// when a fast-path arm hits a shape mismatch and must\n")
	b.WriteString("// fall back. Variants absent from any family are absent\n")
	b.WriteString("// from this map; specialize.Deopt treats those as fixed\n")
	b.WriteString("// points (op -> op).\n")
	b.WriteString("//\n")
	b.WriteString("// CPython: Include/internal/pycore_opcode_metadata.h _PyOpcode_Deopt\n")
	b.WriteString("var DeoptParent = map[compile.Opcode]compile.Opcode{\n")
	for _, f := range families {
		for _, v := range f.Variants {
			fmt.Fprintf(&b, "\tcompile.%s: compile.%s,\n", v, f.Parent)
		}
	}
	b.WriteString("}\n")
	return b.String()
}
