// Tier-1 emitter (B3). Renders one switch arm per real `inst` from
// the analyzed signatures. Body translation is the action translator's
// job (B6); until that lands every arm emits a panic-stub call so the
// generated file always compiles.
//
// CPython: Tools/cases_generator/tier1_generator.py.

package main

import (
	"fmt"
	"sort"
	"strings"
)

// EmitTier1Arm renders the `case opcode.NAME:` block for one analyzed
// instruction. Inputs are popped in reverse source order into named
// locals; outputs are pushed bottom-first. The action body is a
// panic-stub until B6 fills it in.
func EmitTier1Arm(a *SignatureAnalysis) string {
	var b strings.Builder
	fmt.Fprintf(&b, "\tcase compile.%s:\n", a.Name)

	// Pop inputs in reverse so source-order Inputs[0] ends up bound
	// to the deepest popped slot (matches CPython's stack-bottom-first
	// signature).
	for i := len(a.Inputs) - 1; i >= 0; i-- {
		in := a.Inputs[i]
		name := bindName(in.Name, "in", in.Index)
		if in.Sized {
			fmt.Fprintf(&b, "\t\t// sized input %s, size=%s\n", name, in.SizeExpr)
			fmt.Fprintf(&b, "\t\tfor i := 0; i < int(%s); i++ { _ = e.pop() }\n", in.SizeExpr)
			continue
		}
		fmt.Fprintf(&b, "\t\t%s := e.pop()\n", name)
		fmt.Fprintf(&b, "\t\t_ = %s\n", name)
	}

	// Cache reads: emit a comment so B6 can plug in real decoding.
	for _, c := range a.Caches {
		fmt.Fprintf(&b, "\t\t// cache %q size=%d offset=%d\n", c.Name, c.Size, c.Offset)
	}

	// Action body placeholder. B6 will replace this with the
	// translated body.
	fmt.Fprintf(&b, "\t\treturn 0, nil, nil, false, opcodeNotImplemented(op) // body pending (B6)\n")

	// Output pushes are unreachable until B6 fills the body, but emit
	// them in a dead block so the analysis stays visible to readers.
	if len(a.Outputs) > 0 {
		b.WriteString("\t\t// outputs:")
		for _, o := range a.Outputs {
			fmt.Fprintf(&b, " %s", bindName(o.Name, "out", o.Index))
			if o.Sized {
				fmt.Fprintf(&b, "[%s]", o.SizeExpr)
			}
		}
		b.WriteString("\n")
	}
	return b.String()
}

// bindName picks a stable Go identifier for a slot. Empty/unused names
// get a synthetic `_in0` / `_out1` so collisions across slots can't
// happen; Go keywords clash with the language and get a `_v` suffix;
// otherwise we use the source name directly.
func bindName(name, dir string, idx int) string {
	if name == "" || name == "unused" {
		return fmt.Sprintf("_%s%d", dir, idx)
	}
	if goKeywords[name] {
		return name + "_v"
	}
	return name
}

// goKeywords are the reserved identifiers we have to rename around.
// CPython names like `type`, `func`, `default`, `range` collide with
// Go's grammar and would not parse as variable names.
var goKeywords = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true,
	"continue": true, "default": true, "defer": true, "else": true,
	"fallthrough": true, "for": true, "func": true, "go": true,
	"goto": true, "if": true, "import": true, "interface": true,
	"map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true,
	"var": true,
}

// EmitTier1File renders a Go source file containing dispatchGen, which
// the hand-written dispatch falls back to once codegen takes over.
// `pkg` is the target package, `hash` is the bytecodes.c sha256 stamped
// in the drift marker. Adaptive variants in fm are skipped, since v0.6
// has no specializer; their base instruction handles dispatch and the
// adaptive opcode constants don't exist in compile/ yet.
func EmitTier1File(pkg, hash string, analyses []*SignatureAnalysis, fm FamilyMap) string {
	sorted := make([]*SignatureAnalysis, 0, len(analyses))
	for _, a := range analyses {
		if _, isVariant := fm[a.Name]; isVariant {
			continue
		}
		sorted = append(sorted, a)
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b strings.Builder
	b.WriteString("// Code generated by tools/bytecodes_gen. DO NOT EDIT.\n")
	b.WriteString(MarkerLine(hash))
	b.WriteString("\npackage " + pkg + "\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/tamnd/gopy/compile\"\n")
	b.WriteString("\t\"github.com/tamnd/gopy/objects\"\n")
	b.WriteString(")\n\n")
	b.WriteString("// dispatchGen is the generated Tier-1 dispatcher. Each arm is\n")
	b.WriteString("// produced from one `inst` in Python/bytecodes.c.\n")
	b.WriteString("func (e *evalState) dispatchGen(op compile.Opcode, oparg uint32) (next int, retVal objects.Object, retErr error, retDone bool, err error) {\n")
	b.WriteString("\t_ = oparg\n")
	b.WriteString("\tswitch op {\n")
	for _, a := range sorted {
		b.WriteString(EmitTier1Arm(a))
	}
	b.WriteString("\t}\n")
	b.WriteString("\treturn 0, nil, nil, false, opcodeNotImplemented(op)\n")
	b.WriteString("}\n")
	return b.String()
}
