// Command tokens_go generates tokenize/types_gen.go from CPython 3.14
// source.
//
// Inputs:
//   - $CPYTHON/Grammar/Tokens: token names plus optional literal
//     spelling.
//   - $CPYTHON/Include/internal/pycore_token.h: numeric values.
//   - $CPYTHON/Lib/token.py: ENCODING (the one extra token tokenize.py
//     adds on top of the C tokenizer's set).
//
// Output:
//   - <repo>/tokenize/types_gen.go: typed Type constants and the
//     tokenNames lookup table.
//
// Run with:
//
//	go run ./tools/tokens_go \
//	  -cpython=$HOME/cpython-314 \
//	  -out=tokenize/types_gen.go
//
// The CPython source is not vendored. The output file is checked in
// so the runtime build has no Python dependency.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

func main() {
	cpython := flag.String("cpython", "", "path to cpython source tree")
	out := flag.String("out", "", "output Go file")
	flag.Parse()
	if *cpython == "" || *out == "" {
		log.Fatal("both -cpython and -out required")
	}

	values, err := parseValues(filepath.Join(*cpython, "Include", "internal", "pycore_token.h"))
	if err != nil {
		log.Fatal(err)
	}
	enc, err := parseTokenPy(filepath.Join(*cpython, "Lib", "token.py"))
	if err != nil {
		log.Fatal(err)
	}
	for k, v := range enc {
		if _, dup := values[k]; !dup {
			values[k] = v
		}
	}

	src, err := emit(values)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// parseValues reads token name -> numeric value pairs out of
// pycore_token.h. The interesting subset is the leading run of
// `#define NAME N` lines before N_TOKENS / NT_OFFSET.
func parseValues(path string) (map[string]int, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	re := regexp.MustCompile(`^#define\s+([A-Z_0-9]+)\s+(\d+)\s*$`)
	out := map[string]int{}
	for line := range strings.SplitSeq(string(data), "\n") {
		m := re.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		name := m[1]
		if name == "N_TOKENS" || name == "NT_OFFSET" {
			continue
		}
		v, err := strconv.Atoi(m[2])
		if err != nil {
			return nil, err
		}
		out[name] = v
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("no #define entries in %s", path)
	}
	return out, nil
}

// parseTokenPy picks up tokens that exist only on the Python side of
// the tokenizer (notably ENCODING) by scanning Lib/token.py for
// `NAME = N` assignments.
func parseTokenPy(path string) (map[string]int, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	re := regexp.MustCompile(`^([A-Z_]+)\s*=\s*(\d+)\s*$`)
	skip := map[string]bool{"N_TOKENS": true, "NT_OFFSET": true, "ENCODING_OFFSET": true}
	out := map[string]int{}
	for line := range strings.SplitSeq(string(data), "\n") {
		m := re.FindStringSubmatch(line)
		if m == nil || skip[m[1]] {
			continue
		}
		v, err := strconv.Atoi(m[2])
		if err != nil {
			return nil, err
		}
		out[m[1]] = v
	}
	return out, nil
}

func emit(values map[string]int) ([]byte, error) {
	type entry struct {
		name string
		val  int
	}
	entries := make([]entry, 0, len(values))
	for k, v := range values {
		entries = append(entries, entry{k, v})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].val < entries[j].val })

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by tools/tokens_go from cpython/Grammar/Tokens and")
	fmt.Fprintln(&buf, "// cpython/Include/internal/pycore_token.h. DO NOT EDIT.")
	fmt.Fprintln(&buf, "//")
	fmt.Fprintln(&buf, "// CPython: Include/internal/pycore_token.h")
	fmt.Fprintln(&buf, "// CPython: Grammar/Tokens")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "package tokenize")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "const (")
	maxVal := 0
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t%s Type = %d\n", goName(e.name), e.val)
		if e.val > maxVal {
			maxVal = e.val
		}
	}
	fmt.Fprintf(&buf, "\tNTokens Type = %d\n", maxVal+1)
	fmt.Fprintln(&buf, ")")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "// tokenNames is indexed by Type. CPython parity with token.tok_name.")
	fmt.Fprintln(&buf, "var tokenNames = [...]string{")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t%s: %q,\n", goName(e.name), e.name)
	}
	fmt.Fprintln(&buf, "}")

	return format.Source(buf.Bytes())
}

// goName preserves CPython token spelling. All current tokens are
// upper-snake-case identifiers that map straight through.
func goName(name string) string { return name }
