// Code generated by tools/asdl_go. DO NOT EDIT.
// Source: cpython/Parser/Python.asdl

package ast

// Mod is the asdl `mod` sum.
type Mod interface {
	isMod()
}

// Module is the asdl `Module` node.
type Module struct {
	Body        Seq[Stmt]
	TypeIgnores Seq[TypeIgnore]
}

func (*Module) isMod() {}

// Interactive is the asdl `Interactive` node.
type Interactive struct {
	Body Seq[Stmt]
}

func (*Interactive) isMod() {}

// Expression is the asdl `Expression` node.
type Expression struct {
	Body Expr
}

func (*Expression) isMod() {}

// FunctionType is the asdl `FunctionType` node.
type FunctionType struct {
	Argtypes Seq[Expr]
	Returns  Expr
}

func (*FunctionType) isMod() {}

// Stmt is the asdl `stmt` sum.
type Stmt interface {
	isStmt()
	Position() Pos
}

// FunctionDef is the asdl `FunctionDef` node.
type FunctionDef struct {
	Name          string
	Args          *Arguments
	Body          Seq[Stmt]
	DecoratorList Seq[Expr]
	Returns       Expr
	TypeComment   *string
	TypeParams    Seq[TypeParam]
	Pos           Pos
}

func (*FunctionDef) isStmt() {}

// Position returns the source location.
func (n *FunctionDef) Position() Pos { return n.Pos }

// AsyncFunctionDef is the asdl `AsyncFunctionDef` node.
type AsyncFunctionDef struct {
	Name          string
	Args          *Arguments
	Body          Seq[Stmt]
	DecoratorList Seq[Expr]
	Returns       Expr
	TypeComment   *string
	TypeParams    Seq[TypeParam]
	Pos           Pos
}

func (*AsyncFunctionDef) isStmt() {}

// Position returns the source location.
func (n *AsyncFunctionDef) Position() Pos { return n.Pos }

// ClassDef is the asdl `ClassDef` node.
type ClassDef struct {
	Name          string
	Bases         Seq[Expr]
	Keywords      Seq[*Keyword]
	Body          Seq[Stmt]
	DecoratorList Seq[Expr]
	TypeParams    Seq[TypeParam]
	Pos           Pos
}

func (*ClassDef) isStmt() {}

// Position returns the source location.
func (n *ClassDef) Position() Pos { return n.Pos }

// Return is the asdl `Return` node.
type Return struct {
	Value Expr
	Pos   Pos
}

func (*Return) isStmt() {}

// Position returns the source location.
func (n *Return) Position() Pos { return n.Pos }

// Delete is the asdl `Delete` node.
type Delete struct {
	Targets Seq[Expr]
	Pos     Pos
}

func (*Delete) isStmt() {}

// Position returns the source location.
func (n *Delete) Position() Pos { return n.Pos }

// Assign is the asdl `Assign` node.
type Assign struct {
	Targets     Seq[Expr]
	Value       Expr
	TypeComment *string
	Pos         Pos
}

func (*Assign) isStmt() {}

// Position returns the source location.
func (n *Assign) Position() Pos { return n.Pos }

// TypeAlias is the asdl `TypeAlias` node.
type TypeAlias struct {
	Name       Expr
	TypeParams Seq[TypeParam]
	Value      Expr
	Pos        Pos
}

func (*TypeAlias) isStmt() {}

// Position returns the source location.
func (n *TypeAlias) Position() Pos { return n.Pos }

// AugAssign is the asdl `AugAssign` node.
type AugAssign struct {
	Target Expr
	Op     Operator
	Value  Expr
	Pos    Pos
}

func (*AugAssign) isStmt() {}

// Position returns the source location.
func (n *AugAssign) Position() Pos { return n.Pos }

// AnnAssign is the asdl `AnnAssign` node.
type AnnAssign struct {
	Target     Expr
	Annotation Expr
	Value      Expr
	Simple     int
	Pos        Pos
}

func (*AnnAssign) isStmt() {}

// Position returns the source location.
func (n *AnnAssign) Position() Pos { return n.Pos }

// For is the asdl `For` node.
type For struct {
	Target      Expr
	Iter        Expr
	Body        Seq[Stmt]
	Orelse      Seq[Stmt]
	TypeComment *string
	Pos         Pos
}

func (*For) isStmt() {}

// Position returns the source location.
func (n *For) Position() Pos { return n.Pos }

// AsyncFor is the asdl `AsyncFor` node.
type AsyncFor struct {
	Target      Expr
	Iter        Expr
	Body        Seq[Stmt]
	Orelse      Seq[Stmt]
	TypeComment *string
	Pos         Pos
}

func (*AsyncFor) isStmt() {}

// Position returns the source location.
func (n *AsyncFor) Position() Pos { return n.Pos }

// While is the asdl `While` node.
type While struct {
	Test   Expr
	Body   Seq[Stmt]
	Orelse Seq[Stmt]
	Pos    Pos
}

func (*While) isStmt() {}

// Position returns the source location.
func (n *While) Position() Pos { return n.Pos }

// If is the asdl `If` node.
type If struct {
	Test   Expr
	Body   Seq[Stmt]
	Orelse Seq[Stmt]
	Pos    Pos
}

func (*If) isStmt() {}

// Position returns the source location.
func (n *If) Position() Pos { return n.Pos }

// With is the asdl `With` node.
type With struct {
	Items       Seq[*Withitem]
	Body        Seq[Stmt]
	TypeComment *string
	Pos         Pos
}

func (*With) isStmt() {}

// Position returns the source location.
func (n *With) Position() Pos { return n.Pos }

// AsyncWith is the asdl `AsyncWith` node.
type AsyncWith struct {
	Items       Seq[*Withitem]
	Body        Seq[Stmt]
	TypeComment *string
	Pos         Pos
}

func (*AsyncWith) isStmt() {}

// Position returns the source location.
func (n *AsyncWith) Position() Pos { return n.Pos }

// Match is the asdl `Match` node.
type Match struct {
	Subject Expr
	Cases   Seq[*MatchCase]
	Pos     Pos
}

func (*Match) isStmt() {}

// Position returns the source location.
func (n *Match) Position() Pos { return n.Pos }

// Raise is the asdl `Raise` node.
type Raise struct {
	Exc   Expr
	Cause Expr
	Pos   Pos
}

func (*Raise) isStmt() {}

// Position returns the source location.
func (n *Raise) Position() Pos { return n.Pos }

// Try is the asdl `Try` node.
type Try struct {
	Body      Seq[Stmt]
	Handlers  Seq[Excepthandler]
	Orelse    Seq[Stmt]
	Finalbody Seq[Stmt]
	Pos       Pos
}

func (*Try) isStmt() {}

// Position returns the source location.
func (n *Try) Position() Pos { return n.Pos }

// TryStar is the asdl `TryStar` node.
type TryStar struct {
	Body      Seq[Stmt]
	Handlers  Seq[Excepthandler]
	Orelse    Seq[Stmt]
	Finalbody Seq[Stmt]
	Pos       Pos
}

func (*TryStar) isStmt() {}

// Position returns the source location.
func (n *TryStar) Position() Pos { return n.Pos }

// Assert is the asdl `Assert` node.
type Assert struct {
	Test Expr
	Msg  Expr
	Pos  Pos
}

func (*Assert) isStmt() {}

// Position returns the source location.
func (n *Assert) Position() Pos { return n.Pos }

// Import is the asdl `Import` node.
type Import struct {
	Names Seq[*Alias]
	Pos   Pos
}

func (*Import) isStmt() {}

// Position returns the source location.
func (n *Import) Position() Pos { return n.Pos }

// ImportFrom is the asdl `ImportFrom` node.
type ImportFrom struct {
	Module *string
	Names  Seq[*Alias]
	Level  *int
	Pos    Pos
}

func (*ImportFrom) isStmt() {}

// Position returns the source location.
func (n *ImportFrom) Position() Pos { return n.Pos }

// Global is the asdl `Global` node.
type Global struct {
	Names Seq[string]
	Pos   Pos
}

func (*Global) isStmt() {}

// Position returns the source location.
func (n *Global) Position() Pos { return n.Pos }

// Nonlocal is the asdl `Nonlocal` node.
type Nonlocal struct {
	Names Seq[string]
	Pos   Pos
}

func (*Nonlocal) isStmt() {}

// Position returns the source location.
func (n *Nonlocal) Position() Pos { return n.Pos }

// ExprStmt is the asdl `ExprStmt` node.
type ExprStmt struct {
	Value Expr
	Pos   Pos
}

func (*ExprStmt) isStmt() {}

// Position returns the source location.
func (n *ExprStmt) Position() Pos { return n.Pos }

// Pass is the asdl `Pass` node.
type Pass struct {
	Pos Pos
}

func (*Pass) isStmt() {}

// Position returns the source location.
func (n *Pass) Position() Pos { return n.Pos }

// Break is the asdl `Break` node.
type Break struct {
	Pos Pos
}

func (*Break) isStmt() {}

// Position returns the source location.
func (n *Break) Position() Pos { return n.Pos }

// Continue is the asdl `Continue` node.
type Continue struct {
	Pos Pos
}

func (*Continue) isStmt() {}

// Position returns the source location.
func (n *Continue) Position() Pos { return n.Pos }

// Expr is the asdl `expr` sum.
type Expr interface {
	isExpr()
	Position() Pos
}

// BoolOp is the asdl `BoolOp` node.
type BoolOp struct {
	Op     Boolop
	Values Seq[Expr]
	Pos    Pos
}

func (*BoolOp) isExpr() {}

// Position returns the source location.
func (n *BoolOp) Position() Pos { return n.Pos }

// NamedExpr is the asdl `NamedExpr` node.
type NamedExpr struct {
	Target Expr
	Value  Expr
	Pos    Pos
}

func (*NamedExpr) isExpr() {}

// Position returns the source location.
func (n *NamedExpr) Position() Pos { return n.Pos }

// BinOp is the asdl `BinOp` node.
type BinOp struct {
	Left  Expr
	Op    Operator
	Right Expr
	Pos   Pos
}

func (*BinOp) isExpr() {}

// Position returns the source location.
func (n *BinOp) Position() Pos { return n.Pos }

// UnaryOp is the asdl `UnaryOp` node.
type UnaryOp struct {
	Op      Unaryop
	Operand Expr
	Pos     Pos
}

func (*UnaryOp) isExpr() {}

// Position returns the source location.
func (n *UnaryOp) Position() Pos { return n.Pos }

// Lambda is the asdl `Lambda` node.
type Lambda struct {
	Args *Arguments
	Body Expr
	Pos  Pos
}

func (*Lambda) isExpr() {}

// Position returns the source location.
func (n *Lambda) Position() Pos { return n.Pos }

// IfExp is the asdl `IfExp` node.
type IfExp struct {
	Test   Expr
	Body   Expr
	Orelse Expr
	Pos    Pos
}

func (*IfExp) isExpr() {}

// Position returns the source location.
func (n *IfExp) Position() Pos { return n.Pos }

// Dict is the asdl `Dict` node.
type Dict struct {
	Keys   Seq[Expr]
	Values Seq[Expr]
	Pos    Pos
}

func (*Dict) isExpr() {}

// Position returns the source location.
func (n *Dict) Position() Pos { return n.Pos }

// Set is the asdl `Set` node.
type Set struct {
	Elts Seq[Expr]
	Pos  Pos
}

func (*Set) isExpr() {}

// Position returns the source location.
func (n *Set) Position() Pos { return n.Pos }

// ListComp is the asdl `ListComp` node.
type ListComp struct {
	Elt        Expr
	Generators Seq[*Comprehension]
	Pos        Pos
}

func (*ListComp) isExpr() {}

// Position returns the source location.
func (n *ListComp) Position() Pos { return n.Pos }

// SetComp is the asdl `SetComp` node.
type SetComp struct {
	Elt        Expr
	Generators Seq[*Comprehension]
	Pos        Pos
}

func (*SetComp) isExpr() {}

// Position returns the source location.
func (n *SetComp) Position() Pos { return n.Pos }

// DictComp is the asdl `DictComp` node.
type DictComp struct {
	Key        Expr
	Value      Expr
	Generators Seq[*Comprehension]
	Pos        Pos
}

func (*DictComp) isExpr() {}

// Position returns the source location.
func (n *DictComp) Position() Pos { return n.Pos }

// GeneratorExp is the asdl `GeneratorExp` node.
type GeneratorExp struct {
	Elt        Expr
	Generators Seq[*Comprehension]
	Pos        Pos
}

func (*GeneratorExp) isExpr() {}

// Position returns the source location.
func (n *GeneratorExp) Position() Pos { return n.Pos }

// Await is the asdl `Await` node.
type Await struct {
	Value Expr
	Pos   Pos
}

func (*Await) isExpr() {}

// Position returns the source location.
func (n *Await) Position() Pos { return n.Pos }

// Yield is the asdl `Yield` node.
type Yield struct {
	Value Expr
	Pos   Pos
}

func (*Yield) isExpr() {}

// Position returns the source location.
func (n *Yield) Position() Pos { return n.Pos }

// YieldFrom is the asdl `YieldFrom` node.
type YieldFrom struct {
	Value Expr
	Pos   Pos
}

func (*YieldFrom) isExpr() {}

// Position returns the source location.
func (n *YieldFrom) Position() Pos { return n.Pos }

// Compare is the asdl `Compare` node.
type Compare struct {
	Left        Expr
	Ops         Seq[Cmpop]
	Comparators Seq[Expr]
	Pos         Pos
}

func (*Compare) isExpr() {}

// Position returns the source location.
func (n *Compare) Position() Pos { return n.Pos }

// Call is the asdl `Call` node.
type Call struct {
	Func     Expr
	Args     Seq[Expr]
	Keywords Seq[*Keyword]
	Pos      Pos
}

func (*Call) isExpr() {}

// Position returns the source location.
func (n *Call) Position() Pos { return n.Pos }

// FormattedValue is the asdl `FormattedValue` node.
type FormattedValue struct {
	Value      Expr
	Conversion int
	FormatSpec Expr
	Pos        Pos
}

func (*FormattedValue) isExpr() {}

// Position returns the source location.
func (n *FormattedValue) Position() Pos { return n.Pos }

// Interpolation is the asdl `Interpolation` node.
type Interpolation struct {
	Value      Expr
	Str        any
	Conversion int
	FormatSpec Expr
	Pos        Pos
}

func (*Interpolation) isExpr() {}

// Position returns the source location.
func (n *Interpolation) Position() Pos { return n.Pos }

// JoinedStr is the asdl `JoinedStr` node.
type JoinedStr struct {
	Values Seq[Expr]
	Pos    Pos
}

func (*JoinedStr) isExpr() {}

// Position returns the source location.
func (n *JoinedStr) Position() Pos { return n.Pos }

// TemplateStr is the asdl `TemplateStr` node.
type TemplateStr struct {
	Values Seq[Expr]
	Pos    Pos
}

func (*TemplateStr) isExpr() {}

// Position returns the source location.
func (n *TemplateStr) Position() Pos { return n.Pos }

// Constant is the asdl `Constant` node.
type Constant struct {
	Value any
	Kind  *string
	Pos   Pos
}

func (*Constant) isExpr() {}

// Position returns the source location.
func (n *Constant) Position() Pos { return n.Pos }

// Attribute is the asdl `Attribute` node.
type Attribute struct {
	Value Expr
	Attr  string
	Ctx   ExprContext
	Pos   Pos
}

func (*Attribute) isExpr() {}

// Position returns the source location.
func (n *Attribute) Position() Pos { return n.Pos }

// Subscript is the asdl `Subscript` node.
type Subscript struct {
	Value Expr
	Slice Expr
	Ctx   ExprContext
	Pos   Pos
}

func (*Subscript) isExpr() {}

// Position returns the source location.
func (n *Subscript) Position() Pos { return n.Pos }

// Starred is the asdl `Starred` node.
type Starred struct {
	Value Expr
	Ctx   ExprContext
	Pos   Pos
}

func (*Starred) isExpr() {}

// Position returns the source location.
func (n *Starred) Position() Pos { return n.Pos }

// Name is the asdl `Name` node.
type Name struct {
	Id  string
	Ctx ExprContext
	Pos Pos
}

func (*Name) isExpr() {}

// Position returns the source location.
func (n *Name) Position() Pos { return n.Pos }

// List is the asdl `List` node.
type List struct {
	Elts Seq[Expr]
	Ctx  ExprContext
	Pos  Pos
}

func (*List) isExpr() {}

// Position returns the source location.
func (n *List) Position() Pos { return n.Pos }

// Tuple is the asdl `Tuple` node.
type Tuple struct {
	Elts Seq[Expr]
	Ctx  ExprContext
	Pos  Pos
}

func (*Tuple) isExpr() {}

// Position returns the source location.
func (n *Tuple) Position() Pos { return n.Pos }

// Slice is the asdl `Slice` node.
type Slice struct {
	Lower Expr
	Upper Expr
	Step  Expr
	Pos   Pos
}

func (*Slice) isExpr() {}

// Position returns the source location.
func (n *Slice) Position() Pos { return n.Pos }

// ExprContext is the asdl `expr_context` enum.
type ExprContext int

const (
	Load ExprContext = iota + 1
	Store
	Del
)

// String returns the asdl name.
func (v ExprContext) String() string {
	switch v {
	case Load:
		return "Load"
	case Store:
		return "Store"
	case Del:
		return "Del"
	}
	return ""
}

// Boolop is the asdl `boolop` enum.
type Boolop int

const (
	And Boolop = iota + 1
	Or
)

// String returns the asdl name.
func (v Boolop) String() string {
	switch v {
	case And:
		return "And"
	case Or:
		return "Or"
	}
	return ""
}

// Operator is the asdl `operator` enum.
type Operator int

const (
	Add Operator = iota + 1
	Sub
	Mult
	MatMult
	Div
	ModOperator
	Pow
	LShift
	RShift
	BitOr
	BitXor
	BitAnd
	FloorDiv
)

// String returns the asdl name.
func (v Operator) String() string {
	switch v {
	case Add:
		return "Add"
	case Sub:
		return "Sub"
	case Mult:
		return "Mult"
	case MatMult:
		return "MatMult"
	case Div:
		return "Div"
	case ModOperator:
		return "ModOperator"
	case Pow:
		return "Pow"
	case LShift:
		return "LShift"
	case RShift:
		return "RShift"
	case BitOr:
		return "BitOr"
	case BitXor:
		return "BitXor"
	case BitAnd:
		return "BitAnd"
	case FloorDiv:
		return "FloorDiv"
	}
	return ""
}

// Unaryop is the asdl `unaryop` enum.
type Unaryop int

const (
	Invert Unaryop = iota + 1
	Not
	UAdd
	USub
)

// String returns the asdl name.
func (v Unaryop) String() string {
	switch v {
	case Invert:
		return "Invert"
	case Not:
		return "Not"
	case UAdd:
		return "UAdd"
	case USub:
		return "USub"
	}
	return ""
}

// Cmpop is the asdl `cmpop` enum.
type Cmpop int

const (
	Eq Cmpop = iota + 1
	NotEq
	Lt
	LtE
	Gt
	GtE
	Is
	IsNot
	In
	NotIn
)

// String returns the asdl name.
func (v Cmpop) String() string {
	switch v {
	case Eq:
		return "Eq"
	case NotEq:
		return "NotEq"
	case Lt:
		return "Lt"
	case LtE:
		return "LtE"
	case Gt:
		return "Gt"
	case GtE:
		return "GtE"
	case Is:
		return "Is"
	case IsNot:
		return "IsNot"
	case In:
		return "In"
	case NotIn:
		return "NotIn"
	}
	return ""
}

// Comprehension is the asdl `comprehension` node.
type Comprehension struct {
	Target  Expr
	Iter    Expr
	Ifs     Seq[Expr]
	IsAsync int
}

// Excepthandler is the asdl `excepthandler` sum.
type Excepthandler interface {
	isExcepthandler()
	Position() Pos
}

// ExceptHandler is the asdl `ExceptHandler` node.
type ExceptHandler struct {
	Type Expr
	Name *string
	Body Seq[Stmt]
	Pos  Pos
}

func (*ExceptHandler) isExcepthandler() {}

// Position returns the source location.
func (n *ExceptHandler) Position() Pos { return n.Pos }

// Arguments is the asdl `arguments` node.
type Arguments struct {
	Posonlyargs Seq[*Arg]
	Args        Seq[*Arg]
	Vararg      *Arg
	Kwonlyargs  Seq[*Arg]
	KwDefaults  Seq[Expr]
	Kwarg       *Arg
	Defaults    Seq[Expr]
}

// Arg is the asdl `arg` node.
type Arg struct {
	Arg         string
	Annotation  Expr
	TypeComment *string
	Pos         Pos
}

// Position returns the source location.
func (n *Arg) Position() Pos { return n.Pos }

// Keyword is the asdl `keyword` node.
type Keyword struct {
	Arg   *string
	Value Expr
	Pos   Pos
}

// Position returns the source location.
func (n *Keyword) Position() Pos { return n.Pos }

// Alias is the asdl `alias` node.
type Alias struct {
	Name   string
	Asname *string
	Pos    Pos
}

// Position returns the source location.
func (n *Alias) Position() Pos { return n.Pos }

// Withitem is the asdl `withitem` node.
type Withitem struct {
	ContextExpr  Expr
	OptionalVars Expr
}

// MatchCase is the asdl `match_case` node.
type MatchCase struct {
	Pattern Pattern
	Guard   Expr
	Body    Seq[Stmt]
}

// Pattern is the asdl `pattern` sum.
type Pattern interface {
	isPattern()
	Position() Pos
}

// MatchValue is the asdl `MatchValue` node.
type MatchValue struct {
	Value Expr
	Pos   Pos
}

func (*MatchValue) isPattern() {}

// Position returns the source location.
func (n *MatchValue) Position() Pos { return n.Pos }

// MatchSingleton is the asdl `MatchSingleton` node.
type MatchSingleton struct {
	Value any
	Pos   Pos
}

func (*MatchSingleton) isPattern() {}

// Position returns the source location.
func (n *MatchSingleton) Position() Pos { return n.Pos }

// MatchSequence is the asdl `MatchSequence` node.
type MatchSequence struct {
	Patterns Seq[Pattern]
	Pos      Pos
}

func (*MatchSequence) isPattern() {}

// Position returns the source location.
func (n *MatchSequence) Position() Pos { return n.Pos }

// MatchMapping is the asdl `MatchMapping` node.
type MatchMapping struct {
	Keys     Seq[Expr]
	Patterns Seq[Pattern]
	Rest     *string
	Pos      Pos
}

func (*MatchMapping) isPattern() {}

// Position returns the source location.
func (n *MatchMapping) Position() Pos { return n.Pos }

// MatchClass is the asdl `MatchClass` node.
type MatchClass struct {
	Cls         Expr
	Patterns    Seq[Pattern]
	KwdAttrs    Seq[string]
	KwdPatterns Seq[Pattern]
	Pos         Pos
}

func (*MatchClass) isPattern() {}

// Position returns the source location.
func (n *MatchClass) Position() Pos { return n.Pos }

// MatchStar is the asdl `MatchStar` node.
type MatchStar struct {
	Name *string
	Pos  Pos
}

func (*MatchStar) isPattern() {}

// Position returns the source location.
func (n *MatchStar) Position() Pos { return n.Pos }

// MatchAs is the asdl `MatchAs` node.
type MatchAs struct {
	Pattern Pattern
	Name    *string
	Pos     Pos
}

func (*MatchAs) isPattern() {}

// Position returns the source location.
func (n *MatchAs) Position() Pos { return n.Pos }

// MatchOr is the asdl `MatchOr` node.
type MatchOr struct {
	Patterns Seq[Pattern]
	Pos      Pos
}

func (*MatchOr) isPattern() {}

// Position returns the source location.
func (n *MatchOr) Position() Pos { return n.Pos }

// TypeIgnore is the asdl `type_ignore` sum.
type TypeIgnore interface {
	isTypeIgnore()
}

// TypeIgnoreNode is the asdl `TypeIgnoreNode` node.
type TypeIgnoreNode struct {
	Lineno int
	Tag    string
}

func (*TypeIgnoreNode) isTypeIgnore() {}

// TypeParam is the asdl `type_param` sum.
type TypeParam interface {
	isTypeParam()
	Position() Pos
}

// TypeVar is the asdl `TypeVar` node.
type TypeVar struct {
	Name         string
	Bound        Expr
	DefaultValue Expr
	Pos          Pos
}

func (*TypeVar) isTypeParam() {}

// Position returns the source location.
func (n *TypeVar) Position() Pos { return n.Pos }

// ParamSpec is the asdl `ParamSpec` node.
type ParamSpec struct {
	Name         string
	DefaultValue Expr
	Pos          Pos
}

func (*ParamSpec) isTypeParam() {}

// Position returns the source location.
func (n *ParamSpec) Position() Pos { return n.Pos }

// TypeVarTuple is the asdl `TypeVarTuple` node.
type TypeVarTuple struct {
	Name         string
	DefaultValue Expr
	Pos          Pos
}

func (*TypeVarTuple) isTypeParam() {}

// Position returns the source location.
func (n *TypeVarTuple) Position() Pos { return n.Pos }
