// Command parser_gen generates the PEG parser table for gopy from
// cpython/Grammar/python.gram. It is the Go-targeted counterpart of
// CPython's Tools/peg_generator/.
//
// Inputs:
//   - $CPYTHON/Grammar/python.gram: the PEG grammar.
//   - $CPYTHON/Grammar/Tokens: token-kind names (re-resolved
//     against parser/tokenize so generated code links).
//
// Output:
//   - <repo>/parser/pegen/parser_gen.go: the rule-table struct, the
//     keyword tables, and the per-rule parse functions.
//
// Run with:
//
//	go run ./tools/parser_gen \
//	  -cpython=$HOME/cpython-314 \
//	  -out=parser/pegen/parser_gen.go
//
// The generator is a scaffold for now; it parses python.gram into a
// rule list and prints a stub. The actual rule-by-rule emission lands
// alongside the v0.6 work that wires the table into pegen.New.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
)

func main() {
	var cpython, out string
	flag.StringVar(&cpython, "cpython", "", "path to a cpython 3.14 checkout")
	flag.StringVar(&out, "out", "parser/pegen/parser_gen.go", "output Go file")
	flag.Parse()
	if cpython == "" {
		log.Fatal("parser_gen: -cpython is required")
	}
	gram := filepath.Join(cpython, "Grammar", "python.gram")
	if _, err := os.Stat(gram); err != nil {
		log.Fatalf("parser_gen: cannot read %s: %v", gram, err)
	}
	rules, err := readGrammar(gram)
	if err != nil {
		log.Fatalf("parser_gen: %v", err)
	}
	if err := writeStub(out, rules); err != nil {
		log.Fatalf("parser_gen: %v", err)
	}
	fmt.Fprintf(os.Stderr, "parser_gen: scaffold wrote %d rules to %s\n", len(rules), out)
}

// rule is one entry parsed out of python.gram. The full PEG body is
// kept verbatim; the rule-by-rule emitter lands later.
type rule struct {
	Name string
	Body string
}

func readGrammar(path string) ([]rule, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return splitRules(data), nil
}

func splitRules(src []byte) []rule {
	var rules []rule
	var cur rule
	flush := func() {
		if cur.Name != "" {
			rules = append(rules, cur)
			cur = rule{}
		}
	}
	for _, line := range splitLines(src) {
		if len(line) == 0 || line[0] == '#' {
			continue
		}
		// A rule head is a line that starts at column 0 and contains
		// `:` outside of any [optional] / 'literal' brackets. The
		// scaffold treats the leading word as the rule name and
		// gathers the remainder of the rule into Body. The full PEG
		// metadata (return type, action) is left for the emitter.
		if line[0] != ' ' && line[0] != '\t' {
			flush()
			i := 0
			for i < len(line) && line[i] != ':' && line[i] != ' ' && line[i] != '[' {
				i++
			}
			cur.Name = string(line[:i])
			cur.Body = string(line)
			continue
		}
		cur.Body += "\n" + string(line)
	}
	flush()
	return rules
}

func splitLines(src []byte) [][]byte {
	var out [][]byte
	start := 0
	for i, b := range src {
		if b == '\n' {
			out = append(out, src[start:i])
			start = i + 1
		}
	}
	if start < len(src) {
		out = append(out, src[start:])
	}
	return out
}

func writeStub(path string, rules []rule) error {
	var sb []byte
	sb = append(sb, "// Code generated by tools/parser_gen from cpython/Grammar/python.gram. DO NOT EDIT.\n"...)
	sb = append(sb, "//\n// CPython: Grammar/python.gram\n\n"...)
	sb = append(sb, "package pegen\n\n"...)
	sb = append(sb, "// generatedRuleNames is the list of rule names parser_gen extracted\n"...)
	sb = append(sb, "// from python.gram. The rule bodies and parse functions land here\n"...)
	sb = append(sb, "// once the emitter ships.\n"...)
	sb = append(sb, "var generatedRuleNames = []string{\n"...)
	for _, r := range rules {
		sb = append(sb, "\t\""...)
		sb = append(sb, r.Name...)
		sb = append(sb, "\",\n"...)
	}
	sb = append(sb, "}\n"...)
	return os.WriteFile(path, sb, 0o644)
}
