// macOS errno table. The set of E* constants here mirrors the
// MacOSX-specific list that errnomodule.c maintains plus the common
// POSIX entries that exist on Darwin.
//
// CPython: Modules/errnomodule.c:121 add_errcode block (with MacOSX additions at line 890)

package errno

import "syscall"

// errnoEntries returns every (name, code) pair the errno module exposes
// on Darwin. The table is derived from the syscall package's per-arch
// zerrors_darwin_*.go file; one entry per Errno constant that exists on
// this GOOS.
//
// CPython: Modules/errnomodule.c:88 errno_exec (Darwin slice)
func errnoEntries() []errnoEntry {
	return []errnoEntry{
		{"EPERM", int(syscall.EPERM)},
		{"ENOENT", int(syscall.ENOENT)},
		{"ESRCH", int(syscall.ESRCH)},
		{"EINTR", int(syscall.EINTR)},
		{"EIO", int(syscall.EIO)},
		{"ENXIO", int(syscall.ENXIO)},
		{"E2BIG", int(syscall.E2BIG)},
		{"ENOEXEC", int(syscall.ENOEXEC)},
		{"EBADF", int(syscall.EBADF)},
		{"ECHILD", int(syscall.ECHILD)},
		{"EDEADLK", int(syscall.EDEADLK)},
		{"ENOMEM", int(syscall.ENOMEM)},
		{"EACCES", int(syscall.EACCES)},
		{"EFAULT", int(syscall.EFAULT)},
		{"ENOTBLK", int(syscall.ENOTBLK)},
		{"EBUSY", int(syscall.EBUSY)},
		{"EEXIST", int(syscall.EEXIST)},
		{"EXDEV", int(syscall.EXDEV)},
		{"ENODEV", int(syscall.ENODEV)},
		{"ENOTDIR", int(syscall.ENOTDIR)},
		{"EISDIR", int(syscall.EISDIR)},
		{"EINVAL", int(syscall.EINVAL)},
		{"ENFILE", int(syscall.ENFILE)},
		{"EMFILE", int(syscall.EMFILE)},
		{"ENOTTY", int(syscall.ENOTTY)},
		{"ETXTBSY", int(syscall.ETXTBSY)},
		{"EFBIG", int(syscall.EFBIG)},
		{"ENOSPC", int(syscall.ENOSPC)},
		{"ESPIPE", int(syscall.ESPIPE)},
		{"EROFS", int(syscall.EROFS)},
		{"EMLINK", int(syscall.EMLINK)},
		{"EPIPE", int(syscall.EPIPE)},
		{"EDOM", int(syscall.EDOM)},
		{"ERANGE", int(syscall.ERANGE)},
		{"EAGAIN", int(syscall.EAGAIN)},
		{"EWOULDBLOCK", int(syscall.EWOULDBLOCK)},
		{"EINPROGRESS", int(syscall.EINPROGRESS)},
		{"EALREADY", int(syscall.EALREADY)},
		{"ENOTSOCK", int(syscall.ENOTSOCK)},
		{"EDESTADDRREQ", int(syscall.EDESTADDRREQ)},
		{"EMSGSIZE", int(syscall.EMSGSIZE)},
		{"EPROTOTYPE", int(syscall.EPROTOTYPE)},
		{"ENOPROTOOPT", int(syscall.ENOPROTOOPT)},
		{"EPROTONOSUPPORT", int(syscall.EPROTONOSUPPORT)},
		{"ESOCKTNOSUPPORT", int(syscall.ESOCKTNOSUPPORT)},
		{"EOPNOTSUPP", int(syscall.EOPNOTSUPP)},
		{"EPFNOSUPPORT", int(syscall.EPFNOSUPPORT)},
		{"EAFNOSUPPORT", int(syscall.EAFNOSUPPORT)},
		{"EADDRINUSE", int(syscall.EADDRINUSE)},
		{"EADDRNOTAVAIL", int(syscall.EADDRNOTAVAIL)},
		{"ENETDOWN", int(syscall.ENETDOWN)},
		{"ENETUNREACH", int(syscall.ENETUNREACH)},
		{"ENETRESET", int(syscall.ENETRESET)},
		{"ECONNABORTED", int(syscall.ECONNABORTED)},
		{"ECONNRESET", int(syscall.ECONNRESET)},
		{"ENOBUFS", int(syscall.ENOBUFS)},
		{"EISCONN", int(syscall.EISCONN)},
		{"ENOTCONN", int(syscall.ENOTCONN)},
		{"ESHUTDOWN", int(syscall.ESHUTDOWN)},
		{"ETOOMANYREFS", int(syscall.ETOOMANYREFS)},
		{"ETIMEDOUT", int(syscall.ETIMEDOUT)},
		{"ECONNREFUSED", int(syscall.ECONNREFUSED)},
		{"ELOOP", int(syscall.ELOOP)},
		{"ENAMETOOLONG", int(syscall.ENAMETOOLONG)},
		{"EHOSTDOWN", int(syscall.EHOSTDOWN)},
		{"EHOSTUNREACH", int(syscall.EHOSTUNREACH)},
		{"ENOTEMPTY", int(syscall.ENOTEMPTY)},
		{"EPROCLIM", int(syscall.EPROCLIM)},
		{"EUSERS", int(syscall.EUSERS)},
		{"EDQUOT", int(syscall.EDQUOT)},
		{"ESTALE", int(syscall.ESTALE)},
		{"EREMOTE", int(syscall.EREMOTE)},
		{"EBADRPC", int(syscall.EBADRPC)},
		{"ERPCMISMATCH", int(syscall.ERPCMISMATCH)},
		{"EPROGUNAVAIL", int(syscall.EPROGUNAVAIL)},
		{"EPROGMISMATCH", int(syscall.EPROGMISMATCH)},
		{"EPROCUNAVAIL", int(syscall.EPROCUNAVAIL)},
		{"ENOLCK", int(syscall.ENOLCK)},
		{"ENOSYS", int(syscall.ENOSYS)},
		{"EFTYPE", int(syscall.EFTYPE)},
		{"EAUTH", int(syscall.EAUTH)},
		{"ENEEDAUTH", int(syscall.ENEEDAUTH)},
		{"EPWROFF", int(syscall.EPWROFF)},
		{"EDEVERR", int(syscall.EDEVERR)},
		{"EOVERFLOW", int(syscall.EOVERFLOW)},
		{"EBADEXEC", int(syscall.EBADEXEC)},
		{"EBADARCH", int(syscall.EBADARCH)},
		{"ESHLIBVERS", int(syscall.ESHLIBVERS)},
		{"EBADMACHO", int(syscall.EBADMACHO)},
		{"ECANCELED", int(syscall.ECANCELED)},
		{"EIDRM", int(syscall.EIDRM)},
		{"ENOMSG", int(syscall.ENOMSG)},
		{"EILSEQ", int(syscall.EILSEQ)},
		{"ENOATTR", int(syscall.ENOATTR)},
		{"EBADMSG", int(syscall.EBADMSG)},
		{"EMULTIHOP", int(syscall.EMULTIHOP)},
		{"ENODATA", int(syscall.ENODATA)},
		{"ENOLINK", int(syscall.ENOLINK)},
		{"ENOSR", int(syscall.ENOSR)},
		{"ENOSTR", int(syscall.ENOSTR)},
		{"EPROTO", int(syscall.EPROTO)},
		{"ETIME", int(syscall.ETIME)},
		{"ENOPOLICY", int(syscall.ENOPOLICY)},
		{"ENOTRECOVERABLE", int(syscall.ENOTRECOVERABLE)},
		{"EOWNERDEAD", int(syscall.EOWNERDEAD)},
		{"EQFULL", int(syscall.EQFULL)},
		{"ENOTSUP", int(syscall.ENOTSUP)},
	}
}
