// Linux errno table. The set of E* constants here mirrors the
// Linux-relevant subset of errnomodule.c, derived from the syscall
// package's per-arch zerrors_linux_*.go file.
//
// CPython: Modules/errnomodule.c:121 add_errcode block

package errno

import "syscall"

// errnoEntries returns every (name, code) pair the errno module exposes
// on Linux.
//
// CPython: Modules/errnomodule.c:88 errno_exec (Linux slice)
func errnoEntries() []errnoEntry {
	return []errnoEntry{
		{"EPERM", int(syscall.EPERM)},
		{"ENOENT", int(syscall.ENOENT)},
		{"ESRCH", int(syscall.ESRCH)},
		{"EINTR", int(syscall.EINTR)},
		{"EIO", int(syscall.EIO)},
		{"ENXIO", int(syscall.ENXIO)},
		{"E2BIG", int(syscall.E2BIG)},
		{"ENOEXEC", int(syscall.ENOEXEC)},
		{"EBADF", int(syscall.EBADF)},
		{"ECHILD", int(syscall.ECHILD)},
		{"EAGAIN", int(syscall.EAGAIN)},
		{"ENOMEM", int(syscall.ENOMEM)},
		{"EACCES", int(syscall.EACCES)},
		{"EFAULT", int(syscall.EFAULT)},
		{"ENOTBLK", int(syscall.ENOTBLK)},
		{"EBUSY", int(syscall.EBUSY)},
		{"EEXIST", int(syscall.EEXIST)},
		{"EXDEV", int(syscall.EXDEV)},
		{"ENODEV", int(syscall.ENODEV)},
		{"ENOTDIR", int(syscall.ENOTDIR)},
		{"EISDIR", int(syscall.EISDIR)},
		{"EINVAL", int(syscall.EINVAL)},
		{"ENFILE", int(syscall.ENFILE)},
		{"EMFILE", int(syscall.EMFILE)},
		{"ENOTTY", int(syscall.ENOTTY)},
		{"ETXTBSY", int(syscall.ETXTBSY)},
		{"EFBIG", int(syscall.EFBIG)},
		{"ENOSPC", int(syscall.ENOSPC)},
		{"ESPIPE", int(syscall.ESPIPE)},
		{"EROFS", int(syscall.EROFS)},
		{"EMLINK", int(syscall.EMLINK)},
		{"EPIPE", int(syscall.EPIPE)},
		{"EDOM", int(syscall.EDOM)},
		{"ERANGE", int(syscall.ERANGE)},
		{"EDEADLK", int(syscall.EDEADLK)},
		{"ENAMETOOLONG", int(syscall.ENAMETOOLONG)},
		{"ENOLCK", int(syscall.ENOLCK)},
		{"ENOSYS", int(syscall.ENOSYS)},
		{"ENOTEMPTY", int(syscall.ENOTEMPTY)},
		{"ELOOP", int(syscall.ELOOP)},
		{"EWOULDBLOCK", int(syscall.EWOULDBLOCK)},
		{"ENOMSG", int(syscall.ENOMSG)},
		{"EIDRM", int(syscall.EIDRM)},
		{"ECHRNG", int(syscall.ECHRNG)},
		{"EL2NSYNC", int(syscall.EL2NSYNC)},
		{"EL3HLT", int(syscall.EL3HLT)},
		{"EL3RST", int(syscall.EL3RST)},
		{"ELNRNG", int(syscall.ELNRNG)},
		{"EUNATCH", int(syscall.EUNATCH)},
		{"ENOCSI", int(syscall.ENOCSI)},
		{"EL2HLT", int(syscall.EL2HLT)},
		{"EBADE", int(syscall.EBADE)},
		{"EBADR", int(syscall.EBADR)},
		{"EXFULL", int(syscall.EXFULL)},
		{"ENOANO", int(syscall.ENOANO)},
		{"EBADRQC", int(syscall.EBADRQC)},
		{"EBADSLT", int(syscall.EBADSLT)},
		{"EDEADLOCK", int(syscall.EDEADLOCK)},
		{"EBFONT", int(syscall.EBFONT)},
		{"ENOSTR", int(syscall.ENOSTR)},
		{"ENODATA", int(syscall.ENODATA)},
		{"ETIME", int(syscall.ETIME)},
		{"ENOSR", int(syscall.ENOSR)},
		{"ENONET", int(syscall.ENONET)},
		{"ENOPKG", int(syscall.ENOPKG)},
		{"EREMOTE", int(syscall.EREMOTE)},
		{"ENOLINK", int(syscall.ENOLINK)},
		{"EADV", int(syscall.EADV)},
		{"ESRMNT", int(syscall.ESRMNT)},
		{"ECOMM", int(syscall.ECOMM)},
		{"EPROTO", int(syscall.EPROTO)},
		{"EMULTIHOP", int(syscall.EMULTIHOP)},
		{"EDOTDOT", int(syscall.EDOTDOT)},
		{"EBADMSG", int(syscall.EBADMSG)},
		{"EOVERFLOW", int(syscall.EOVERFLOW)},
		{"ENOTUNIQ", int(syscall.ENOTUNIQ)},
		{"EBADFD", int(syscall.EBADFD)},
		{"EREMCHG", int(syscall.EREMCHG)},
		{"ELIBACC", int(syscall.ELIBACC)},
		{"ELIBBAD", int(syscall.ELIBBAD)},
		{"ELIBSCN", int(syscall.ELIBSCN)},
		{"ELIBMAX", int(syscall.ELIBMAX)},
		{"ELIBEXEC", int(syscall.ELIBEXEC)},
		{"EILSEQ", int(syscall.EILSEQ)},
		{"ERESTART", int(syscall.ERESTART)},
		{"ESTRPIPE", int(syscall.ESTRPIPE)},
		{"EUSERS", int(syscall.EUSERS)},
		{"ENOTSOCK", int(syscall.ENOTSOCK)},
		{"EDESTADDRREQ", int(syscall.EDESTADDRREQ)},
		{"EMSGSIZE", int(syscall.EMSGSIZE)},
		{"EPROTOTYPE", int(syscall.EPROTOTYPE)},
		{"ENOPROTOOPT", int(syscall.ENOPROTOOPT)},
		{"EPROTONOSUPPORT", int(syscall.EPROTONOSUPPORT)},
		{"ESOCKTNOSUPPORT", int(syscall.ESOCKTNOSUPPORT)},
		{"EOPNOTSUPP", int(syscall.EOPNOTSUPP)},
		{"EPFNOSUPPORT", int(syscall.EPFNOSUPPORT)},
		{"EAFNOSUPPORT", int(syscall.EAFNOSUPPORT)},
		{"EADDRINUSE", int(syscall.EADDRINUSE)},
		{"EADDRNOTAVAIL", int(syscall.EADDRNOTAVAIL)},
		{"ENETDOWN", int(syscall.ENETDOWN)},
		{"ENETUNREACH", int(syscall.ENETUNREACH)},
		{"ENETRESET", int(syscall.ENETRESET)},
		{"ECONNABORTED", int(syscall.ECONNABORTED)},
		{"ECONNRESET", int(syscall.ECONNRESET)},
		{"ENOBUFS", int(syscall.ENOBUFS)},
		{"EISCONN", int(syscall.EISCONN)},
		{"ENOTCONN", int(syscall.ENOTCONN)},
		{"ESHUTDOWN", int(syscall.ESHUTDOWN)},
		{"ETOOMANYREFS", int(syscall.ETOOMANYREFS)},
		{"ETIMEDOUT", int(syscall.ETIMEDOUT)},
		{"ECONNREFUSED", int(syscall.ECONNREFUSED)},
		{"EHOSTDOWN", int(syscall.EHOSTDOWN)},
		{"EHOSTUNREACH", int(syscall.EHOSTUNREACH)},
		{"EALREADY", int(syscall.EALREADY)},
		{"EINPROGRESS", int(syscall.EINPROGRESS)},
		{"ESTALE", int(syscall.ESTALE)},
		{"EUCLEAN", int(syscall.EUCLEAN)},
		{"ENOTNAM", int(syscall.ENOTNAM)},
		{"ENAVAIL", int(syscall.ENAVAIL)},
		{"EISNAM", int(syscall.EISNAM)},
		{"EREMOTEIO", int(syscall.EREMOTEIO)},
		{"EDQUOT", int(syscall.EDQUOT)},
		{"ENOMEDIUM", int(syscall.ENOMEDIUM)},
		{"EMEDIUMTYPE", int(syscall.EMEDIUMTYPE)},
		{"ECANCELED", int(syscall.ECANCELED)},
		{"ENOKEY", int(syscall.ENOKEY)},
		{"EKEYEXPIRED", int(syscall.EKEYEXPIRED)},
		{"EKEYREVOKED", int(syscall.EKEYREVOKED)},
		{"EKEYREJECTED", int(syscall.EKEYREJECTED)},
		{"EOWNERDEAD", int(syscall.EOWNERDEAD)},
		{"ENOTRECOVERABLE", int(syscall.ENOTRECOVERABLE)},
		{"ERFKILL", int(syscall.ERFKILL)},
		{"ENOTSUP", int(syscall.ENOTSUP)},
	}
}
