// Command opcodes_go generates compile/opcodes_gen.go from CPython
// 3.14 source.
//
// Inputs:
//   - $CPYTHON/Lib/_opcode_metadata.py: opmap (name -> opcode int).
//   - $CPYTHON/Include/internal/pycore_opcode_metadata.h: per-opcode
//     flag bitmask (HAS_ARG, HAS_JUMP, HAS_NAME, ...).
//
// Output:
//   - <repo>/compile/opcodes_gen.go: typed Opcode constants, opcode
//     name table, flag predicates, name lookup.
//
// Run with:
//
//	go run ./tools/opcodes_go \
//	  -cpython=$HOME/github/python/cpython \
//	  -out=compile/opcodes_gen.go
//
// The CPython source is not vendored. The generator regenerates the
// output file on demand; the file is checked in so the runtime build
// has no Python dependency.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const flagOrder = "ARG,CONST,NAME,JUMP,FREE,LOCAL,EVAL_BREAK,DEOPT,ERROR,ESCAPES,EXIT,PURE,PASSTHROUGH,OPARG_AND_1,ERROR_NO_POP,NO_SAVE_IP"

func main() {
	cpython := flag.String("cpython", "", "path to cpython source tree")
	out := flag.String("out", "", "output Go file")
	flag.Parse()
	if *cpython == "" || *out == "" {
		log.Fatal("both -cpython and -out required")
	}

	opmap, err := parseOpmap(filepath.Join(*cpython, "Lib", "_opcode_metadata.py"))
	if err != nil {
		log.Fatal(err)
	}

	flags, err := parseFlags(filepath.Join(*cpython, "Include", "internal", "pycore_opcode_metadata.h"))
	if err != nil {
		log.Fatal(err)
	}

	src, err := emit(opmap, flags)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// parseOpmap parses both the opmap and _specialized_opmap dict
// literals in _opcode_metadata.py. Lines have the shape
// `    'NAME': N,`. Specialized variants (LOAD_ATTR_INSTANCE_VALUE,
// BINARY_OP_ADD_INT, ...) live in _specialized_opmap and the
// adaptive specializer needs to refer to them by name, so we
// merge both dicts into a single map.
func parseOpmap(path string) (map[string]int, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	re := regexp.MustCompile(`'([A-Z_0-9]+)':\s*(\d+),`)
	out := map[string]int{}
	in := false
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "opmap = {"),
			strings.HasPrefix(trimmed, "_specialized_opmap = {"):
			in = true
		case in && strings.HasPrefix(trimmed, "}"):
			in = false
		case in:
			if m := re.FindStringSubmatch(line); m != nil {
				v, err := strconv.Atoi(m[2])
				if err != nil {
					return nil, err
				}
				out[m[1]] = v
			}
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("opmap dict not found in %s", path)
	}
	return out, nil
}

// parseFlags parses the table entries in pycore_opcode_metadata.h.
// Each entry has the shape:
//
//	[NAME] = { true, INSTR_FMT_X, FLAG_A | FLAG_B | ... },
//
// We only keep the flag set; valid_entry and instr_format are
// reconstructible from the opcode name.
func parseFlags(path string) (map[string]uint16, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	// Capture name + the comma-separated flag list. The flags can
	// include a literal `0` for opcodes with no metadata flags.
	re := regexp.MustCompile(`\[([A-Z_0-9]+)\]\s*=\s*\{\s*(?:true|false)\s*,\s*[A-Z_0-9]+\s*,\s*([0A-Z_| ]+)\s*\}`)
	out := map[string]uint16{}
	for _, m := range re.FindAllStringSubmatch(string(data), -1) {
		name := m[1]
		bits := uint16(0)
		for _, f := range strings.Split(m[2], "|") {
			f = strings.TrimSpace(f)
			f = strings.TrimSuffix(f, "_FLAG")
			if f == "" || f == "0" {
				continue
			}
			b, ok := flagBit(f)
			if !ok {
				return nil, fmt.Errorf("unknown flag %q for %s", f, name)
			}
			bits |= b
		}
		out[name] = bits
	}
	return out, nil
}

func flagBit(name string) (uint16, bool) {
	for i, f := range strings.Split(flagOrder, ",") {
		want := strings.TrimPrefix(name, "HAS_")
		if want == f {
			return 1 << i, true
		}
	}
	return 0, false
}

func emit(opmap map[string]int, flags map[string]uint16) ([]byte, error) {
	type entry struct {
		Name  string
		Op    int
		Flags uint16
	}
	entries := make([]entry, 0, len(opmap))
	for n, v := range opmap {
		entries = append(entries, entry{Name: n, Op: v, Flags: flags[n]})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Op < entries[j].Op })

	var buf bytes.Buffer
	fmt.Fprintln(&buf, `// Code generated by tools/opcodes_go. DO NOT EDIT.`)
	fmt.Fprintln(&buf, `// Source: cpython/Lib/_opcode_metadata.py + cpython/Include/internal/pycore_opcode_metadata.h`)
	fmt.Fprintln(&buf, ``)
	fmt.Fprintln(&buf, `package compile`)
	fmt.Fprintln(&buf, ``)
	fmt.Fprintln(&buf, `// Opcode flag bits. Mirror HAS_*_FLAG in pycore_opcode_metadata.h.`)
	fmt.Fprintln(&buf, `const (`)
	for i, f := range strings.Split(flagOrder, ",") {
		fmt.Fprintf(&buf, "\tflag%s = 1 << %d\n", camelFlag(f), i)
	}
	fmt.Fprintln(&buf, `)`)
	fmt.Fprintln(&buf, ``)
	fmt.Fprintln(&buf, `// Opcode constants. Numeric values match cpython 3.14 opmap.`)
	fmt.Fprintln(&buf, `const (`)
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t%s Opcode = %d\n", e.Name, e.Op)
	}
	fmt.Fprintln(&buf, `)`)
	fmt.Fprintln(&buf, ``)
	fmt.Fprintln(&buf, `// opcodeFlags is indexed by opcode value.`)
	maxOp := 0
	for _, e := range entries {
		if e.Op > maxOp {
			maxOp = e.Op
		}
	}
	fmt.Fprintf(&buf, "var opcodeFlags = [%d]uint16{\n", maxOp+1)
	for _, e := range entries {
		if e.Flags == 0 {
			continue
		}
		fmt.Fprintf(&buf, "\t%s: 0x%04x,\n", e.Name, e.Flags)
	}
	fmt.Fprintln(&buf, `}`)
	fmt.Fprintln(&buf, ``)
	fmt.Fprintf(&buf, "var opcodeName = [%d]string{\n", maxOp+1)
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t%s: %q,\n", e.Name, e.Name)
	}
	fmt.Fprintln(&buf, `}`)
	fmt.Fprintln(&buf, ``)
	fmt.Fprintln(&buf, `// Name returns the symbolic name for op, or "" if op is not a known opcode.`)
	fmt.Fprintln(&buf, `func (op Opcode) Name() string {`)
	fmt.Fprintln(&buf, `	if op < 0 || int(op) >= len(opcodeName) {`)
	fmt.Fprintln(&buf, `		return ""`)
	fmt.Fprintln(&buf, `	}`)
	fmt.Fprintln(&buf, `	return opcodeName[op]`)
	fmt.Fprintln(&buf, `}`)
	fmt.Fprintln(&buf, ``)
	for _, f := range strings.Split(flagOrder, ",") {
		fmt.Fprintf(&buf, "// Has%s reports whether op carries the %s metadata flag.\n", camelFlag(f), strings.ReplaceAll(strings.ToLower(f), "_", " "))
		fmt.Fprintf(&buf, "func (op Opcode) Has%s() bool {\n", camelFlag(f))
		fmt.Fprintf(&buf, "\tif op < 0 || int(op) >= len(opcodeFlags) { return false }\n")
		fmt.Fprintf(&buf, "\treturn opcodeFlags[op]&flag%s != 0\n}\n\n", camelFlag(f))
	}
	fmt.Fprintln(&buf, `// HasTarget reports whether op carries a jump target oparg.`)
	fmt.Fprintln(&buf, `// CPython spells this OPCODE_HAS_JUMP and uses it from the`)
	fmt.Fprintln(&buf, `// instruction-sequence label resolver.`)
	fmt.Fprintln(&buf, `func HasTarget(op Opcode) bool { return op.HasJump() }`)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("gofmt: %w", err)
	}
	return src, nil
}

func camelFlag(f string) string {
	// HAS_OPARG_AND_1 -> OpargAnd1, NO_SAVE_IP -> NoSaveIP, etc.
	parts := strings.Split(f, "_")
	for i, p := range parts {
		switch p {
		case "IP":
			parts[i] = "IP"
		default:
			parts[i] = strings.Title(strings.ToLower(p))
		}
	}
	return strings.Join(parts, "")
}
