/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  manualSidebar: [
    'manual/index',
    {
      label: 'Get started',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'manual/install',
        'manual/run',
        'manual/hello-world',
      ],
    },
    {
      label: 'Using gopy',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'manual/cli',
        'manual/repl',
        'manual/embedding',
      ],
    },
    {
      label: 'Project',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'manual/status',
        'manual/parity',
      ],
    },
  ],

  gopyInternalsSidebar: [
    'gopy/index',
    {
      label: 'Pipeline',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'gopy/pipeline',
        'gopy/parser',
        'gopy/ast',
        'gopy/symtable',
        'gopy/compiler',
        'gopy/flowgraph',
        'gopy/assembler',
      ],
    },
    {
      label: 'Execution',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'gopy/vm',
        'gopy/frames',
        'gopy/specializer',
        'gopy/tier2',
        'gopy/monitor',
        'gopy/gil',
        'gopy/exceptions',
      ],
    },
    {
      label: 'Runtime',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'gopy/objects',
        'gopy/types',
        'gopy/gc',
        'gopy/imports',
        'gopy/generators',
      ],
    },
  ],

  cpythonInternalsSidebar: [
    'cpython/index',
    {
      label: 'Pipeline',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'cpython/pipeline',
        'cpython/parser',
        'cpython/ast',
        'cpython/symtable',
        'cpython/compiler',
        'cpython/flowgraph',
        'cpython/assembler',
      ],
    },
    {
      label: 'Execution',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'cpython/vm',
        'cpython/frames',
        'cpython/specializer',
        'cpython/tier2',
        'cpython/monitor',
        'cpython/gil',
        'cpython/exceptions',
      ],
    },
    {
      label: 'Runtime',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'cpython/objects',
        'cpython/types',
        'cpython/gc',
        'cpython/imports',
        'cpython/generators',
      ],
    },
  ],

  annotationsSidebar: [
    'annotations/index',
    {
      label: 'Parser/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/parser/index'},
      items: [
        'annotations/parser/token',
        'annotations/parser/lexer',
        'annotations/parser/pegen',
        'annotations/parser/action_helpers',
        'annotations/parser/pegen_errors',
        'annotations/parser/string_parser',
        'annotations/parser/lexer_state',
        'annotations/parser/file_tokenizer',
        'annotations/parser/string_tokenizer',
        'annotations/parser/tokenizer_helpers',
        'annotations/parser/asdl',
      ],
    },
    {
      label: 'Python/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/python/index'},
      items: [
        'annotations/python/ast',
        'annotations/python/symtable',
        'annotations/python/compile',
        'annotations/python/flowgraph',
        'annotations/python/assemble',
        'annotations/python/ceval',
        'annotations/python/marshal',
        'annotations/python/errors',
        'annotations/python/import',
        'annotations/python/ceval_gil',
        'annotations/python/gc',
        'annotations/python/traceback',
        'annotations/python/bltinmodule',
        'annotations/python/context',
        'annotations/python/hamt',
        'annotations/python/warnings',
        'annotations/python/sysmodule',
        'annotations/python/pythonrun',
        'annotations/python/pylifecycle',
        'annotations/python/modsupport',
        'annotations/python/getargs',
        'annotations/python/thread',
        'annotations/python/thread_posix',
        'annotations/python/preconfig',
        'annotations/python/python_tokenize',
        'annotations/python/initconfig',
        'annotations/python/frozen',
        'annotations/python/bootstrap_hash',
        'annotations/python/specialize',
        'annotations/python/optimizer',
        'annotations/python/ceval_tracing',
        'annotations/python/exceptions',
        'annotations/python/codecs',
        'annotations/python/monitoring',
        'annotations/python/crossinterp',
        'annotations/python/parking_lot',
        'annotations/python/freelists',
        'annotations/python/typevarobj',
        'annotations/python/dtoa',
        'annotations/python/format',
        'annotations/python/bytecodes',
        'annotations/python/pystate',
        'annotations/python/structmember',
        'annotations/python/ceval_executor',
        'annotations/python/pytime',
        'annotations/python/intrinsics',
        'annotations/python/suggestions',
        'annotations/python/ceval_macros',
        'annotations/python/fileutils',
        'annotations/python/pathconfig',
        'annotations/python/pyhash',
        'annotations/python/gc_free_threading',
        'annotations/python/mystrtoul',
        'annotations/python/mysnprintf',
        'annotations/python/pytime_impl',
        'annotations/python/ast_unparse',
        'annotations/python/ast_opt',
        'annotations/python/python_ast',
      ],
    },
    {
      label: 'Objects/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/objects/index'},
      items: [
        'annotations/objects/object',
        'annotations/objects/typeobject',
        'annotations/objects/abstract',
        'annotations/objects/codeobject',
        'annotations/objects/funcobject',
        'annotations/objects/longobject',
        'annotations/objects/tupleobject',
        'annotations/objects/listobject',
        'annotations/objects/floatobject',
        'annotations/objects/dictobject',
        'annotations/objects/setobject',
        'annotations/objects/genobject',
        'annotations/objects/exceptions',
        'annotations/objects/unicodeobject',
        'annotations/objects/bytesobject',
        'annotations/objects/boolobject',
        'annotations/objects/complexobject',
        'annotations/objects/bytearrayobject',
        'annotations/objects/rangeobject',
        'annotations/objects/moduleobject',
        'annotations/objects/namespaceobject',
        'annotations/objects/descrobject',
        'annotations/objects/iterobject',
        'annotations/objects/weakrefobject',
        'annotations/objects/cellobject',
        'annotations/objects/frameobject',
        'annotations/objects/memoryobject',
        'annotations/objects/sliceobject',
        'annotations/objects/structseq',
        'annotations/objects/odictobject',
        'annotations/objects/classobject',
        'annotations/objects/methodobject',
        'annotations/objects/genericaliasobject',
        'annotations/objects/unionobject',
        'annotations/objects/call',
        'annotations/objects/fileobject',
        'annotations/objects/interpolationobject',
        'annotations/objects/capsule',
        'annotations/objects/obmalloc',
        'annotations/objects/bytes_methods',
      ],
    },
    {
      label: 'Include/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/include/index'},
      items: [
        'annotations/include/object',
        'annotations/include/abstract',
        'annotations/include/unicodeobject',
        'annotations/include/listobject',
        'annotations/include/pyerrors',
        'annotations/include/cpython_object',
        'annotations/include/cpython_code',
        'annotations/include/cpython_funcobject',
        'annotations/include/cpython_dictobject',
        'annotations/include/cpython_listobject',
        'annotations/include/cpython_tupleobject',
        'annotations/include/cpython_frame',
        'annotations/include/cpython_abstract',
        'annotations/include/cpython_bytesobject',
        'annotations/include/cpython_setobject',
        'annotations/include/cpython_genobject',
        'annotations/include/cpython_moduleobject',
        'annotations/include/cpython_descrobject',
        'annotations/include/cpython_weakrefobject',
        'annotations/include/cpython_iterobject',
        'annotations/include/cpython_classobject',
        'annotations/include/cpython_longobject',
        'annotations/include/cpython_floatobject',
        'annotations/include/cpython_methodobject',
        'annotations/include/cpython_complexobject',
        'annotations/include/cpython_namespaceobject',
        {
          label: 'internal/',
          type: 'category',
          collapsed: true,
          link: {type: 'doc', id: 'annotations/include/internal/index'},
          items: [
            'annotations/include/internal/pycore_interp',
            'annotations/include/internal/pycore_frame',
            'annotations/include/internal/pycore_gc',
            'annotations/include/internal/pycore_ceval',
            'annotations/include/internal/pycore_code',
            'annotations/include/internal/pycore_dict',
            'annotations/include/internal/pycore_object',
            'annotations/include/internal/pycore_list',
            'annotations/include/internal/pycore_tuple',
            'annotations/include/internal/pycore_unicode',
            'annotations/include/internal/pycore_exceptions',
            'annotations/include/internal/pycore_runtime',
            'annotations/include/internal/pycore_typeobject',
            'annotations/include/internal/pycore_import',
            'annotations/include/internal/pycore_tstate',
            'annotations/include/internal/pycore_long',
            'annotations/include/internal/pycore_function',
            'annotations/include/internal/pycore_weakref',
            'annotations/include/internal/pycore_opcode_metadata',
            'annotations/include/internal/pycore_compile',
            'annotations/include/internal/pycore_symtable',
            'annotations/include/internal/pycore_ast',
            'annotations/include/internal/pycore_genobject',
            'annotations/include/internal/pycore_call',
            'annotations/include/internal/pycore_lock',
            'annotations/include/internal/pycore_stackref',
            'annotations/include/internal/pycore_floatobject',
            'annotations/include/internal/pycore_context',
            'annotations/include/internal/pycore_moduleobject',
            'annotations/include/internal/pycore_setobject',
            'annotations/include/internal/pycore_time',
            'annotations/include/internal/pycore_ceval_state',
            'annotations/include/internal/pycore_pyerrors',
            'annotations/include/internal/pycore_descrobject',
            'annotations/include/internal/pycore_signal',
            'annotations/include/internal/pycore_hamt',
            'annotations/include/internal/pycore_cell',
            'annotations/include/internal/pycore_opcode_utils',
            'annotations/include/internal/pycore_fileutils',
            'annotations/include/internal/pycore_crossinterp',
            'annotations/include/internal/pycore_warnings',
            'annotations/include/internal/pycore_optimizer',
            'annotations/include/internal/pycore_instruments',
            'annotations/include/internal/pycore_modsupport',
            'annotations/include/internal/pycore_traceback',
            'annotations/include/internal/pycore_sysmodule',
            'annotations/include/internal/pycore_initconfig',
            'annotations/include/internal/pycore_bytes_methods',
            'annotations/include/internal/pycore_complexobject',
            'annotations/include/internal/pycore_namespace',
            'annotations/include/internal/pycore_global_objects',
            'annotations/include/internal/pycore_refcount',
            'annotations/include/internal/pycore_hashtable',
            'annotations/include/internal/pycore_mimalloc',
            'annotations/include/internal/pycore_pymem',
            'annotations/include/internal/pycore_structseq',
            'annotations/include/internal/pycore_bytearray',
            'annotations/include/internal/pycore_range',
            'annotations/include/internal/pycore_sliceobject',
            'annotations/include/internal/pycore_obmalloc',
            'annotations/include/internal/pycore_global_strings',
            'annotations/include/internal/pycore_pylifecycle',
            'annotations/include/internal/pycore_tracemalloc',
            'annotations/include/internal/pycore_pathconfig',
            'annotations/include/internal/pycore_global_objects_fini',
            'annotations/include/internal/pycore_bytes',
            'annotations/include/internal/pycore_memoryobject',
          ],
        },
      ],
    },
    {
      label: 'Modules/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/modules/index'},
      items: [
        'annotations/modules/posixmodule',
        'annotations/modules/functoolsmodule',
        'annotations/modules/weakref',
        'annotations/modules/errnomodule',
        'annotations/modules/abcmodule',
        'annotations/modules/collectionsmodule',
        'annotations/modules/iomodule',
        'annotations/modules/jsonmodule',
        'annotations/modules/bisectmodule',
        'annotations/modules/heapqmodule',
        'annotations/modules/operatormodule',
        'annotations/modules/structmodule',
        'annotations/modules/datetimemodule',
        'annotations/modules/csvmodule',
        'annotations/modules/randommodule',
        'annotations/modules/threadmodule',
        'annotations/modules/sremodule',
        'annotations/modules/signalmodule',
        'annotations/modules/picklemodule',
        'annotations/modules/hashlibmodule',
        'annotations/modules/socketmodule',
        'annotations/modules/asynciomodule',
        'annotations/modules/contextvarsmodule',
        'annotations/modules/queuemodule',
        'annotations/modules/bufferedio',
        'annotations/modules/textio',
        'annotations/modules/bytesio',
        'annotations/modules/timemodule',
        'annotations/modules/fileio',
        'annotations/modules/mathmodule',
        'annotations/modules/itertoolsmodule',
        'annotations/modules/selectmodule',
        'annotations/modules/decimalmodule',
        'annotations/modules/arraymodule',
        'annotations/modules/cmathmodule',
        'annotations/modules/jsonmodule_c',
        'annotations/modules/bisectmodule_c',
        'annotations/modules/gcmodule',
        'annotations/modules/unicodedatamodule',
        'annotations/modules/lsprofmodule',
        'annotations/modules/lzmamodule',
        'annotations/modules/sslmodule',
        'annotations/modules/zipimport',
        'annotations/modules/fcntlmodule',
        'annotations/modules/resource',
        'annotations/modules/cursesmodule',
        'annotations/modules/termiosmodule',
        'annotations/modules/pwdmodule',
        'annotations/modules/grpmodule',
        'annotations/modules/opcode_c',
        'annotations/modules/tracemalloc_c',
        'annotations/modules/heapq_c',
        'annotations/modules/symtable_c',
        'annotations/modules/csv_c',
        'annotations/modules/zlibmodule',
        'annotations/modules/bz2module',
        'annotations/modules/readline',
        'annotations/modules/asyncio_c',
        'annotations/modules/collections_c',
        'annotations/modules/struct_c',
        'annotations/modules/mmapmodule',
        'annotations/modules/statistics_c',
        'annotations/modules/elementtree_c',
        'annotations/modules/posixsubprocess',
        'annotations/modules/uuidmodule',
        'annotations/modules/codecsmodule',
        'annotations/modules/interpretersmodule',
        'annotations/modules/interpchannels',
        'annotations/modules/interpqueues',
        'annotations/modules/binascii',
        'annotations/modules/blake2module',
        'annotations/modules/multiprocessing_c',
        'annotations/modules/ctypes_c',
        'annotations/modules/sqlite_c',
        'annotations/modules/sha3module',
        'annotations/modules/md5module',
        'annotations/modules/sha1module',
        'annotations/modules/sha256module',
        'annotations/modules/sha512module',
        'annotations/modules/opcode_module',
        'annotations/modules/abc_c',
        'annotations/modules/decimal_c',
      ],
    },
    {
      label: 'Lib/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/lib/index'},
      items: [
        'annotations/lib/functools',
        'annotations/lib/types',
        'annotations/lib/contextlib',
        'annotations/lib/traceback',
        'annotations/lib/weakref',
        'annotations/lib/abc',
        'annotations/lib/collections',
        'annotations/lib/dataclasses',
        'annotations/lib/os',
        'annotations/lib/io',
        'annotations/lib/enum',
        'annotations/lib/pathlib',
        'annotations/lib/inspect',
        'annotations/lib/typing',
        'annotations/lib/copy',
        'annotations/lib/operator',
        'annotations/lib/heapq',
        'annotations/lib/csv',
        'annotations/lib/threading',
        'annotations/lib/re',
        'annotations/lib/json',
        'annotations/lib/datetime',
        'annotations/lib/random',
        'annotations/lib/pickle',
        'annotations/lib/hashlib',
        'annotations/lib/socket',
        'annotations/lib/struct',
        'annotations/lib/asyncio',
        'annotations/lib/unittest',
        'annotations/lib/logging',
        'annotations/lib/signal',
        'annotations/lib/select',
        'annotations/lib/string',
        'annotations/lib/textwrap',
        'annotations/lib/difflib',
        'annotations/lib/fnmatch',
        'annotations/lib/glob',
        'annotations/lib/shutil',
        'annotations/lib/argparse',
        'annotations/lib/configparser',
        'annotations/lib/tempfile',
        'annotations/lib/zipfile',
        'annotations/lib/tarfile',
        'annotations/lib/decimal',
        'annotations/lib/fractions',
        'annotations/lib/numbers',
        'annotations/lib/http_client',
        'annotations/lib/urllib_parse',
        'annotations/lib/xml_etree',
        'annotations/lib/html_parser',
        'annotations/lib/warnings',
        'annotations/lib/email',
        'annotations/lib/subprocess',
        'annotations/lib/concurrent_futures',
        'annotations/lib/multiprocessing',
        'annotations/lib/reprlib',
        'annotations/lib/pdb',
        'annotations/lib/profile',
        'annotations/lib/socketserver',
        'annotations/lib/http_server',
        'annotations/lib/unittest_mock',
        'annotations/lib/logging_handlers',
        'annotations/lib/logging_config',
        'annotations/lib/ctypes',
        'annotations/lib/importlib',
        'annotations/lib/ast',
        'annotations/lib/smtplib',
        'annotations/lib/pprint',
        'annotations/lib/uuid',
        'annotations/lib/dis',
        'annotations/lib/tokenize',
        'annotations/lib/linecache',
        'annotations/lib/copyreg',
        'annotations/lib/site',
        'annotations/lib/ftplib',
        'annotations/lib/imaplib',
        'annotations/lib/sqlite3',
        'annotations/lib/base64',
        'annotations/lib/bisect',
        'annotations/lib/gzip',
        'annotations/lib/locale',
        'annotations/lib/selectors',
        'annotations/lib/timeit',
        'annotations/lib/pkgutil',
        'annotations/lib/platform',
        'annotations/lib/mimetypes',
        'annotations/lib/calendar',
        'annotations/lib/compileall',
        'annotations/lib/py_compile',
        'annotations/lib/sched',
        'annotations/lib/fileinput',
        'annotations/lib/cProfile',
        'annotations/lib/pstats',
        'annotations/lib/netrc',
        'annotations/lib/xmlrpc',
        'annotations/lib/plistlib',
        'annotations/lib/codeop',
        'annotations/lib/pydoc',
        'annotations/lib/rlcompleter',
        'annotations/lib/mailbox',
        'annotations/lib/trace',
        'annotations/lib/tracemalloc',
        'annotations/lib/pyrepl',
        'annotations/lib/ipaddress',
        'annotations/lib/ssl',
        'annotations/lib/statistics',
        'annotations/lib/shlex',
        'annotations/lib/doctest',
        'annotations/lib/graphlib',
        'annotations/lib/symtable',
        'annotations/lib/lzma',
        'annotations/lib/gettext',
        'annotations/lib/tomllib',
        'annotations/lib/getpass',
        'annotations/lib/venv',
        'annotations/lib/pickletools',
        'annotations/lib/sysconfig',
        'annotations/lib/zipapp',
        'annotations/lib/urllib_request',
        'annotations/lib/urllib_error',
        'annotations/lib/html',
        'annotations/lib/stat',
        'annotations/lib/filecmp',
        'annotations/lib/pty',
        'annotations/lib/xmlrpc_server',
        'annotations/lib/getopt',
        'annotations/lib/colorsys',
        'annotations/lib/curses',
        'annotations/lib/dbm',
        'annotations/lib/optparse',
        'annotations/lib/wsgiref',
        'annotations/lib/xml_dom',
        'annotations/lib/xml_sax',
        'annotations/lib/urllib_response',
        'annotations/lib/urllib_robotparser',
        'annotations/lib/html_entities',
        'annotations/lib/opcode',
        'annotations/lib/codecs',
        'annotations/lib/keyword',
        'annotations/lib/code',
        'annotations/lib/lib2to3',
        'annotations/lib/modulefinder',
        'annotations/lib/hmac',
        'annotations/lib/secrets',
        'annotations/lib/shelve',
        'annotations/lib/queue',
        'annotations/lib/runpy',
        'annotations/lib/encodings',
        'annotations/lib/webbrowser',
        'annotations/lib/zoneinfo',
        'annotations/lib/cmd',
        'annotations/lib/tty',
        'annotations/lib/pyclbr',
        'annotations/lib/tabnanny',
        'annotations/lib/importlib_bootstrap',
        'annotations/lib/importlib_bootstrap_external',
        'annotations/lib/bdb',
        'annotations/lib/wave',
        'annotations/lib/quopri',
      ],
    },
  ],

  referenceSidebar: [
    'reference/index',
    'reference/opcodes',
    'reference/types',
    'reference/builtins',
    'reference/errors',
  ],

  modulesSidebar: [
    'modules/index',
    {
      label: 'Built-in',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'modules/sys',
        'modules/builtins',
      ],
    },
    {
      label: 'Standard library',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'modules/io',
        'modules/os',
        'modules/functools',
        'modules/collections',
        'modules/dataclasses',
        'modules/contextlib',
        'modules/traceback',
        'modules/weakref',
        'modules/types',
      ],
    },
  ],
};

module.exports = sidebars;
