/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  manualSidebar: [
    'manual/index',
    {
      label: 'Get started',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'manual/install',
        'manual/run',
        'manual/hello-world',
      ],
    },
    {
      label: 'Using gopy',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'manual/cli',
        'manual/repl',
        'manual/embedding',
      ],
    },
    {
      label: 'Project',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'manual/status',
        'manual/parity',
      ],
    },
  ],

  gopyInternalsSidebar: [
    'gopy/index',
    {
      label: 'Pipeline',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'gopy/pipeline',
        'gopy/parser',
        'gopy/ast',
        'gopy/symtable',
        'gopy/compiler',
        'gopy/flowgraph',
        'gopy/assembler',
      ],
    },
    {
      label: 'Execution',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'gopy/vm',
        'gopy/frames',
        'gopy/specializer',
        'gopy/tier2',
        'gopy/monitor',
        'gopy/gil',
        'gopy/exceptions',
      ],
    },
    {
      label: 'Runtime',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'gopy/objects',
        'gopy/types',
        'gopy/gc',
        'gopy/imports',
        'gopy/generators',
      ],
    },
  ],

  cpythonInternalsSidebar: [
    'cpython/index',
    {
      label: 'Pipeline',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'cpython/pipeline',
        'cpython/parser',
        'cpython/ast',
        'cpython/symtable',
        'cpython/compiler',
        'cpython/flowgraph',
        'cpython/assembler',
      ],
    },
    {
      label: 'Execution',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'cpython/vm',
        'cpython/frames',
        'cpython/specializer',
        'cpython/tier2',
        'cpython/monitor',
        'cpython/gil',
        'cpython/exceptions',
      ],
    },
    {
      label: 'Runtime',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'cpython/objects',
        'cpython/types',
        'cpython/gc',
        'cpython/imports',
        'cpython/generators',
      ],
    },
  ],

  annotationsSidebar: [
    'annotations/index',
    {
      label: 'Parser/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/parser/index'},
      items: [
        'annotations/parser/token',
        'annotations/parser/lexer',
        'annotations/parser/pegen',
        'annotations/parser/action_helpers',
        'annotations/parser/pegen_errors',
        'annotations/parser/string_parser',
        'annotations/parser/lexer_state',
        'annotations/parser/file_tokenizer',
        'annotations/parser/string_tokenizer',
        'annotations/parser/tokenizer_helpers',
        'annotations/parser/asdl',
      ],
    },
    {
      label: 'Python/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/python/index'},
      items: [
        'annotations/python/ast',
        'annotations/python/symtable',
        'annotations/python/compile',
        'annotations/python/flowgraph',
        'annotations/python/assemble',
        'annotations/python/ceval',
        'annotations/python/marshal',
        'annotations/python/errors',
        'annotations/python/import',
        'annotations/python/ceval_gil',
        'annotations/python/gc',
        'annotations/python/traceback',
        'annotations/python/bltinmodule',
        'annotations/python/context',
        'annotations/python/hamt',
        'annotations/python/warnings',
        'annotations/python/sysmodule',
        'annotations/python/pythonrun',
        'annotations/python/pylifecycle',
        'annotations/python/modsupport',
        'annotations/python/getargs',
        'annotations/python/thread',
        'annotations/python/thread_posix',
        'annotations/python/preconfig',
        'annotations/python/python_tokenize',
        'annotations/python/initconfig',
        'annotations/python/frozen',
        'annotations/python/bootstrap_hash',
        'annotations/python/specialize',
        'annotations/python/optimizer',
        'annotations/python/ceval_tracing',
        'annotations/python/exceptions',
        'annotations/python/codecs',
        'annotations/python/monitoring',
        'annotations/python/crossinterp',
        'annotations/python/parking_lot',
        'annotations/python/freelists',
        'annotations/python/typevarobj',
        'annotations/python/dtoa',
        'annotations/python/format',
        'annotations/python/bytecodes',
        'annotations/python/pystate',
        'annotations/python/structmember',
        'annotations/python/ceval_executor',
        'annotations/python/pytime',
        'annotations/python/intrinsics',
        'annotations/python/clinic',
        'annotations/python/suggestions',
        'annotations/python/pystate_detail',
        'annotations/python/errors_detail',
        'annotations/python/modsupport_detail',
        'annotations/python/ceval_macros',
        'annotations/python/fileutils',
        'annotations/python/pathconfig',
        'annotations/python/pyhash',
        'annotations/python/gc_free_threading',
        'annotations/python/mystrtoul',
        'annotations/python/mysnprintf',
        'annotations/python/pytime_impl',
        'annotations/python/ast_unparse',
        'annotations/python/ast_opt',
        'annotations/python/python_ast',
        'annotations/python/compile_detail',
        'annotations/python/symtable_detail',
        'annotations/python/getargs_detail',
        'annotations/python/errors_c_detail',
        'annotations/python/ceval_gil_detail',
        'annotations/python/import_detail',
        'annotations/python/ceval_detail',
        'annotations/python/peephole_detail',
        'annotations/python/ast_detail',
        'annotations/python/gcmodule_detail',
        'annotations/python/thread_detail',
        'annotations/python/sysmodule_detail',
        'annotations/python/pythonrun_detail',
        'annotations/python/bltinmodule_detail',
        'annotations/python/marshal_detail',
        'annotations/python/initconfig_detail',
        'annotations/python/frozen_detail',
        'annotations/python/codecs_detail',
        'annotations/python/specialize_detail',
        'annotations/python/clinic_detail',
        'annotations/python/opcode_metadata_detail',
        'annotations/python/bootstrap_hash_detail',
        'annotations/python/hamt_detail',
        'annotations/python/context_detail',
        'annotations/python/assemble_detail',
        'annotations/python/intrinsics_detail',
        'annotations/python/wordcode_helpers_detail',
        'annotations/python/exception_hierarchy_detail',
        'annotations/python/pystrtod_detail',
        'annotations/python/errors_c_detail',
        'annotations/python/traceback_c_detail',
        'annotations/python/python_ast_detail',
        'annotations/python/gc_c_detail',
        'annotations/python/thread_c_detail',
        'annotations/python/asdl_detail',
        'annotations/python/pylifecycle_detail',
      ],
    },
    {
      label: 'Objects/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/objects/index'},
      items: [
        'annotations/objects/object',
        'annotations/objects/typeobject',
        'annotations/objects/abstract',
        'annotations/objects/codeobject',
        'annotations/objects/funcobject',
        'annotations/objects/longobject',
        'annotations/objects/tupleobject',
        'annotations/objects/listobject',
        'annotations/objects/floatobject',
        'annotations/objects/dictobject',
        'annotations/objects/setobject',
        'annotations/objects/genobject',
        'annotations/objects/exceptions',
        'annotations/objects/unicodeobject',
        'annotations/objects/bytesobject',
        'annotations/objects/boolobject',
        'annotations/objects/complexobject',
        'annotations/objects/complexobject_detail',
        'annotations/objects/bytearrayobject',
        'annotations/objects/rangeobject',
        'annotations/objects/moduleobject',
        'annotations/objects/namespaceobject',
        'annotations/objects/descrobject',
        'annotations/objects/iterobject',
        'annotations/objects/weakrefobject',
        'annotations/objects/cellobject',
        'annotations/objects/frameobject',
        'annotations/objects/memoryobject',
        'annotations/objects/memoryobject_detail',
        'annotations/objects/sliceobject',
        'annotations/objects/sliceobject_detail',
        'annotations/objects/structseq',
        'annotations/objects/odictobject',
        'annotations/objects/classobject',
        'annotations/objects/methodobject',
        'annotations/objects/genericaliasobject',
        'annotations/objects/unionobject',
        'annotations/objects/call',
        'annotations/objects/fileobject',
        'annotations/objects/interpolationobject',
        'annotations/objects/capsule',
        'annotations/objects/obmalloc',
        'annotations/objects/bytes_methods',
        'annotations/objects/floatobject_detail',
        'annotations/objects/boolobject_detail',
        'annotations/objects/rangeobject_detail',
        'annotations/objects/tupleobject_detail',
        'annotations/objects/setobject_detail',
        'annotations/objects/bytesobject_detail',
        'annotations/objects/longobject_detail',
        'annotations/objects/complexobject_detail',
        'annotations/objects/memoryobject_detail',
        'annotations/objects/exceptions_c_detail',
        'annotations/objects/weakrefobject_detail',
        'annotations/objects/genericaliasobject_detail',
        'annotations/objects/typeobject_detail',
        'annotations/objects/descrobject_detail',
        'annotations/objects/abstract_detail',
        'annotations/objects/listobject_detail',
        'annotations/objects/dictobject_detail',
        'annotations/objects/unicodeobject_detail',
        'annotations/objects/funcobject_detail',
        'annotations/objects/methodobject_detail',
        'annotations/objects/iterobject_detail',
        'annotations/objects/cellobject_detail',
        'annotations/objects/frameobject_detail',
        'annotations/objects/genobject_detail',
        'annotations/objects/typevarobject_detail',
        'annotations/objects/namespaceobject_detail',
        'annotations/objects/moduleobject_detail',
        'annotations/objects/classobject_detail',
        'annotations/objects/codeobject_detail',
        'annotations/objects/obmalloc_detail',
        'annotations/objects/odictobject_detail',
        'annotations/objects/enumobject_detail',
        'annotations/objects/sliceobject_detail',
        'annotations/objects/typeobject_call_detail',
        'annotations/objects/longobject_bits_detail',
        'annotations/objects/capsuleobject_detail',
        'annotations/objects/fileobject_detail',
        'annotations/objects/descrobject_detail',
        'annotations/objects/objectobject_detail',
        'annotations/objects/bytearrayobject_detail',
        'annotations/objects/rangeobject_detail',
        'annotations/objects/iterobject_detail',
      ],
    },
    {
      label: 'Include/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/include/index'},
      items: [
        'annotations/include/object',
        'annotations/include/abstract',
        'annotations/include/unicodeobject',
        'annotations/include/listobject',
        'annotations/include/pyerrors',
        'annotations/include/cpython_object',
        'annotations/include/cpython_code',
        'annotations/include/cpython_funcobject',
        'annotations/include/cpython_dictobject',
        'annotations/include/cpython_listobject',
        'annotations/include/cpython_tupleobject',
        'annotations/include/cpython_frame',
        'annotations/include/cpython_abstract',
        'annotations/include/cpython_bytesobject',
        'annotations/include/cpython_setobject',
        'annotations/include/cpython_genobject',
        'annotations/include/cpython_moduleobject',
        'annotations/include/cpython_descrobject',
        'annotations/include/cpython_weakrefobject',
        'annotations/include/cpython_iterobject',
        'annotations/include/cpython_classobject',
        'annotations/include/cpython_longobject',
        'annotations/include/cpython_floatobject',
        'annotations/include/cpython_methodobject',
        'annotations/include/cpython_complexobject',
        'annotations/include/cpython_namespaceobject',
        {
          label: 'internal/',
          type: 'category',
          collapsed: true,
          link: {type: 'doc', id: 'annotations/include/internal/index'},
          items: [
            'annotations/include/internal/pycore_interp',
            'annotations/include/internal/pycore_frame',
            'annotations/include/internal/pycore_gc',
            'annotations/include/internal/pycore_ceval',
            'annotations/include/internal/pycore_code',
            'annotations/include/internal/pycore_dict',
            'annotations/include/internal/pycore_object',
            'annotations/include/internal/pycore_list',
            'annotations/include/internal/pycore_tuple',
            'annotations/include/internal/pycore_unicode',
            'annotations/include/internal/pycore_exceptions',
            'annotations/include/internal/pycore_runtime',
            'annotations/include/internal/pycore_typeobject',
            'annotations/include/internal/pycore_import',
            'annotations/include/internal/pycore_tstate',
            'annotations/include/internal/pycore_long',
            'annotations/include/internal/pycore_function',
            'annotations/include/internal/pycore_weakref',
            'annotations/include/internal/pycore_opcode_metadata',
            'annotations/include/internal/pycore_compile',
            'annotations/include/internal/pycore_symtable',
            'annotations/include/internal/pycore_ast',
            'annotations/include/internal/pycore_genobject',
            'annotations/include/internal/pycore_call',
            'annotations/include/internal/pycore_lock',
            'annotations/include/internal/pycore_stackref',
            'annotations/include/internal/pycore_floatobject',
            'annotations/include/internal/pycore_context',
            'annotations/include/internal/pycore_moduleobject',
            'annotations/include/internal/pycore_setobject',
            'annotations/include/internal/pycore_time',
            'annotations/include/internal/pycore_ceval_state',
            'annotations/include/internal/pycore_pyerrors',
            'annotations/include/internal/pycore_descrobject',
            'annotations/include/internal/pycore_signal',
            'annotations/include/internal/pycore_hamt',
            'annotations/include/internal/pycore_cell',
            'annotations/include/internal/pycore_opcode_utils',
            'annotations/include/internal/pycore_fileutils',
            'annotations/include/internal/pycore_crossinterp',
            'annotations/include/internal/pycore_warnings',
            'annotations/include/internal/pycore_optimizer',
            'annotations/include/internal/pycore_instruments',
            'annotations/include/internal/pycore_modsupport',
            'annotations/include/internal/pycore_traceback',
            'annotations/include/internal/pycore_sysmodule',
            'annotations/include/internal/pycore_initconfig',
            'annotations/include/internal/pycore_bytes_methods',
            'annotations/include/internal/pycore_complexobject',
            'annotations/include/internal/pycore_namespace',
            'annotations/include/internal/pycore_global_objects',
            'annotations/include/internal/pycore_refcount',
            'annotations/include/internal/pycore_hashtable',
            'annotations/include/internal/pycore_mimalloc',
            'annotations/include/internal/pycore_pymem',
            'annotations/include/internal/pycore_structseq',
            'annotations/include/internal/pycore_bytearray',
            'annotations/include/internal/pycore_range',
            'annotations/include/internal/pycore_sliceobject',
            'annotations/include/internal/pycore_obmalloc',
            'annotations/include/internal/pycore_global_strings',
            'annotations/include/internal/pycore_pylifecycle',
            'annotations/include/internal/pycore_tracemalloc',
            'annotations/include/internal/pycore_pathconfig',
            'annotations/include/internal/pycore_global_objects_fini',
            'annotations/include/internal/pycore_bytes',
            'annotations/include/internal/pycore_memoryobject',
            'annotations/include/internal/pycore_critical_section',
            'annotations/include/internal/pycore_pymath',
            'annotations/include/internal/pycore_statsmodule',
            'annotations/include/internal/pycore_typevarobj',
            'annotations/include/internal/pycore_crossinterp_data_registry',
            'annotations/include/internal/pycore_atomic',
            'annotations/include/internal/pycore_runtime_init',
            'annotations/include/internal/pycore_id',
            'annotations/include/internal/pycore_freelist',
            'annotations/include/internal/pycore_dtoa',
            'annotations/include/internal/pycore_object_stack',
            'annotations/include/internal/pycore_gc_detail',
            'annotations/include/internal/pycore_interp_detail',
            'annotations/include/internal/pycore_frame_detail',
            'annotations/include/internal/pycore_dict_detail',
            'annotations/include/internal/pycore_list_detail',
            'annotations/include/internal/pycore_tuple_detail',
            'annotations/include/internal/pycore_code_detail',
            'annotations/include/internal/pycore_ceval_detail',
            'annotations/include/internal/pycore_object_detail',
            'annotations/include/internal/pycore_symtable_detail',
            'annotations/include/internal/pycore_ast_detail',
            'annotations/include/internal/pycore_compile_detail',
            'annotations/include/internal/pycore_runtime_detail',
            'annotations/include/internal/pycore_parser_detail',
            'annotations/include/internal/pycore_import_detail',
          ],
        },
        'annotations/include/object_h_detail',
        'annotations/include/code_h_detail',
        'annotations/include/abstract_h_detail',
        'annotations/include/unicode_h_detail',
        'annotations/include/listobject_h_detail',
        'annotations/include/dictobject_h_detail',
        'annotations/include/tupleobject_h_detail',
        'annotations/include/setobject_h_detail',
        'annotations/include/bytesobject_h_detail',
        'annotations/include/funcobject_h_detail',
        'annotations/include/genobject_h_detail',
        'annotations/include/moduleobject_h_detail',
        'annotations/include/methodobject_h_detail',
        'annotations/include/descrobject_h_detail',
        'annotations/include/weakrefobject_h_detail',
        'annotations/include/pystate_h_detail',
        'annotations/include/import_h_detail',
        'annotations/include/eval_h_detail',
        'annotations/include/cpython_object_h_detail',
        'annotations/include/pycore_pylifecycle_h_detail',
        'annotations/include/pycore_traceback_h_detail',
        'annotations/include/code_h_detail',
        'annotations/include/pycore_warnings_h_detail',
        'annotations/include/pycore_signal_h_detail',
        'annotations/include/pycore_gc_h_detail',
        'annotations/include/pycore_code_h_detail',
        'annotations/include/pystate_cpython_h_detail',
        'annotations/include/pycore_interp_h_detail',
        'annotations/include/pycore_object_h_detail',
      ],
    },
    {
      label: 'Modules/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/modules/index'},
      items: [
        'annotations/modules/posixmodule',
        'annotations/modules/functoolsmodule',
        'annotations/modules/weakref',
        'annotations/modules/errnomodule',
        'annotations/modules/abcmodule',
        'annotations/modules/collectionsmodule',
        'annotations/modules/iomodule',
        'annotations/modules/jsonmodule',
        'annotations/modules/bisectmodule',
        'annotations/modules/heapqmodule',
        'annotations/modules/operatormodule',
        'annotations/modules/structmodule',
        'annotations/modules/datetimemodule',
        'annotations/modules/csvmodule',
        'annotations/modules/randommodule',
        'annotations/modules/threadmodule',
        'annotations/modules/sremodule',
        'annotations/modules/signalmodule',
        'annotations/modules/picklemodule',
        'annotations/modules/hashlibmodule',
        'annotations/modules/socketmodule',
        'annotations/modules/asynciomodule',
        'annotations/modules/contextvarsmodule',
        'annotations/modules/queuemodule',
        'annotations/modules/bufferedio',
        'annotations/modules/textio',
        'annotations/modules/bytesio',
        'annotations/modules/timemodule',
        'annotations/modules/fileio',
        'annotations/modules/mathmodule',
        'annotations/modules/itertoolsmodule',
        'annotations/modules/selectmodule',
        'annotations/modules/decimalmodule',
        'annotations/modules/arraymodule',
        'annotations/modules/cmathmodule',
        'annotations/modules/jsonmodule_c',
        'annotations/modules/bisectmodule_c',
        'annotations/modules/gcmodule',
        'annotations/modules/unicodedatamodule',
        'annotations/modules/lsprofmodule',
        'annotations/modules/lzmamodule',
        'annotations/modules/sslmodule',
        'annotations/modules/zipimport',
        'annotations/modules/fcntlmodule',
        'annotations/modules/resource',
        'annotations/modules/cursesmodule',
        'annotations/modules/termiosmodule',
        'annotations/modules/pwdmodule',
        'annotations/modules/grpmodule',
        'annotations/modules/opcode_c',
        'annotations/modules/tracemalloc_c',
        'annotations/modules/heapq_c',
        'annotations/modules/symtable_c',
        'annotations/modules/csv_c',
        'annotations/modules/zlibmodule',
        'annotations/modules/bz2module',
        'annotations/modules/readline',
        'annotations/modules/asyncio_c',
        'annotations/modules/collections_c',
        'annotations/modules/struct_c',
        'annotations/modules/mmapmodule',
        'annotations/modules/statistics_c',
        'annotations/modules/elementtree_c',
        'annotations/modules/posixsubprocess',
        'annotations/modules/uuidmodule',
        'annotations/modules/codecsmodule',
        'annotations/modules/interpretersmodule',
        'annotations/modules/interpchannels',
        'annotations/modules/interpqueues',
        'annotations/modules/binascii',
        'annotations/modules/blake2module',
        'annotations/modules/multiprocessing_c',
        'annotations/modules/ctypes_c',
        'annotations/modules/sqlite_c',
        'annotations/modules/sha3module',
        'annotations/modules/md5module',
        'annotations/modules/sha1module',
        'annotations/modules/sha256module',
        'annotations/modules/sha512module',
        'annotations/modules/opcode_module',
        'annotations/modules/abc_c',
        'annotations/modules/decimal_c',
        'annotations/modules/module_io_detail',
        'annotations/modules/module_csv_detail',
        'annotations/modules/module_json_detail',
        'annotations/modules/module_functools_detail',
        'annotations/modules/module_operator_detail',
        'annotations/modules/module_collections_detail',
        'annotations/modules/module_struct_detail',
        'annotations/modules/module_datetime_detail',
        'annotations/modules/module_abc_detail',
        'annotations/modules/module_weakref_detail',
        'annotations/modules/module_heapq_detail',
        'annotations/modules/module_bisect_detail',
        'annotations/modules/module_bufferedwriter_detail',
        'annotations/modules/module_fileio_detail',
        'annotations/modules/module_textiowrapper_detail',
        'annotations/modules/module_sre_detail',
        'annotations/modules/module_thread_detail',
        'annotations/modules/module_posix_detail',
        'annotations/modules/module_asyncio_detail',
        'annotations/modules/module_contextvars_detail',
        'annotations/modules/module_queue_detail',
        'annotations/modules/module_math_detail',
        'annotations/modules/module_ctypes_detail',
        'annotations/modules/module_cmath_detail',
        'annotations/modules/io_bufferedio_detail',
        'annotations/modules/io_fileio_detail',
        'annotations/modules/io_textio_detail',
        'annotations/modules/module_sre_detail',
        'annotations/modules/module_bisect_detail',
        'annotations/modules/module_pickle_detail',
      ],
    },
    {
      label: 'Lib/',
      type: 'category',
      collapsed: true,
      link: {type: 'doc', id: 'annotations/lib/index'},
      items: [
        'annotations/lib/functools',
        'annotations/lib/types',
        'annotations/lib/contextlib',
        'annotations/lib/contextlib_detail',
        'annotations/lib/traceback',
        'annotations/lib/weakref',
        'annotations/lib/abc',
        'annotations/lib/collections',
        'annotations/lib/collections_abc',
        'annotations/lib/collections_detail',
        'annotations/lib/dataclasses',
        'annotations/lib/dataclasses_detail',
        'annotations/lib/os',
        'annotations/lib/os_path_detail',
        'annotations/lib/io',
        'annotations/lib/io_detail',
        'annotations/lib/enum',
        'annotations/lib/enum_detail',
        'annotations/lib/pathlib',
        'annotations/lib/pathlib_detail',
        'annotations/lib/inspect',
        'annotations/lib/typing',
        'annotations/lib/typing_detail',
        'annotations/lib/copy',
        'annotations/lib/copy_detail',
        'annotations/lib/operator',
        'annotations/lib/heapq',
        'annotations/lib/heapq_detail',
        'annotations/lib/csv',
        'annotations/lib/threading',
        'annotations/lib/threading_detail',
        'annotations/lib/re',
        'annotations/lib/re_detail',
        'annotations/lib/json',
        'annotations/lib/datetime',
        'annotations/lib/random',
        'annotations/lib/pickle',
        'annotations/lib/hashlib',
        'annotations/lib/socket',
        'annotations/lib/struct',
        'annotations/lib/asyncio',
        'annotations/lib/asyncio_streams',
        'annotations/lib/asyncio_queues',
        'annotations/lib/asyncio_locks',
        'annotations/lib/asyncio_runner',
        'annotations/lib/asyncio_timeouts',
        'annotations/lib/asyncio_taskgroups',
        'annotations/lib/asyncio_subprocess',
        'annotations/lib/asyncio_unix_events',
        'annotations/lib/asyncio_windows_events',
        'annotations/lib/unittest',
        'annotations/lib/unittest_case',
        'annotations/lib/unittest_runner',
        'annotations/lib/unittest_loader',
        'annotations/lib/logging',
        'annotations/lib/signal',
        'annotations/lib/select',
        'annotations/lib/string',
        'annotations/lib/textwrap',
        'annotations/lib/difflib',
        'annotations/lib/fnmatch',
        'annotations/lib/fnmatch_detail',
        'annotations/lib/glob',
        'annotations/lib/glob_detail',
        'annotations/lib/shutil',
        'annotations/lib/shutil_detail',
        'annotations/lib/argparse',
        'annotations/lib/configparser',
        'annotations/lib/tempfile',
        'annotations/lib/zipfile',
        'annotations/lib/tarfile',
        'annotations/lib/decimal',
        'annotations/lib/fractions',
        'annotations/lib/numbers',
        'annotations/lib/http_client',
        'annotations/lib/urllib_parse',
        'annotations/lib/xml_etree',
        'annotations/lib/xml_etree_element',
        'annotations/lib/xml_sax_init',
        'annotations/lib/xml_sax_handler',
        'annotations/lib/html_parser',
        'annotations/lib/warnings',
        'annotations/lib/email',
        'annotations/lib/email_mime',
        'annotations/lib/email_message',
        'annotations/lib/email_policy',
        'annotations/lib/email_headerregistry',
        'annotations/lib/subprocess',
        'annotations/lib/concurrent_futures',
        'annotations/lib/concurrent_futures_thread',
        'annotations/lib/concurrent_futures_process',
        'annotations/lib/multiprocessing',
        'annotations/lib/reprlib',
        'annotations/lib/pdb',
        'annotations/lib/profile',
        'annotations/lib/socketserver',
        'annotations/lib/http_server',
        'annotations/lib/http_server_detail',
        'annotations/lib/unittest_mock',
        'annotations/lib/logging_handlers',
        'annotations/lib/logging_config',
        'annotations/lib/ctypes',
        'annotations/lib/importlib',
        'annotations/lib/importlib_abc',
        'annotations/lib/importlib_util',
        'annotations/lib/importlib_machinery',
        'annotations/lib/ast',
        'annotations/lib/smtplib',
        'annotations/lib/pprint',
        'annotations/lib/uuid',
        'annotations/lib/dis',
        'annotations/lib/tokenize',
        'annotations/lib/linecache',
        'annotations/lib/copyreg',
        'annotations/lib/site',
        'annotations/lib/ftplib',
        'annotations/lib/imaplib',
        'annotations/lib/sqlite3',
        'annotations/lib/base64',
        'annotations/lib/bisect',
        'annotations/lib/gzip',
        'annotations/lib/locale',
        'annotations/lib/selectors',
        'annotations/lib/timeit',
        'annotations/lib/pkgutil',
        'annotations/lib/platform',
        'annotations/lib/mimetypes',
        'annotations/lib/calendar',
        'annotations/lib/compileall',
        'annotations/lib/py_compile',
        'annotations/lib/sched',
        'annotations/lib/fileinput',
        'annotations/lib/cProfile',
        'annotations/lib/pstats',
        'annotations/lib/netrc',
        'annotations/lib/xmlrpc',
        'annotations/lib/plistlib',
        'annotations/lib/codeop',
        'annotations/lib/pydoc',
        'annotations/lib/rlcompleter',
        'annotations/lib/mailbox',
        'annotations/lib/trace',
        'annotations/lib/tracemalloc',
        'annotations/lib/pyrepl',
        'annotations/lib/ipaddress',
        'annotations/lib/ssl',
        'annotations/lib/statistics',
        'annotations/lib/shlex',
        'annotations/lib/doctest',
        'annotations/lib/graphlib',
        'annotations/lib/symtable',
        'annotations/lib/lzma',
        'annotations/lib/gettext',
        'annotations/lib/tomllib',
        'annotations/lib/getpass',
        'annotations/lib/venv',
        'annotations/lib/pickletools',
        'annotations/lib/sysconfig',
        'annotations/lib/zipapp',
        'annotations/lib/urllib_request',
        'annotations/lib/urllib_error',
        'annotations/lib/html',
        'annotations/lib/stat',
        'annotations/lib/filecmp',
        'annotations/lib/pty',
        'annotations/lib/xmlrpc_server',
        'annotations/lib/getopt',
        'annotations/lib/colorsys',
        'annotations/lib/curses',
        'annotations/lib/dbm',
        'annotations/lib/optparse',
        'annotations/lib/wsgiref',
        'annotations/lib/xml_dom',
        'annotations/lib/xml_sax',
        'annotations/lib/urllib_response',
        'annotations/lib/urllib_robotparser',
        'annotations/lib/html_entities',
        'annotations/lib/opcode',
        'annotations/lib/codecs',
        'annotations/lib/keyword',
        'annotations/lib/code',
        'annotations/lib/lib2to3',
        'annotations/lib/modulefinder',
        'annotations/lib/hmac',
        'annotations/lib/secrets',
        'annotations/lib/shelve',
        'annotations/lib/queue',
        'annotations/lib/runpy',
        'annotations/lib/encodings',
        'annotations/lib/webbrowser',
        'annotations/lib/zoneinfo',
        'annotations/lib/cmd',
        'annotations/lib/tty',
        'annotations/lib/pyclbr',
        'annotations/lib/tabnanny',
        'annotations/lib/importlib_bootstrap',
        'annotations/lib/importlib_bootstrap_external',
        'annotations/lib/genericpath',
        'annotations/lib/ntpath',
        'annotations/lib/posixpath',
        'annotations/lib/contextvars',
        'annotations/lib/threading_local',
        'annotations/lib/multiprocessing_process',
        'annotations/lib/asyncio_tasks',
        'annotations/lib/asyncio_events',
        'annotations/lib/asyncio_coroutines',
        'annotations/lib/asyncio_base_events',
        'annotations/lib/asyncio_selector_events',
        'annotations/lib/asyncio_futures',
        'annotations/lib/asyncio_protocols',
        'annotations/lib/asyncio_transports',
        'annotations/lib/multiprocessing_connection',
        'annotations/lib/multiprocessing_pool',
        'annotations/lib/multiprocessing_managers',
        'annotations/lib/http_cookiejar',
        'annotations/lib/http_cookies',
        'annotations/lib/bdb',
        'annotations/lib/wave',
        'annotations/lib/quopri',
        'annotations/lib/traceback_detail',
        'annotations/lib/warnings_detail',
        'annotations/lib/weakref_detail',
        'annotations/lib/abc_detail',
        'annotations/lib/operator_detail',
        'annotations/lib/bisect_detail',
        'annotations/lib/pprint_detail',
        'annotations/lib/textwrap_detail',
        'annotations/lib/string_detail',
        'annotations/lib/csv_detail',
        'annotations/lib/configparser_detail',
        'annotations/lib/argparse_detail',
        'annotations/lib/logging_init_detail',
        'annotations/lib/logging_handlers_detail',
        'annotations/lib/logging_config_detail',
        'annotations/lib/unittest_mock_detail',
        'annotations/lib/doctest_detail',
        'annotations/lib/pickle_detail',
        'annotations/lib/json_encoder_detail',
        'annotations/lib/json_decoder_detail',
        'annotations/lib/urllib_parse_detail',
        'annotations/lib/socket_detail',
        'annotations/lib/ssl_detail',
        'annotations/lib/select_detail',
        'annotations/lib/zipfile_detail',
        'annotations/lib/tarfile_detail',
        'annotations/lib/gzip_detail',
        'annotations/lib/decimal_detail',
        'annotations/lib/fractions_detail',
        'annotations/lib/statistics_detail',
        'annotations/lib/datetime_detail',
        'annotations/lib/calendar_detail',
        'annotations/lib/time_detail',
        'annotations/lib/random_detail',
        'annotations/lib/hashlib_detail',
        'annotations/lib/hmac_detail',
        'annotations/lib/subprocess_detail',
        'annotations/lib/signal_detail',
        'annotations/lib/mmap_detail',
        'annotations/lib/threading_detail',
        'annotations/lib/queue_detail',
        'annotations/lib/concurrent_futures_detail',
        'annotations/lib/io_module_detail',
        'annotations/lib/contextlib_advanced_detail',
        'annotations/lib/functools_detail',
        'annotations/lib/http_client_detail',
        'annotations/lib/xmlrpc_client_detail',
        'annotations/lib/html_parser_detail',
        'annotations/lib/os_module_detail',
        'annotations/lib/collections_module_detail',
        'annotations/lib/abc_module_detail',
        'annotations/lib/contextlib_module_detail',
        'annotations/lib/dataclasses_detail',
        'annotations/lib/enum_module_detail',
        'annotations/lib/typing_module_detail',
        'annotations/lib/re_module_detail',
        'annotations/lib/re_compiler_detail',
        'annotations/lib/re_parser_detail',
        'annotations/lib/copy_module_detail',
        'annotations/lib/pprint_module_detail',
        'annotations/lib/reprlib_detail',
        'annotations/lib/ast_lib_detail',
        'annotations/lib/dis_detail',
        'annotations/lib/inspect_detail',
        'annotations/lib/importlib_bootstrap_detail',
        'annotations/lib/importlib_bootstrap_external_detail',
        'annotations/lib/importlib_util_detail',
      ],
    },
  ],

  referenceSidebar: [
    'reference/index',
    'reference/opcodes',
    'reference/types',
    'reference/builtins',
    'reference/errors',
  ],

  modulesSidebar: [
    'modules/index',
    {
      label: 'Built-in',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'modules/sys',
        'modules/builtins',
      ],
    },
    {
      label: 'Standard library',
      type: 'category',
      className: 'sidebar-heading',
      collapsed: false,
      items: [
        'modules/io',
        'modules/os',
        'modules/functools',
        'modules/collections',
        'modules/dataclasses',
        'modules/contextlib',
        'modules/traceback',
        'modules/weakref',
        'modules/types',
      ],
    },
  ],
};

module.exports = sidebars;
